# Mario Party (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "globals.inc"
.include "macros.inc"

glabel func_8003C2D0
/* 03CED0 8003C2D0 3C01800D */  lui   $at, %hi(D_800D6050) # $at, 0x800d
/* 03CED4 8003C2D4 AC246050 */  sw    $a0, %lo(D_800D6050)($at)
/* 03CED8 8003C2D8 00001821 */  addu  $v1, $zero, $zero
/* 03CEDC 8003C2DC 2404FFFF */  li    $a0, -1
/* 03CEE0 8003C2E0 00031100 */  sll   $v0, $v1, 4
.L8003C2E4:
/* 03CEE4 8003C2E4 3C01800D */  lui   $at, 0x800d
/* 03CEE8 8003C2E8 00220821 */  addu  $at, $at, $v0
/* 03CEEC 8003C2EC A0246058 */  sb    $a0, 0x6058($at)
/* 03CEF0 8003C2F0 24630001 */  addiu $v1, $v1, 1
/* 03CEF4 8003C2F4 28620014 */  slti  $v0, $v1, 0x14
/* 03CEF8 8003C2F8 5440FFFA */  bnezl $v0, .L8003C2E4
/* 03CEFC 8003C2FC 00031100 */   sll   $v0, $v1, 4
/* 03CF00 8003C300 3C01800D */  lui   $at, 0x800d
/* 03CF04 8003C304 03E00008 */  jr    $ra
/* 03CF08 8003C308 A4206054 */   sh    $zero, 0x6054($at)

glabel func_8003C30C
/* 03CF0C 8003C30C 03E00008 */  jr    $ra
/* 03CF10 8003C310 00000000 */   nop   

glabel func_8003C314
/* 03CF14 8003C314 3C02800D */  lui   $v0, %hi(D_800D6054) # $v0, 0x800d
/* 03CF18 8003C318 94426054 */  lhu   $v0, %lo(D_800D6054)($v0)
/* 03CF1C 8003C31C 24430001 */  addiu $v1, $v0, 1
/* 03CF20 8003C320 3C01800D */  lui   $at, %hi(D_800D6054) # $at, 0x800d
/* 03CF24 8003C324 A4236054 */  sh    $v1, %lo(D_800D6054)($at)
/* 03CF28 8003C328 00021400 */  sll   $v0, $v0, 0x10
/* 03CF2C 8003C32C 00021303 */  sra   $v0, $v0, 0xc
/* 03CF30 8003C330 3C03800D */  lui   $v1, %hi(D_800D6058) # $v1, 0x800d
/* 03CF34 8003C334 24636058 */  addiu $v1, %lo(D_800D6058) # addiu $v1, $v1, 0x6058
/* 03CF38 8003C338 00431021 */  addu  $v0, $v0, $v1
/* 03CF3C 8003C33C A0440000 */  sb    $a0, ($v0)
/* 03CF40 8003C340 AC450004 */  sw    $a1, 4($v0)
/* 03CF44 8003C344 A446000C */  sh    $a2, 0xc($v0)
/* 03CF48 8003C348 03E00008 */  jr    $ra
/* 03CF4C 8003C34C A447000E */   sh    $a3, 0xe($v0)

glabel func_8003C350
/* 03CF50 8003C350 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 03CF54 8003C354 AFBF001C */  sw    $ra, 0x1c($sp)
/* 03CF58 8003C358 AFB20018 */  sw    $s2, 0x18($sp)
/* 03CF5C 8003C35C AFB10014 */  sw    $s1, 0x14($sp)
/* 03CF60 8003C360 AFB00010 */  sw    $s0, 0x10($sp)
/* 03CF64 8003C364 00008821 */  addu  $s1, $zero, $zero
/* 03CF68 8003C368 3C12800D */  lui   $s2, %hi(D_800D6058) # $s2, 0x800d
/* 03CF6C 8003C36C 26526058 */  addiu $s2, %lo(D_800D6058) # addiu $s2, $s2, 0x6058
/* 03CF70 8003C370 00111100 */  sll   $v0, $s1, 4
.L8003C374:
/* 03CF74 8003C374 00528021 */  addu  $s0, $v0, $s2
/* 03CF78 8003C378 82020000 */  lb    $v0, ($s0)
/* 03CF7C 8003C37C 04420008 */  bltzl $v0, .L8003C3A0
/* 03CF80 8003C380 26310001 */   addiu $s1, $s1, 1
/* 03CF84 8003C384 8E040008 */  lw    $a0, 8($s0)
/* 03CF88 8003C388 50800004 */  beql  $a0, $zero, .L8003C39C
/* 03CF8C 8003C38C AE000008 */   sw    $zero, 8($s0)
/* 03CF90 8003C390 0C017764 */  jal   EndProcess
/* 03CF94 8003C394 00000000 */   nop   
/* 03CF98 8003C398 AE000008 */  sw    $zero, 8($s0)
.L8003C39C:
/* 03CF9C 8003C39C 26310001 */  addiu $s1, $s1, 1
.L8003C3A0:
/* 03CFA0 8003C3A0 2A220014 */  slti  $v0, $s1, 0x14
/* 03CFA4 8003C3A4 1440FFF3 */  bnez  $v0, .L8003C374
/* 03CFA8 8003C3A8 00111100 */   sll   $v0, $s1, 4
/* 03CFAC 8003C3AC 8FBF001C */  lw    $ra, 0x1c($sp)
/* 03CFB0 8003C3B0 8FB20018 */  lw    $s2, 0x18($sp)
/* 03CFB4 8003C3B4 8FB10014 */  lw    $s1, 0x14($sp)
/* 03CFB8 8003C3B8 8FB00010 */  lw    $s0, 0x10($sp)
/* 03CFBC 8003C3BC 03E00008 */  jr    $ra
/* 03CFC0 8003C3C0 27BD0020 */   addiu $sp, $sp, 0x20

D_8003C3C4:
/* 03CFC4 8003C3C4 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 03CFC8 8003C3C8 AFBF001C */  sw    $ra, 0x1c($sp)
/* 03CFCC 8003C3CC AFB00018 */  sw    $s0, 0x18($sp)
/* 03CFD0 8003C3D0 F7BA0038 */  sdc1  $f26, 0x38($sp)
/* 03CFD4 8003C3D4 F7B80030 */  sdc1  $f24, 0x30($sp)
/* 03CFD8 8003C3D8 F7B60028 */  sdc1  $f22, 0x28($sp)
/* 03CFDC 8003C3DC 0C018CEA */  jal   GetCurrentProcess
/* 03CFE0 8003C3E0 F7B40020 */   sdc1  $f20, 0x20($sp)
/* 03CFE4 8003C3E4 8C50008C */  lw    $s0, 0x8c($v0)
/* 03CFE8 8003C3E8 4480A000 */  mtc1  $zero, $f20
/* 03CFEC 8003C3EC 00000000 */  nop   
/* 03CFF0 8003C3F0 4600A586 */  mov.s $f22, $f20
/* 03CFF4 8003C3F4 4480D000 */  mtc1  $zero, $f26
/* 03CFF8 8003C3F8 3C0143B4 */  li    $at, 0x43B40000 # 360.000000
/* 03CFFC 8003C3FC 4481C000 */  mtc1  $at, $f24
/* 03D000 8003C400 00000000 */  nop   
glabel func_8003C404
/* 03D004 8003C404 0C02BAB0 */  jal   func_800AEAC0
/* 03D008 8003C408 4600B306 */   mov.s $f12, $f22
/* 03D00C 8003C40C 46000086 */  mov.s $f2, $f0
/* 03D010 8003C410 461A103C */  c.lt.s $f2, $f26
/* 03D014 8003C414 00000000 */  nop   
/* 03D018 8003C418 00000000 */  nop   
/* 03D01C 8003C41C 45000002 */  bc1f  .L8003C428
/* 03D020 8003C420 46001106 */   mov.s $f4, $f2
/* 03D024 8003C424 46001107 */  neg.s $f4, $f2
.L8003C428:
/* 03D028 8003C428 3C01437F */  li    $at, 0x437F0000 # 255.000000
/* 03D02C 8003C42C 44810000 */  mtc1  $at, $f0
/* 03D030 8003C430 00000000 */  nop   
/* 03D034 8003C434 46002002 */  mul.s $f0, $f4, $f0
/* 03D038 8003C438 4600008D */  trunc.w.s $f2, $f0
/* 03D03C 8003C43C 44071000 */  mfc1  $a3, $f2
/* 03D040 8003C440 3C0140C0 */  li    $at, 0x40C00000 # 6.000000
/* 03D044 8003C444 44810000 */  mtc1  $at, $f0
/* 03D048 8003C448 00000000 */  nop   
/* 03D04C 8003C44C 4600B580 */  add.s $f22, $f22, $f0
/* 03D050 8003C450 4616C03C */  c.lt.s $f24, $f22
/* 03D054 8003C454 00000000 */  nop   
/* 03D058 8003C458 00000000 */  nop   
/* 03D05C 8003C45C 45030001 */  bc1tl .L8003C464
/* 03D060 8003C460 4618B581 */   sub.s $f22, $f22, $f24
.L8003C464:
/* 03D064 8003C464 86040000 */  lh    $a0, ($s0)
/* 03D068 8003C468 86050002 */  lh    $a1, 2($s0)
/* 03D06C 8003C46C AFA00010 */  sw    $zero, 0x10($sp)
/* 03D070 8003C470 240200C0 */  li    $v0, 192
/* 03D074 8003C474 AFA20014 */  sw    $v0, 0x14($sp)
/* 03D078 8003C478 240600FF */  li    $a2, 255
/* 03D07C 8003C47C 0C019D56 */  jal   func_80067558
/* 03D080 8003C480 30E700FF */   andi  $a3, $a3, 0xff
/* 03D084 8003C484 0C02BAB0 */  jal   func_800AEAC0
/* 03D088 8003C488 4600A306 */   mov.s $f12, $f20
/* 03D08C 8003C48C 461A003C */  c.lt.s $f0, $f26
/* 03D090 8003C490 3C013E4C */  li    $at, 0x3E4C0000 # 0.199219
/* 03D094 8003C494 3421CCCD */  ori   $at, (0x3E4CCCCD & 0xFFFF) # ori $at, $at, 0xcccd
/* 03D098 8003C498 44810000 */  mtc1  $at, $f0
/* 03D09C 8003C49C 00000000 */  nop   
/* 03D0A0 8003C4A0 45030001 */  bc1tl .L8003C4A8
/* 03D0A4 8003C4A4 4600D006 */   mov.s $f0, $f26
.L8003C4A8:
/* 03D0A8 8003C4A8 46000086 */  mov.s $f2, $f0
/* 03D0AC 8003C4AC 3C014170 */  li    $at, 0x41700000 # 15.000000
/* 03D0B0 8003C4B0 44810000 */  mtc1  $at, $f0
/* 03D0B4 8003C4B4 00000000 */  nop   
/* 03D0B8 8003C4B8 4600A500 */  add.s $f20, $f20, $f0
/* 03D0BC 8003C4BC 4614C03C */  c.lt.s $f24, $f20
/* 03D0C0 8003C4C0 00000000 */  nop   
/* 03D0C4 8003C4C4 00000000 */  nop   
/* 03D0C8 8003C4C8 45030001 */  bc1tl .L8003C4D0
/* 03D0CC 8003C4CC 4618A501 */   sub.s $f20, $f20, $f24
.L8003C4D0:
/* 03D0D0 8003C4D0 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 03D0D4 8003C4D4 44810000 */  mtc1  $at, $f0
/* 03D0D8 8003C4D8 00000000 */  nop   
/* 03D0DC 8003C4DC 46001000 */  add.s $f0, $f2, $f0
/* 03D0E0 8003C4E0 86040000 */  lh    $a0, ($s0)
/* 03D0E4 8003C4E4 86050002 */  lh    $a1, 2($s0)
/* 03D0E8 8003C4E8 44060000 */  mfc1  $a2, $f0
/* 03D0EC 8003C4EC 44070000 */  mfc1  $a3, $f0
/* 03D0F0 8003C4F0 0C019CD5 */  jal   func_80067354
/* 03D0F4 8003C4F4 00000000 */   nop   
/* 03D0F8 8003C4F8 0C018D6D */  jal   SleepVProcess
/* 03D0FC 8003C4FC 00000000 */   nop   
/* 03D100 8003C500 0800F101 */  j     func_8003C404
/* 03D104 8003C504 00000000 */   nop   

/* 03D108 8003C508 8FBF001C */  lw    $ra, 0x1c($sp)
/* 03D10C 8003C50C 8FB00018 */  lw    $s0, 0x18($sp)
/* 03D110 8003C510 D7BA0038 */  ldc1  $f26, 0x38($sp)
/* 03D114 8003C514 D7B80030 */  ldc1  $f24, 0x30($sp)
/* 03D118 8003C518 D7B60028 */  ldc1  $f22, 0x28($sp)
/* 03D11C 8003C51C D7B40020 */  ldc1  $f20, 0x20($sp)
/* 03D120 8003C520 03E00008 */  jr    $ra
/* 03D124 8003C524 27BD0040 */   addiu $sp, $sp, 0x40

glabel func_8003C528
/* 03D128 8003C528 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 03D12C 8003C52C AFBF001C */  sw    $ra, 0x1c($sp)
/* 03D130 8003C530 AFB20018 */  sw    $s2, 0x18($sp)
/* 03D134 8003C534 AFB10014 */  sw    $s1, 0x14($sp)
/* 03D138 8003C538 AFB00010 */  sw    $s0, 0x10($sp)
/* 03D13C 8003C53C 00808821 */  addu  $s1, $a0, $zero
/* 03D140 8003C540 00A09021 */  addu  $s2, $a1, $zero
/* 03D144 8003C544 3C048004 */  lui   $a0, %hi(D_8003C3C4) # $a0, 0x8004
/* 03D148 8003C548 2484C3C4 */  addiu $a0, %lo(D_8003C3C4) # addiu $a0, $a0, -0x3c3c
/* 03D14C 8003C54C 24051005 */  li    $a1, 4101
/* 03D150 8003C550 00003021 */  addu  $a2, $zero, $zero
/* 03D154 8003C554 0C01770A */  jal   InitProcess
/* 03D158 8003C558 24070040 */   li    $a3, 64
/* 03D15C 8003C55C 00408021 */  addu  $s0, $v0, $zero
/* 03D160 8003C560 8E040018 */  lw    $a0, 0x18($s0)
/* 03D164 8003C564 0C016628 */  jal   Malloc
/* 03D168 8003C568 24050004 */   li    $a1, 4
/* 03D16C 8003C56C AE02008C */  sw    $v0, 0x8c($s0)
/* 03D170 8003C570 A4510000 */  sh    $s1, ($v0)
/* 03D174 8003C574 A4520002 */  sh    $s2, 2($v0)
/* 03D178 8003C578 02001021 */  addu  $v0, $s0, $zero
/* 03D17C 8003C57C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 03D180 8003C580 8FB20018 */  lw    $s2, 0x18($sp)
/* 03D184 8003C584 8FB10014 */  lw    $s1, 0x14($sp)
/* 03D188 8003C588 8FB00010 */  lw    $s0, 0x10($sp)
/* 03D18C 8003C58C 03E00008 */  jr    $ra
/* 03D190 8003C590 27BD0020 */   addiu $sp, $sp, 0x20

glabel func_8003C594
/* 03D194 8003C594 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 03D198 8003C598 AFBF0030 */  sw    $ra, 0x30($sp)
/* 03D19C 8003C59C AFB3002C */  sw    $s3, 0x2c($sp)
/* 03D1A0 8003C5A0 AFB20028 */  sw    $s2, 0x28($sp)
/* 03D1A4 8003C5A4 AFB10024 */  sw    $s1, 0x24($sp)
/* 03D1A8 8003C5A8 AFB00020 */  sw    $s0, 0x20($sp)
/* 03D1AC 8003C5AC F7B40038 */  sdc1  $f20, 0x38($sp)
/* 03D1B0 8003C5B0 00809821 */  addu  $s3, $a0, $zero
/* 03D1B4 8003C5B4 00058C00 */  sll   $s1, $a1, 0x10
/* 03D1B8 8003C5B8 3C10800C */  lui   $s0, %hi(D_800C430C) # $s0, 0x800c
/* 03D1BC 8003C5BC 2610430C */  addiu $s0, %lo(D_800C430C) # addiu $s0, $s0, 0x430c
/* 03D1C0 8003C5C0 00118BC3 */  sra   $s1, $s1, 0xf
/* 03D1C4 8003C5C4 02308021 */  addu  $s0, $s1, $s0
/* 03D1C8 8003C5C8 3C12800C */  lui   $s2, %hi(D_800C4314) # $s2, 0x800c
/* 03D1CC 8003C5CC 26524314 */  addiu $s2, %lo(D_800C4314) # addiu $s2, $s2, 0x4314
/* 03D1D0 8003C5D0 02329021 */  addu  $s2, $s1, $s2
/* 03D1D4 8003C5D4 8664000A */  lh    $a0, 0xa($s3)
/* 03D1D8 8003C5D8 86060000 */  lh    $a2, ($s0)
/* 03D1DC 8003C5DC 86470000 */  lh    $a3, ($s2)
/* 03D1E0 8003C5E0 0C019B71 */  jal   func_80066DC4
/* 03D1E4 8003C5E4 00002821 */   addu  $a1, $zero, $zero
/* 03D1E8 8003C5E8 8664000A */  lh    $a0, 0xa($s3)
/* 03D1EC 8003C5EC 86060000 */  lh    $a2, ($s0)
/* 03D1F0 8003C5F0 86470000 */  lh    $a3, ($s2)
/* 03D1F4 8003C5F4 0C019B71 */  jal   func_80066DC4
/* 03D1F8 8003C5F8 24050001 */   li    $a1, 1
/* 03D1FC 8003C5FC 3C02800D */  lui   $v0, 0x800d
/* 03D200 8003C600 00511021 */  addu  $v0, $v0, $s1
/* 03D204 8003C604 84426198 */  lh    $v0, 0x6198($v0)
/* 03D208 8003C608 86030000 */  lh    $v1, ($s0)
/* 03D20C 8003C60C 00431023 */  subu  $v0, $v0, $v1
/* 03D210 8003C610 44820000 */  mtc1  $v0, $f0
/* 03D214 8003C614 00000000 */  nop   
/* 03D218 8003C618 46800020 */  cvt.s.w $f0, $f0
/* 03D21C 8003C61C E7A00010 */  swc1  $f0, 0x10($sp)
/* 03D220 8003C620 AFA00014 */  sw    $zero, 0x14($sp)
/* 03D224 8003C624 3C02800D */  lui   $v0, 0x800d
/* 03D228 8003C628 00511021 */  addu  $v0, $v0, $s1
/* 03D22C 8003C62C 844261A0 */  lh    $v0, 0x61a0($v0)
/* 03D230 8003C630 86430000 */  lh    $v1, ($s2)
/* 03D234 8003C634 00431023 */  subu  $v0, $v0, $v1
/* 03D238 8003C638 44820000 */  mtc1  $v0, $f0
/* 03D23C 8003C63C 00000000 */  nop   
/* 03D240 8003C640 46800020 */  cvt.s.w $f0, $f0
/* 03D244 8003C644 E7A00018 */  swc1  $f0, 0x18($sp)
/* 03D248 8003C648 0C00F4AC */  jal   func_8003D2B0
/* 03D24C 8003C64C 27A40010 */   addiu $a0, $sp, 0x10
/* 03D250 8003C650 46000506 */  mov.s $f20, $f0
/* 03D254 8003C654 C7A00010 */  lwc1  $f0, 0x10($sp)
/* 03D258 8003C658 46000002 */  mul.s $f0, $f0, $f0
/* 03D25C 8003C65C C7AC0018 */  lwc1  $f12, 0x18($sp)
/* 03D260 8003C660 460C6302 */  mul.s $f12, $f12, $f12
/* 03D264 8003C664 0C02C5D4 */  jal   func_800B1750
/* 03D268 8003C668 460C0300 */   add.s $f12, $f0, $f12
/* 03D26C 8003C66C 3C014200 */  li    $at, 0x42000000 # 32.000000
/* 03D270 8003C670 44811000 */  mtc1  $at, $f2
/* 03D274 8003C674 8664000A */  lh    $a0, 0xa($s3)
/* 03D278 8003C678 3C063E80 */  lui   $a2, 0x3e80
/* 03D27C 8003C67C 46020083 */  div.s $f2, $f0, $f2
/* 03D280 8003C680 44071000 */  mfc1  $a3, $f2
/* 03D284 8003C684 00000000 */  nop   
/* 03D288 8003C688 0C019CD5 */  jal   func_80067354
/* 03D28C 8003C68C 00002821 */   addu  $a1, $zero, $zero
/* 03D290 8003C690 8664000A */  lh    $a0, 0xa($s3)
/* 03D294 8003C694 4406A000 */  mfc1  $a2, $f20
/* 03D298 8003C698 00000000 */  nop   
/* 03D29C 8003C69C 0C019CEC */  jal   func_800673B0
/* 03D2A0 8003C6A0 00002821 */   addu  $a1, $zero, $zero
/* 03D2A4 8003C6A4 8FBF0030 */  lw    $ra, 0x30($sp)
/* 03D2A8 8003C6A8 8FB3002C */  lw    $s3, 0x2c($sp)
/* 03D2AC 8003C6AC 8FB20028 */  lw    $s2, 0x28($sp)
/* 03D2B0 8003C6B0 8FB10024 */  lw    $s1, 0x24($sp)
/* 03D2B4 8003C6B4 8FB00020 */  lw    $s0, 0x20($sp)
/* 03D2B8 8003C6B8 D7B40038 */  ldc1  $f20, 0x38($sp)
/* 03D2BC 8003C6BC 03E00008 */  jr    $ra
/* 03D2C0 8003C6C0 27BD0040 */   addiu $sp, $sp, 0x40

glabel func_8003C6C4
/* 03D2C4 8003C6C4 27BDFFC8 */  addiu $sp, $sp, -0x38
/* 03D2C8 8003C6C8 AFBF0030 */  sw    $ra, 0x30($sp)
/* 03D2CC 8003C6CC AFB5002C */  sw    $s5, 0x2c($sp)
/* 03D2D0 8003C6D0 AFB40028 */  sw    $s4, 0x28($sp)
/* 03D2D4 8003C6D4 AFB30024 */  sw    $s3, 0x24($sp)
/* 03D2D8 8003C6D8 AFB20020 */  sw    $s2, 0x20($sp)
/* 03D2DC 8003C6DC AFB1001C */  sw    $s1, 0x1c($sp)
/* 03D2E0 8003C6E0 AFB00018 */  sw    $s0, 0x18($sp)
/* 03D2E4 8003C6E4 00009021 */  addu  $s2, $zero, $zero
/* 03D2E8 8003C6E8 241400FF */  li    $s4, 255
/* 03D2EC 8003C6EC 24130080 */  li    $s3, 128
/* 03D2F0 8003C6F0 3C15800D */  lui   $s5, %hi(D_800D61A8) # $s5, 0x800d
/* 03D2F4 8003C6F4 26B561A8 */  addiu $s5, %lo(D_800D61A8) # addiu $s5, $s5, 0x61a8
/* 03D2F8 8003C6F8 24040002 */  li    $a0, 2
.L8003C6FC:
/* 03D2FC 8003C6FC 0C014CFE */  jal   func_800533F8
/* 03D300 8003C700 00002821 */   addu  $a1, $zero, $zero
/* 03D304 8003C704 00408021 */  addu  $s0, $v0, $zero
/* 03D308 8003C708 3C04000A */  lui   $a0, (0x000A010B >> 16) # lui $a0, 0xa
/* 03D30C 8003C70C 0C00516C */  jal   ReadMainFS
/* 03D310 8003C710 3484010B */   ori   $a0, (0x000A010B & 0xFFFF) # ori $a0, $a0, 0x10b
/* 03D314 8003C714 00408821 */  addu  $s1, $v0, $zero
/* 03D318 8003C718 0C019E29 */  jal   func_800678A4
/* 03D31C 8003C71C 02202021 */   addu  $a0, $s1, $zero
/* 03D320 8003C720 8E03000C */  lw    $v1, 0xc($s0)
/* 03D324 8003C724 A4620000 */  sh    $v0, ($v1)
/* 03D328 8003C728 8E02000C */  lw    $v0, 0xc($s0)
/* 03D32C 8003C72C 8604000A */  lh    $a0, 0xa($s0)
/* 03D330 8003C730 00002821 */  addu  $a1, $zero, $zero
/* 03D334 8003C734 84460000 */  lh    $a2, ($v0)
/* 03D338 8003C738 0C019C82 */  jal   func_80067208
/* 03D33C 8003C73C 00003821 */   addu  $a3, $zero, $zero
/* 03D340 8003C740 8604000A */  lh    $a0, 0xa($s0)
/* 03D344 8003C744 00002821 */  addu  $a1, $zero, $zero
/* 03D348 8003C748 3C060100 */  lui   $a2, (0x01001808 >> 16) # lui $a2, 0x100
/* 03D34C 8003C74C 0C019D2F */  jal   func_800674BC
/* 03D350 8003C750 34C61808 */   ori   $a2, (0x01001808 & 0xFFFF) # ori $a2, $a2, 0x1808
/* 03D354 8003C754 8604000A */  lh    $a0, 0xa($s0)
/* 03D358 8003C758 00002821 */  addu  $a1, $zero, $zero
/* 03D35C 8003C75C 0C019CE1 */  jal   func_80067384
/* 03D360 8003C760 24060002 */   li    $a2, 2
/* 03D364 8003C764 8604000A */  lh    $a0, 0xa($s0)
/* 03D368 8003C768 AFB40010 */  sw    $s4, 0x10($sp)
/* 03D36C 8003C76C AFB30014 */  sw    $s3, 0x14($sp)
/* 03D370 8003C770 00002821 */  addu  $a1, $zero, $zero
/* 03D374 8003C774 00003021 */  addu  $a2, $zero, $zero
/* 03D378 8003C778 0C019D56 */  jal   func_80067558
/* 03D37C 8003C77C 00003821 */   addu  $a3, $zero, $zero
/* 03D380 8003C780 0C0051CC */  jal   FreeMainFS
/* 03D384 8003C784 02202021 */   addu  $a0, $s1, $zero
/* 03D388 8003C788 3C04000A */  lui   $a0, (0x000A0020 >> 16) # lui $a0, 0xa
/* 03D38C 8003C78C 0C00516C */  jal   ReadMainFS
/* 03D390 8003C790 34840020 */   ori   $a0, (0x000A0020 & 0xFFFF) # ori $a0, $a0, 0x20
/* 03D394 8003C794 00408821 */  addu  $s1, $v0, $zero
/* 03D398 8003C798 0C019E29 */  jal   func_800678A4
/* 03D39C 8003C79C 02202021 */   addu  $a0, $s1, $zero
/* 03D3A0 8003C7A0 8E03000C */  lw    $v1, 0xc($s0)
/* 03D3A4 8003C7A4 A4620002 */  sh    $v0, 2($v1)
/* 03D3A8 8003C7A8 8E02000C */  lw    $v0, 0xc($s0)
/* 03D3AC 8003C7AC 8604000A */  lh    $a0, 0xa($s0)
/* 03D3B0 8003C7B0 24050001 */  li    $a1, 1
/* 03D3B4 8003C7B4 84460002 */  lh    $a2, 2($v0)
/* 03D3B8 8003C7B8 0C019C82 */  jal   func_80067208
/* 03D3BC 8003C7BC 00003821 */   addu  $a3, $zero, $zero
/* 03D3C0 8003C7C0 8604000A */  lh    $a0, 0xa($s0)
/* 03D3C4 8003C7C4 24050001 */  li    $a1, 1
/* 03D3C8 8003C7C8 3C060100 */  lui   $a2, (0x01001808 >> 16) # lui $a2, 0x100
/* 03D3CC 8003C7CC 0C019D2F */  jal   func_800674BC
/* 03D3D0 8003C7D0 34C61808 */   ori   $a2, (0x01001808 & 0xFFFF) # ori $a2, $a2, 0x1808
/* 03D3D4 8003C7D4 8604000A */  lh    $a0, 0xa($s0)
/* 03D3D8 8003C7D8 24050001 */  li    $a1, 1
/* 03D3DC 8003C7DC 0C019CE1 */  jal   func_80067384
/* 03D3E0 8003C7E0 24060002 */   li    $a2, 2
/* 03D3E4 8003C7E4 8604000A */  lh    $a0, 0xa($s0)
/* 03D3E8 8003C7E8 AFB40010 */  sw    $s4, 0x10($sp)
/* 03D3EC 8003C7EC AFB30014 */  sw    $s3, 0x14($sp)
/* 03D3F0 8003C7F0 24050001 */  li    $a1, 1
/* 03D3F4 8003C7F4 00003021 */  addu  $a2, $zero, $zero
/* 03D3F8 8003C7F8 0C019D56 */  jal   func_80067558
/* 03D3FC 8003C7FC 00003821 */   addu  $a3, $zero, $zero
/* 03D400 8003C800 0C0051CC */  jal   FreeMainFS
/* 03D404 8003C804 02202021 */   addu  $a0, $s1, $zero
/* 03D408 8003C808 00122C00 */  sll   $a1, $s2, 0x10
/* 03D40C 8003C80C 02002021 */  addu  $a0, $s0, $zero
/* 03D410 8003C810 0C00F165 */  jal   func_8003C594
/* 03D414 8003C814 00052C03 */   sra   $a1, $a1, 0x10
/* 03D418 8003C818 00121080 */  sll   $v0, $s2, 2
/* 03D41C 8003C81C 00551021 */  addu  $v0, $v0, $s5
/* 03D420 8003C820 AC500000 */  sw    $s0, ($v0)
/* 03D424 8003C824 26520001 */  addiu $s2, $s2, 1
/* 03D428 8003C828 2A420004 */  slti  $v0, $s2, 4
/* 03D42C 8003C82C 1440FFB3 */  bnez  $v0, .L8003C6FC
/* 03D430 8003C830 24040002 */   li    $a0, 2
/* 03D434 8003C834 8FBF0030 */  lw    $ra, 0x30($sp)
/* 03D438 8003C838 8FB5002C */  lw    $s5, 0x2c($sp)
/* 03D43C 8003C83C 8FB40028 */  lw    $s4, 0x28($sp)
/* 03D440 8003C840 8FB30024 */  lw    $s3, 0x24($sp)
/* 03D444 8003C844 8FB20020 */  lw    $s2, 0x20($sp)
/* 03D448 8003C848 8FB1001C */  lw    $s1, 0x1c($sp)
/* 03D44C 8003C84C 8FB00018 */  lw    $s0, 0x18($sp)
/* 03D450 8003C850 03E00008 */  jr    $ra
/* 03D454 8003C854 27BD0038 */   addiu $sp, $sp, 0x38

glabel func_8003C858
/* 03D458 8003C858 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 03D45C 8003C85C AFBF0018 */  sw    $ra, 0x18($sp)
/* 03D460 8003C860 AFB10014 */  sw    $s1, 0x14($sp)
/* 03D464 8003C864 AFB00010 */  sw    $s0, 0x10($sp)
/* 03D468 8003C868 00008021 */  addu  $s0, $zero, $zero
/* 03D46C 8003C86C 3C11800D */  lui   $s1, %hi(D_800D61A8) # $s1, 0x800d
/* 03D470 8003C870 263161A8 */  addiu $s1, %lo(D_800D61A8) # addiu $s1, $s1, 0x61a8
/* 03D474 8003C874 00101080 */  sll   $v0, $s0, 2
.L8003C878:
/* 03D478 8003C878 00511021 */  addu  $v0, $v0, $s1
/* 03D47C 8003C87C 8C440000 */  lw    $a0, ($v0)
/* 03D480 8003C880 0C014D15 */  jal   func_80053454
/* 03D484 8003C884 26100001 */   addiu $s0, $s0, 1
/* 03D488 8003C888 2A020004 */  slti  $v0, $s0, 4
/* 03D48C 8003C88C 1440FFFA */  bnez  $v0, .L8003C878
/* 03D490 8003C890 00101080 */   sll   $v0, $s0, 2
/* 03D494 8003C894 8FBF0018 */  lw    $ra, 0x18($sp)
/* 03D498 8003C898 8FB10014 */  lw    $s1, 0x14($sp)
/* 03D49C 8003C89C 8FB00010 */  lw    $s0, 0x10($sp)
/* 03D4A0 8003C8A0 03E00008 */  jr    $ra
/* 03D4A4 8003C8A4 27BD0020 */   addiu $sp, $sp, 0x20

D_8003C8A8:
/* 03D4A8 8003C8A8 27BDFFB8 */  addiu $sp, $sp, -0x48
/* 03D4AC 8003C8AC AFBF0038 */  sw    $ra, 0x38($sp)
/* 03D4B0 8003C8B0 AFB50034 */  sw    $s5, 0x34($sp)
/* 03D4B4 8003C8B4 AFB40030 */  sw    $s4, 0x30($sp)
/* 03D4B8 8003C8B8 AFB3002C */  sw    $s3, 0x2c($sp)
/* 03D4BC 8003C8BC AFB20028 */  sw    $s2, 0x28($sp)
/* 03D4C0 8003C8C0 AFB10024 */  sw    $s1, 0x24($sp)
/* 03D4C4 8003C8C4 AFB00020 */  sw    $s0, 0x20($sp)
/* 03D4C8 8003C8C8 F7B40040 */  sdc1  $f20, 0x40($sp)
/* 03D4CC 8003C8CC 2412FFFF */  li    $s2, -1
/* 03D4D0 8003C8D0 3C0142B4 */  li    $at, 0x42B40000 # 90.000000
/* 03D4D4 8003C8D4 4481A000 */  mtc1  $at, $f20
/* 03D4D8 8003C8D8 3C15800D */  lui   $s5, %hi(D_800D61A8) # $s5, 0x800d
/* 03D4DC 8003C8DC 26B561A8 */  addiu $s5, %lo(D_800D61A8) # addiu $s5, $s5, 0x61a8
/* 03D4E0 8003C8E0 241400FF */  li    $s4, 255
glabel func_8003C8E4
/* 03D4E4 8003C8E4 0C018D6D */  jal   SleepVProcess
/* 03D4E8 8003C8E8 00000000 */   nop   
/* 03D4EC 8003C8EC 00121400 */  sll   $v0, $s2, 0x10
/* 03D4F0 8003C8F0 00021403 */  sra   $v0, $v0, 0x10
/* 03D4F4 8003C8F4 3C03800D */  lui   $v1, %hi(D_800D61B8) # $v1, 0x800d
/* 03D4F8 8003C8F8 846361B8 */  lh    $v1, %lo(D_800D61B8)($v1)
/* 03D4FC 8003C8FC 10430034 */  beq   $v0, $v1, .L8003C9D0
/* 03D500 8003C900 00602021 */   addu  $a0, $v1, $zero
/* 03D504 8003C904 00809021 */  addu  $s2, $a0, $zero
/* 03D508 8003C908 00008021 */  addu  $s0, $zero, $zero
/* 03D50C 8003C90C 00121400 */  sll   $v0, $s2, 0x10
/* 03D510 8003C910 00029C03 */  sra   $s3, $v0, 0x10
/* 03D514 8003C914 00101080 */  sll   $v0, $s0, 2
.L8003C918:
/* 03D518 8003C918 00551021 */  addu  $v0, $v0, $s5
/* 03D51C 8003C91C 8C510000 */  lw    $s1, ($v0)
/* 03D520 8003C920 16130009 */  bne   $s0, $s3, .L8003C948
/* 03D524 8003C924 240200A0 */   li    $v0, 160
/* 03D528 8003C928 8624000A */  lh    $a0, 0xa($s1)
/* 03D52C 8003C92C 00002821 */  addu  $a1, $zero, $zero
/* 03D530 8003C930 0C019CE1 */  jal   func_80067384
/* 03D534 8003C934 24060002 */   li    $a2, 2
/* 03D538 8003C938 8624000A */  lh    $a0, 0xa($s1)
/* 03D53C 8003C93C 24050001 */  li    $a1, 1
/* 03D540 8003C940 0800F267 */  j     func_8003C99C
/* 03D544 8003C944 24060002 */   li    $a2, 2

.L8003C948:
/* 03D548 8003C948 8624000A */  lh    $a0, 0xa($s1)
/* 03D54C 8003C94C AFB40010 */  sw    $s4, 0x10($sp)
/* 03D550 8003C950 AFA20014 */  sw    $v0, 0x14($sp)
/* 03D554 8003C954 00002821 */  addu  $a1, $zero, $zero
/* 03D558 8003C958 00003021 */  addu  $a2, $zero, $zero
/* 03D55C 8003C95C 0C019D56 */  jal   func_80067558
/* 03D560 8003C960 00003821 */   addu  $a3, $zero, $zero
/* 03D564 8003C964 8624000A */  lh    $a0, 0xa($s1)
/* 03D568 8003C968 AFB40010 */  sw    $s4, 0x10($sp)
/* 03D56C 8003C96C AFB40014 */  sw    $s4, 0x14($sp)
/* 03D570 8003C970 24050001 */  li    $a1, 1
/* 03D574 8003C974 00003021 */  addu  $a2, $zero, $zero
/* 03D578 8003C978 0C019D56 */  jal   func_80067558
/* 03D57C 8003C97C 00003821 */   addu  $a3, $zero, $zero
/* 03D580 8003C980 8624000A */  lh    $a0, 0xa($s1)
/* 03D584 8003C984 00002821 */  addu  $a1, $zero, $zero
/* 03D588 8003C988 0C019CE1 */  jal   func_80067384
/* 03D58C 8003C98C 24060003 */   li    $a2, 3
/* 03D590 8003C990 8624000A */  lh    $a0, 0xa($s1)
/* 03D594 8003C994 24050001 */  li    $a1, 1
/* 03D598 8003C998 24060003 */  li    $a2, 3
glabel func_8003C99C
/* 03D59C 8003C99C 0C019CE1 */  jal   func_80067384
/* 03D5A0 8003C9A0 26100001 */   addiu $s0, $s0, 1
/* 03D5A4 8003C9A4 8624000A */  lh    $a0, 0xa($s1)
/* 03D5A8 8003C9A8 00002821 */  addu  $a1, $zero, $zero
/* 03D5AC 8003C9AC 0C019D20 */  jal   func_80067480
/* 03D5B0 8003C9B0 34068000 */   li    $a2, 32768
/* 03D5B4 8003C9B4 8624000A */  lh    $a0, 0xa($s1)
/* 03D5B8 8003C9B8 24050001 */  li    $a1, 1
/* 03D5BC 8003C9BC 0C019D20 */  jal   func_80067480
/* 03D5C0 8003C9C0 34068000 */   li    $a2, 32768
/* 03D5C4 8003C9C4 2A020004 */  slti  $v0, $s0, 4
/* 03D5C8 8003C9C8 1440FFD3 */  bnez  $v0, .L8003C918
/* 03D5CC 8003C9CC 00101080 */   sll   $v0, $s0, 2
.L8003C9D0:
/* 03D5D0 8003C9D0 00121400 */  sll   $v0, $s2, 0x10
/* 03D5D4 8003C9D4 00021383 */  sra   $v0, $v0, 0xe
/* 03D5D8 8003C9D8 00551021 */  addu  $v0, $v0, $s5
/* 03D5DC 8003C9DC 8C510000 */  lw    $s1, ($v0)
/* 03D5E0 8003C9E0 0C02BAB0 */  jal   func_800AEAC0
/* 03D5E4 8003C9E4 4600A306 */   mov.s $f12, $f20
/* 03D5E8 8003C9E8 3C01437F */  li    $at, 0x437F0000 # 255.000000
/* 03D5EC 8003C9EC 44811000 */  mtc1  $at, $f2
/* 03D5F0 8003C9F0 00000000 */  nop   
/* 03D5F4 8003C9F4 46020002 */  mul.s $f0, $f0, $f2
/* 03D5F8 8003C9F8 4600008D */  trunc.w.s $f2, $f0
/* 03D5FC 8003C9FC 44021000 */  mfc1  $v0, $f2
/* 03D600 8003CA00 00000000 */  nop   
/* 03D604 8003CA04 00021400 */  sll   $v0, $v0, 0x10
/* 03D608 8003CA08 00021403 */  sra   $v0, $v0, 0x10
/* 03D60C 8003CA0C 04420001 */  bltzl $v0, .L8003CA14
/* 03D610 8003CA10 00021023 */   negu  $v0, $v0
.L8003CA14:
/* 03D614 8003CA14 3C0140C0 */  li    $at, 0x40C00000 # 6.000000
/* 03D618 8003CA18 44810000 */  mtc1  $at, $f0
/* 03D61C 8003CA1C 00000000 */  nop   
/* 03D620 8003CA20 4600A500 */  add.s $f20, $f20, $f0
/* 03D624 8003CA24 3C0143B4 */  li    $at, 0x43B40000 # 360.000000
/* 03D628 8003CA28 44810000 */  mtc1  $at, $f0
/* 03D62C 8003CA2C 00000000 */  nop   
/* 03D630 8003CA30 4614003C */  c.lt.s $f0, $f20
/* 03D634 8003CA34 00000000 */  nop   
/* 03D638 8003CA38 00000000 */  nop   
/* 03D63C 8003CA3C 45030001 */  bc1tl .L8003CA44
/* 03D640 8003CA40 4600A501 */   sub.s $f20, $f20, $f0
.L8003CA44:
/* 03D644 8003CA44 8624000A */  lh    $a0, 0xa($s1)
/* 03D648 8003CA48 305000FF */  andi  $s0, $v0, 0xff
/* 03D64C 8003CA4C AFA00010 */  sw    $zero, 0x10($sp)
/* 03D650 8003CA50 240200A0 */  li    $v0, 160
/* 03D654 8003CA54 AFA20014 */  sw    $v0, 0x14($sp)
/* 03D658 8003CA58 00002821 */  addu  $a1, $zero, $zero
/* 03D65C 8003CA5C 240600FF */  li    $a2, 255
/* 03D660 8003CA60 0C019D56 */  jal   func_80067558
/* 03D664 8003CA64 02003821 */   addu  $a3, $s0, $zero
/* 03D668 8003CA68 8624000A */  lh    $a0, 0xa($s1)
/* 03D66C 8003CA6C AFA00010 */  sw    $zero, 0x10($sp)
/* 03D670 8003CA70 AFB40014 */  sw    $s4, 0x14($sp)
/* 03D674 8003CA74 24050001 */  li    $a1, 1
/* 03D678 8003CA78 240600FF */  li    $a2, 255
/* 03D67C 8003CA7C 0C019D56 */  jal   func_80067558
/* 03D680 8003CA80 02003821 */   addu  $a3, $s0, $zero
/* 03D684 8003CA84 0800F239 */  j     func_8003C8E4
/* 03D688 8003CA88 00000000 */   nop   

/* 03D68C 8003CA8C 8FBF0038 */  lw    $ra, 0x38($sp)
/* 03D690 8003CA90 8FB50034 */  lw    $s5, 0x34($sp)
/* 03D694 8003CA94 8FB40030 */  lw    $s4, 0x30($sp)
/* 03D698 8003CA98 8FB3002C */  lw    $s3, 0x2c($sp)
/* 03D69C 8003CA9C 8FB20028 */  lw    $s2, 0x28($sp)
/* 03D6A0 8003CAA0 8FB10024 */  lw    $s1, 0x24($sp)
/* 03D6A4 8003CAA4 8FB00020 */  lw    $s0, 0x20($sp)
/* 03D6A8 8003CAA8 D7B40040 */  ldc1  $f20, 0x40($sp)
/* 03D6AC 8003CAAC 03E00008 */  jr    $ra
/* 03D6B0 8003CAB0 27BD0048 */   addiu $sp, $sp, 0x48

D_8003CAB4:
/* 03D6B4 8003CAB4 27BDFF98 */  addiu $sp, $sp, -0x68
/* 03D6B8 8003CAB8 AFBF0064 */  sw    $ra, 0x64($sp)
/* 03D6BC 8003CABC AFBE0060 */  sw    $fp, 0x60($sp)
/* 03D6C0 8003CAC0 AFB7005C */  sw    $s7, 0x5c($sp)
/* 03D6C4 8003CAC4 AFB60058 */  sw    $s6, 0x58($sp)
/* 03D6C8 8003CAC8 AFB50054 */  sw    $s5, 0x54($sp)
/* 03D6CC 8003CACC AFB40050 */  sw    $s4, 0x50($sp)
/* 03D6D0 8003CAD0 AFB3004C */  sw    $s3, 0x4c($sp)
/* 03D6D4 8003CAD4 AFB20048 */  sw    $s2, 0x48($sp)
/* 03D6D8 8003CAD8 AFB10044 */  sw    $s1, 0x44($sp)
/* 03D6DC 8003CADC 0C018CEA */  jal   GetCurrentProcess
/* 03D6E0 8003CAE0 AFB00040 */   sw    $s0, 0x40($sp)
/* 03D6E4 8003CAE4 8C42008C */  lw    $v0, 0x8c($v0)
/* 03D6E8 8003CAE8 AFA20024 */  sw    $v0, 0x24($sp)
/* 03D6EC 8003CAEC 3C08800F */  lui   $t0, %hi(D_800F6598) # $t0, 0x800f
/* 03D6F0 8003CAF0 8D086598 */  lw    $t0, %lo(D_800F6598)($t0)
/* 03D6F4 8003CAF4 AFA8002C */  sw    $t0, 0x2c($sp)
/* 03D6F8 8003CAF8 A7A00036 */  sh    $zero, 0x36($sp)
/* 03D6FC 8003CAFC 0000A021 */  addu  $s4, $zero, $zero
/* 03D700 8003CB00 00142400 */  sll   $a0, $s4, 0x10
.L8003CB04:
/* 03D704 8003CB04 0C014AC8 */  jal   PlayerIsCPU
/* 03D708 8003CB08 00042403 */   sra   $a0, $a0, 0x10
/* 03D70C 8003CB0C 5440000C */  bnezl $v0, .L8003CB40
/* 03D710 8003CB10 26940001 */   addiu $s4, $s4, 1
/* 03D714 8003CB14 00141040 */  sll   $v0, $s4, 1
/* 03D718 8003CB18 00541021 */  addu  $v0, $v0, $s4
/* 03D71C 8003CB1C 00021100 */  sll   $v0, $v0, 4
/* 03D720 8003CB20 3C01800F */  lui   $at, 0x800f
/* 03D724 8003CB24 00220821 */  addu  $at, $at, $v0
/* 03D728 8003CB28 902232B3 */  lbu   $v0, 0x32b3($at)
/* 03D72C 8003CB2C 8FA80024 */  lw    $t0, 0x24($sp)
/* 03D730 8003CB30 54480003 */  bnel  $v0, $t0, .L8003CB40
/* 03D734 8003CB34 26940001 */   addiu $s4, $s4, 1
/* 03D738 8003CB38 0800F2D3 */  j     func_8003CB4C
/* 03D73C 8003CB3C A7B40036 */   sh    $s4, 0x36($sp)

.L8003CB40:
/* 03D740 8003CB40 2A820004 */  slti  $v0, $s4, 4
/* 03D744 8003CB44 5440FFEF */  bnezl $v0, .L8003CB04
/* 03D748 8003CB48 00142400 */   sll   $a0, $s4, 0x10
glabel func_8003CB4C
/* 03D74C 8003CB4C 97A80036 */  lhu   $t0, 0x36($sp)
/* 03D750 8003CB50 3C01800D */  lui   $at, %hi(D_800D61B8) # $at, 0x800d
/* 03D754 8003CB54 A42861B8 */  sh    $t0, %lo(D_800D61B8)($at)
/* 03D758 8003CB58 0C012DB6 */  jal   func_8004B6D8
/* 03D75C 8003CB5C 27A40010 */   addiu $a0, $sp, 0x10
/* 03D760 8003CB60 24040006 */  li    $a0, 6
/* 03D764 8003CB64 0C01C9AB */  jal   func_800726AC
/* 03D768 8003CB68 24050008 */   li    $a1, 8
/* 03D76C 8003CB6C 0C018D54 */  jal   SleepProcess
/* 03D770 8003CB70 24040008 */   li    $a0, 8
/* 03D774 8003CB74 0C01566F */  jal   func_800559BC
/* 03D778 8003CB78 0000A021 */   addu  $s4, $zero, $zero
/* 03D77C 8003CB7C 8FA40024 */  lw    $a0, 0x24($sp)
/* 03D780 8003CB80 0C0101B9 */  jal   func_800406E4
/* 03D784 8003CB84 00000000 */   nop   
/* 03D788 8003CB88 0C018D6D */  jal   SleepVProcess
/* 03D78C 8003CB8C 00000000 */   nop   
/* 03D790 8003CB90 24020001 */  li    $v0, 1
/* 03D794 8003CB94 3C01800F */  lui   $at, %hi(D_800F384E) # $at, 0x800f
/* 03D798 8003CB98 A022384E */  sb    $v0, %lo(D_800F384E)($at)
/* 03D79C 8003CB9C 3C02800F */  lui   $v0, %hi(D_800F5278) # $v0, 0x800f
/* 03D7A0 8003CBA0 94425278 */  lhu   $v0, %lo(D_800F5278)($v0)
/* 03D7A4 8003CBA4 3042FFFE */  andi  $v0, $v0, 0xfffe
/* 03D7A8 8003CBA8 3C01800F */  lui   $at, %hi(D_800F5278) # $at, 0x800f
/* 03D7AC 8003CBAC A4225278 */  sh    $v0, %lo(D_800F5278)($at)
/* 03D7B0 8003CBB0 3C10800F */  lui   $s0, %hi(D_800ED5DC) # $s0, 0x800f
/* 03D7B4 8003CBB4 2610D5DC */  addiu $s0, %lo(D_800ED5DC) # addiu $s0, $s0, -0x2a24
/* 03D7B8 8003CBB8 0C010177 */  jal   func_800405DC
/* 03D7BC 8003CBBC 86040000 */   lh    $a0, ($s0)
/* 03D7C0 8003CBC0 0C0101B9 */  jal   func_800406E4
/* 03D7C4 8003CBC4 86040000 */   lh    $a0, ($s0)
/* 03D7C8 8003CBC8 0C012E75 */  jal   func_8004B9D4
/* 03D7CC 8003CBCC 24040001 */   li    $a0, 1
/* 03D7D0 8003CBD0 0C012850 */  jal   func_8004A140
/* 03D7D4 8003CBD4 00000000 */   nop   
/* 03D7D8 8003CBD8 3C04800D */  lui   $a0, %hi(D_800D6050) # $a0, 0x800d
/* 03D7DC 8003CBDC 0C0127D3 */  jal   func_80049F4C
/* 03D7E0 8003CBE0 8C846050 */   lw    $a0, %lo(D_800D6050)($a0)
/* 03D7E4 8003CBE4 0C012DFE */  jal   func_8004B7F8
/* 03D7E8 8003CBE8 24040096 */   li    $a0, 150
/* 03D7EC 8003CBEC 24040014 */  li    $a0, 20
/* 03D7F0 8003CBF0 0C014CFE */  jal   func_800533F8
/* 03D7F4 8003CBF4 00002821 */   addu  $a1, $zero, $zero
/* 03D7F8 8003CBF8 0040F021 */  addu  $fp, $v0, $zero
/* 03D7FC 8003CBFC 3C11800D */  lui   $s1, %hi(D_800D6198) # $s1, 0x800d
/* 03D800 8003CC00 26316198 */  addiu $s1, %lo(D_800D6198) # addiu $s1, $s1, 0x6198
/* 03D804 8003CC04 3C10800D */  lui   $s0, %hi(D_800D61A0) # $s0, 0x800d
/* 03D808 8003CC08 261061A0 */  addiu $s0, %lo(D_800D61A0) # addiu $s0, $s0, 0x61a0
.L8003CC0C:
/* 03D80C 8003CC0C 0C014AA3 */  jal   GetPlayerStruct
/* 03D810 8003CC10 02802021 */   addu  $a0, $s4, $zero
/* 03D814 8003CC14 0040A821 */  addu  $s5, $v0, $zero
/* 03D818 8003CC18 96A4000E */  lhu   $a0, 0xe($s5)
/* 03D81C 8003CC1C 0C013081 */  jal   GetAbsSpaceIndexFromChainSpaceIndex
/* 03D820 8003CC20 96A50010 */   lhu   $a1, 0x10($s5)
/* 03D824 8003CC24 00021400 */  sll   $v0, $v0, 0x10
/* 03D828 8003CC28 0C01307B */  jal   GetSpaceData
/* 03D82C 8003CC2C 00022403 */   sra   $a0, $v0, 0x10
/* 03D830 8003CC30 24440004 */  addiu $a0, $v0, 4
/* 03D834 8003CC34 0C012DCC */  jal   func_8004B730
/* 03D838 8003CC38 27A50018 */   addiu $a1, $sp, 0x18
/* 03D83C 8003CC3C 00141840 */  sll   $v1, $s4, 1
/* 03D840 8003CC40 00712021 */  addu  $a0, $v1, $s1
/* 03D844 8003CC44 C7A00018 */  lwc1  $f0, 0x18($sp)
/* 03D848 8003CC48 4600008D */  trunc.w.s $f2, $f0
/* 03D84C 8003CC4C 44021000 */  mfc1  $v0, $f2
/* 03D850 8003CC50 00000000 */  nop   
/* 03D854 8003CC54 A4820000 */  sh    $v0, ($a0)
/* 03D858 8003CC58 00701821 */  addu  $v1, $v1, $s0
/* 03D85C 8003CC5C C7A0001C */  lwc1  $f0, 0x1c($sp)
/* 03D860 8003CC60 4600008D */  trunc.w.s $f2, $f0
/* 03D864 8003CC64 44021000 */  mfc1  $v0, $f2
/* 03D868 8003CC68 00000000 */  nop   
/* 03D86C 8003CC6C A4620000 */  sh    $v0, ($v1)
/* 03D870 8003CC70 26940001 */  addiu $s4, $s4, 1
/* 03D874 8003CC74 2A820004 */  slti  $v0, $s4, 4
/* 03D878 8003CC78 1440FFE4 */  bnez  $v0, .L8003CC0C
/* 03D87C 8003CC7C 00009821 */   addu  $s3, $zero, $zero
/* 03D880 8003CC80 0000A021 */  addu  $s4, $zero, $zero
.L8003CC84:
/* 03D884 8003CC84 00131900 */  sll   $v1, $s3, 4
/* 03D888 8003CC88 3C02800D */  lui   $v0, %hi(D_800D6058) # $v0, 0x800d
/* 03D88C 8003CC8C 24426058 */  addiu $v0, %lo(D_800D6058) # addiu $v0, $v0, 0x6058
/* 03D890 8003CC90 00629021 */  addu  $s2, $v1, $v0
/* 03D894 8003CC94 82420000 */  lb    $v0, ($s2)
/* 03D898 8003CC98 04400068 */  bltz  $v0, .L8003CE3C
/* 03D89C 8003CC9C 00021080 */   sll   $v0, $v0, 2
/* 03D8A0 8003CCA0 3C04800C */  lui   $a0, 0x800c
/* 03D8A4 8003CCA4 00822021 */  addu  $a0, $a0, $v0
/* 03D8A8 8003CCA8 8C8442C0 */  lw    $a0, 0x42c0($a0)
/* 03D8AC 8003CCAC 0C00516C */  jal   ReadMainFS
/* 03D8B0 8003CCB0 00148400 */   sll   $s0, $s4, 0x10
/* 03D8B4 8003CCB4 0040B821 */  addu  $s7, $v0, $zero
/* 03D8B8 8003CCB8 0C019E29 */  jal   func_800678A4
/* 03D8BC 8003CCBC 02E02021 */   addu  $a0, $s7, $zero
/* 03D8C0 8003CCC0 8FC3000C */  lw    $v1, 0xc($fp)
/* 03D8C4 8003CCC4 00143040 */  sll   $a2, $s4, 1
/* 03D8C8 8003CCC8 00C31821 */  addu  $v1, $a2, $v1
/* 03D8CC 8003CCCC A4620000 */  sh    $v0, ($v1)
/* 03D8D0 8003CCD0 00108403 */  sra   $s0, $s0, 0x10
/* 03D8D4 8003CCD4 8FC2000C */  lw    $v0, 0xc($fp)
/* 03D8D8 8003CCD8 00C23021 */  addu  $a2, $a2, $v0
/* 03D8DC 8003CCDC 87C4000A */  lh    $a0, 0xa($fp)
/* 03D8E0 8003CCE0 02002821 */  addu  $a1, $s0, $zero
/* 03D8E4 8003CCE4 84C60000 */  lh    $a2, ($a2)
/* 03D8E8 8003CCE8 0C019C82 */  jal   func_80067208
/* 03D8EC 8003CCEC 00003821 */   addu  $a3, $zero, $zero
/* 03D8F0 8003CCF0 87C4000A */  lh    $a0, 0xa($fp)
/* 03D8F4 8003CCF4 02002821 */  addu  $a1, $s0, $zero
/* 03D8F8 8003CCF8 3C060100 */  lui   $a2, (0x01001000 >> 16) # lui $a2, 0x100
/* 03D8FC 8003CCFC 0C019D2F */  jal   func_800674BC
/* 03D900 8003CD00 34C61000 */   ori   $a2, (0x01001000 & 0xFFFF) # ori $a2, $a2, 0x1000
/* 03D904 8003CD04 8E440004 */  lw    $a0, 4($s2)
/* 03D908 8003CD08 2484000C */  addiu $a0, $a0, 0xc
/* 03D90C 8003CD0C 0C012DCC */  jal   func_8004B730
/* 03D910 8003CD10 27A50018 */   addiu $a1, $sp, 0x18
/* 03D914 8003CD14 C7A00018 */  lwc1  $f0, 0x18($sp)
/* 03D918 8003CD18 4600008D */  trunc.w.s $f2, $f0
/* 03D91C 8003CD1C 44031000 */  mfc1  $v1, $f2
/* 03D920 8003CD20 9642000C */  lhu   $v0, 0xc($s2)
/* 03D924 8003CD24 00621821 */  addu  $v1, $v1, $v0
/* 03D928 8003CD28 C7A0001C */  lwc1  $f0, 0x1c($sp)
/* 03D92C 8003CD2C 4600008D */  trunc.w.s $f2, $f0
/* 03D930 8003CD30 44041000 */  mfc1  $a0, $f2
/* 03D934 8003CD34 9642000E */  lhu   $v0, 0xe($s2)
/* 03D938 8003CD38 00828821 */  addu  $s1, $a0, $v0
/* 03D93C 8003CD3C 00031C00 */  sll   $v1, $v1, 0x10
/* 03D940 8003CD40 0003AC03 */  sra   $s5, $v1, 0x10
/* 03D944 8003CD44 00113C00 */  sll   $a3, $s1, 0x10
/* 03D948 8003CD48 87C4000A */  lh    $a0, 0xa($fp)
/* 03D94C 8003CD4C 02002821 */  addu  $a1, $s0, $zero
/* 03D950 8003CD50 02A03021 */  addu  $a2, $s5, $zero
/* 03D954 8003CD54 0C019B71 */  jal   func_80066DC4
/* 03D958 8003CD58 00073C03 */   sra   $a3, $a3, 0x10
/* 03D95C 8003CD5C 00113027 */  nor   $a2, $zero, $s1
/* 03D960 8003CD60 87C4000A */  lh    $a0, 0xa($fp)
/* 03D964 8003CD64 02002821 */  addu  $a1, $s0, $zero
/* 03D968 8003CD68 0C019CE1 */  jal   func_80067384
/* 03D96C 8003CD6C 30C6FFFF */   andi  $a2, $a2, 0xffff
/* 03D970 8003CD70 0C0051CC */  jal   FreeMainFS
/* 03D974 8003CD74 02E02021 */   addu  $a0, $s7, $zero
/* 03D978 8003CD78 82420000 */  lb    $v0, ($s2)
/* 03D97C 8003CD7C 38430006 */  xori  $v1, $v0, 6
/* 03D980 8003CD80 2C630001 */  sltiu $v1, $v1, 1
/* 03D984 8003CD84 3842000A */  xori  $v0, $v0, 0xa
/* 03D988 8003CD88 2C420001 */  sltiu $v0, $v0, 1
/* 03D98C 8003CD8C 00621825 */  or    $v1, $v1, $v0
/* 03D990 8003CD90 1060002A */  beqz  $v1, .L8003CE3C
/* 03D994 8003CD94 3C04000A */   lui   $a0, (0x000A0124 >> 16) # lui $a0, 0xa
/* 03D998 8003CD98 26940001 */  addiu $s4, $s4, 1
/* 03D99C 8003CD9C 0C00516C */  jal   ReadMainFS
/* 03D9A0 8003CDA0 34840124 */   ori   $a0, (0x000A0124 & 0xFFFF) # ori $a0, $a0, 0x124
/* 03D9A4 8003CDA4 0040B821 */  addu  $s7, $v0, $zero
/* 03D9A8 8003CDA8 0C019E29 */  jal   func_800678A4
/* 03D9AC 8003CDAC 02E02021 */   addu  $a0, $s7, $zero
/* 03D9B0 8003CDB0 8FC3000C */  lw    $v1, 0xc($fp)
/* 03D9B4 8003CDB4 00143040 */  sll   $a2, $s4, 1
/* 03D9B8 8003CDB8 00C31821 */  addu  $v1, $a2, $v1
/* 03D9BC 8003CDBC A4620000 */  sh    $v0, ($v1)
/* 03D9C0 8003CDC0 00148400 */  sll   $s0, $s4, 0x10
/* 03D9C4 8003CDC4 00108403 */  sra   $s0, $s0, 0x10
/* 03D9C8 8003CDC8 8FC2000C */  lw    $v0, 0xc($fp)
/* 03D9CC 8003CDCC 00C23021 */  addu  $a2, $a2, $v0
/* 03D9D0 8003CDD0 87C4000A */  lh    $a0, 0xa($fp)
/* 03D9D4 8003CDD4 02002821 */  addu  $a1, $s0, $zero
/* 03D9D8 8003CDD8 84C60000 */  lh    $a2, ($a2)
/* 03D9DC 8003CDDC 0C019C82 */  jal   func_80067208
/* 03D9E0 8003CDE0 00003821 */   addu  $a3, $zero, $zero
/* 03D9E4 8003CDE4 87C4000A */  lh    $a0, 0xa($fp)
/* 03D9E8 8003CDE8 02002821 */  addu  $a1, $s0, $zero
/* 03D9EC 8003CDEC 3C060100 */  lui   $a2, (0x01001808 >> 16) # lui $a2, 0x100
/* 03D9F0 8003CDF0 0C019D2F */  jal   func_800674BC
/* 03D9F4 8003CDF4 34C61808 */   ori   $a2, (0x01001808 & 0xFFFF) # ori $a2, $a2, 0x1808
/* 03D9F8 8003CDF8 2627FFFF */  addiu $a3, $s1, -1
/* 03D9FC 8003CDFC 00073C00 */  sll   $a3, $a3, 0x10
/* 03DA00 8003CE00 87C4000A */  lh    $a0, 0xa($fp)
/* 03DA04 8003CE04 02002821 */  addu  $a1, $s0, $zero
/* 03DA08 8003CE08 02A03021 */  addu  $a2, $s5, $zero
/* 03DA0C 8003CE0C 0C019B71 */  jal   func_80066DC4
/* 03DA10 8003CE10 00073C03 */   sra   $a3, $a3, 0x10
/* 03DA14 8003CE14 87C4000A */  lh    $a0, 0xa($fp)
/* 03DA18 8003CE18 02002821 */  addu  $a1, $s0, $zero
/* 03DA1C 8003CE1C 0C019CE1 */  jal   func_80067384
/* 03DA20 8003CE20 3406FFFF */   li    $a2, 65535
/* 03DA24 8003CE24 0C0051CC */  jal   FreeMainFS
/* 03DA28 8003CE28 02E02021 */   addu  $a0, $s7, $zero
/* 03DA2C 8003CE2C 87C4000A */  lh    $a0, 0xa($fp)
/* 03DA30 8003CE30 0C00F14A */  jal   func_8003C528
/* 03DA34 8003CE34 02002821 */   addu  $a1, $s0, $zero
/* 03DA38 8003CE38 AE420008 */  sw    $v0, 8($s2)
.L8003CE3C:
/* 03DA3C 8003CE3C 26730001 */  addiu $s3, $s3, 1
/* 03DA40 8003CE40 2A620014 */  slti  $v0, $s3, 0x14
/* 03DA44 8003CE44 1440FF8F */  bnez  $v0, .L8003CC84
/* 03DA48 8003CE48 26940001 */   addiu $s4, $s4, 1
/* 03DA4C 8003CE4C 0C00F1B1 */  jal   func_8003C6C4
/* 03DA50 8003CE50 0000A021 */   addu  $s4, $zero, $zero
/* 03DA54 8003CE54 3C048004 */  lui   $a0, %hi(D_8003C8A8) # $a0, 0x8004
/* 03DA58 8003CE58 2484C8A8 */  addiu $a0, %lo(D_8003C8A8) # addiu $a0, $a0, -0x3758
/* 03DA5C 8003CE5C 24051005 */  li    $a1, 4101
/* 03DA60 8003CE60 00003021 */  addu  $a2, $zero, $zero
/* 03DA64 8003CE64 0C01770A */  jal   InitProcess
/* 03DA68 8003CE68 00003821 */   addu  $a3, $zero, $zero
/* 03DA6C 8003CE6C AFA2003C */  sw    $v0, 0x3c($sp)
/* 03DA70 8003CE70 24040008 */  li    $a0, 8
/* 03DA74 8003CE74 0C014CFE */  jal   func_800533F8
/* 03DA78 8003CE78 00002821 */   addu  $a1, $zero, $zero
/* 03DA7C 8003CE7C 0040B021 */  addu  $s6, $v0, $zero
.L8003CE80:
/* 03DA80 8003CE80 0C014AA3 */  jal   GetPlayerStruct
/* 03DA84 8003CE84 02802021 */   addu  $a0, $s4, $zero
/* 03DA88 8003CE88 0040A821 */  addu  $s5, $v0, $zero
/* 03DA8C 8003CE8C 92A20004 */  lbu   $v0, 4($s5)
/* 03DA90 8003CE90 00021080 */  sll   $v0, $v0, 2
/* 03DA94 8003CE94 3C04800C */  lui   $a0, 0x800c
/* 03DA98 8003CE98 00822021 */  addu  $a0, $a0, $v0
/* 03DA9C 8003CE9C 8C84431C */  lw    $a0, 0x431c($a0)
/* 03DAA0 8003CEA0 0C00516C */  jal   ReadMainFS
/* 03DAA4 8003CEA4 00148840 */   sll   $s1, $s4, 1
/* 03DAA8 8003CEA8 0040B821 */  addu  $s7, $v0, $zero
/* 03DAAC 8003CEAC 0C019E29 */  jal   func_800678A4
/* 03DAB0 8003CEB0 02E02021 */   addu  $a0, $s7, $zero
/* 03DAB4 8003CEB4 8EC3000C */  lw    $v1, 0xc($s6)
/* 03DAB8 8003CEB8 02231821 */  addu  $v1, $s1, $v1
/* 03DABC 8003CEBC A4620000 */  sh    $v0, ($v1)
/* 03DAC0 8003CEC0 00148400 */  sll   $s0, $s4, 0x10
/* 03DAC4 8003CEC4 00108403 */  sra   $s0, $s0, 0x10
/* 03DAC8 8003CEC8 8EC2000C */  lw    $v0, 0xc($s6)
/* 03DACC 8003CECC 02221021 */  addu  $v0, $s1, $v0
/* 03DAD0 8003CED0 86C4000A */  lh    $a0, 0xa($s6)
/* 03DAD4 8003CED4 02002821 */  addu  $a1, $s0, $zero
/* 03DAD8 8003CED8 84460000 */  lh    $a2, ($v0)
/* 03DADC 8003CEDC 0C019C82 */  jal   func_80067208
/* 03DAE0 8003CEE0 00003821 */   addu  $a3, $zero, $zero
/* 03DAE4 8003CEE4 86C4000A */  lh    $a0, 0xa($s6)
/* 03DAE8 8003CEE8 02002821 */  addu  $a1, $s0, $zero
/* 03DAEC 8003CEEC 0C019CE1 */  jal   func_80067384
/* 03DAF0 8003CEF0 24060001 */   li    $a2, 1
/* 03DAF4 8003CEF4 86C4000A */  lh    $a0, 0xa($s6)
/* 03DAF8 8003CEF8 02002821 */  addu  $a1, $s0, $zero
/* 03DAFC 8003CEFC 3C060100 */  lui   $a2, %hi(0x00FFFFE2) # $a2, 0x100
/* 03DB00 8003CF00 0C019D2F */  jal   func_800674BC
/* 03DB04 8003CF04 34C61000 */   ori   $a2, (0x01001000 & 0xFFFF) # ori $a2, $a2, 0x1000
/* 03DB08 8003CF08 3C12800C */  lui   $s2, %hi(D_800C430C) # $s2, 0x800c
/* 03DB0C 8003CF0C 2652430C */  addiu $s2, %lo(D_800C430C) # addiu $s2, $s2, 0x430c
/* 03DB10 8003CF10 02329021 */  addu  $s2, $s1, $s2
/* 03DB14 8003CF14 96460000 */  lhu   $a2, ($s2)
/* 03DB18 8003CF18 24C6FFE2 */  addiu $a2, %lo(0x00FFFFE2) # addiu $a2, $a2, -0x1e
/* 03DB1C 8003CF1C 00063400 */  sll   $a2, $a2, 0x10
/* 03DB20 8003CF20 3C13800C */  lui   $s3, %hi(D_800C4314) # $s3, 0x800c
/* 03DB24 8003CF24 26734314 */  addiu $s3, %lo(D_800C4314) # addiu $s3, $s3, 0x4314
/* 03DB28 8003CF28 02339821 */  addu  $s3, $s1, $s3
/* 03DB2C 8003CF2C 86C4000A */  lh    $a0, 0xa($s6)
/* 03DB30 8003CF30 02002821 */  addu  $a1, $s0, $zero
/* 03DB34 8003CF34 86670000 */  lh    $a3, ($s3)
/* 03DB38 8003CF38 0C019B71 */  jal   func_80066DC4
/* 03DB3C 8003CF3C 00063403 */   sra   $a2, $a2, 0x10
/* 03DB40 8003CF40 0C0051CC */  jal   FreeMainFS
/* 03DB44 8003CF44 02E02021 */   addu  $a0, $s7, $zero
/* 03DB48 8003CF48 92A20004 */  lbu   $v0, 4($s5)
/* 03DB4C 8003CF4C 00021080 */  sll   $v0, $v0, 2
/* 03DB50 8003CF50 3C04800C */  lui   $a0, 0x800c
/* 03DB54 8003CF54 00822021 */  addu  $a0, $a0, $v0
/* 03DB58 8003CF58 8C844334 */  lw    $a0, 0x4334($a0)
/* 03DB5C 8003CF5C 0C00516C */  jal   ReadMainFS
/* 03DB60 8003CF60 26900004 */   addiu $s0, $s4, 4
/* 03DB64 8003CF64 0040B821 */  addu  $s7, $v0, $zero
/* 03DB68 8003CF68 0C019E29 */  jal   func_800678A4
/* 03DB6C 8003CF6C 02E02021 */   addu  $a0, $s7, $zero
/* 03DB70 8003CF70 8EC3000C */  lw    $v1, 0xc($s6)
/* 03DB74 8003CF74 02231821 */  addu  $v1, $s1, $v1
/* 03DB78 8003CF78 A4620008 */  sh    $v0, 8($v1)
/* 03DB7C 8003CF7C 00108400 */  sll   $s0, $s0, 0x10
/* 03DB80 8003CF80 00108403 */  sra   $s0, $s0, 0x10
/* 03DB84 8003CF84 8EC2000C */  lw    $v0, 0xc($s6)
/* 03DB88 8003CF88 02228821 */  addu  $s1, $s1, $v0
/* 03DB8C 8003CF8C 86C4000A */  lh    $a0, 0xa($s6)
/* 03DB90 8003CF90 02002821 */  addu  $a1, $s0, $zero
/* 03DB94 8003CF94 86260008 */  lh    $a2, 8($s1)
/* 03DB98 8003CF98 0C019C82 */  jal   func_80067208
/* 03DB9C 8003CF9C 00003821 */   addu  $a3, $zero, $zero
/* 03DBA0 8003CFA0 86C4000A */  lh    $a0, 0xa($s6)
/* 03DBA4 8003CFA4 02002821 */  addu  $a1, $s0, $zero
/* 03DBA8 8003CFA8 0C019CE1 */  jal   func_80067384
/* 03DBAC 8003CFAC 24060001 */   li    $a2, 1
/* 03DBB0 8003CFB0 86C4000A */  lh    $a0, 0xa($s6)
/* 03DBB4 8003CFB4 02002821 */  addu  $a1, $s0, $zero
/* 03DBB8 8003CFB8 3C060100 */  lui   $a2, %hi(0x01000008) # $a2, 0x100
/* 03DBBC 8003CFBC 0C019D2F */  jal   func_800674BC
/* 03DBC0 8003CFC0 34C61000 */   ori   $a2, (0x01001000 & 0xFFFF) # ori $a2, $a2, 0x1000
/* 03DBC4 8003CFC4 96460000 */  lhu   $a2, ($s2)
/* 03DBC8 8003CFC8 24C60008 */  addiu $a2, %lo(0x01000008) # addiu $a2, $a2, 8
/* 03DBCC 8003CFCC 00063400 */  sll   $a2, $a2, 0x10
/* 03DBD0 8003CFD0 86C4000A */  lh    $a0, 0xa($s6)
/* 03DBD4 8003CFD4 02002821 */  addu  $a1, $s0, $zero
/* 03DBD8 8003CFD8 86670000 */  lh    $a3, ($s3)
/* 03DBDC 8003CFDC 0C019B71 */  jal   func_80066DC4
/* 03DBE0 8003CFE0 00063403 */   sra   $a2, $a2, 0x10
/* 03DBE4 8003CFE4 0C0051CC */  jal   FreeMainFS
/* 03DBE8 8003CFE8 02E02021 */   addu  $a0, $s7, $zero
/* 03DBEC 8003CFEC 26940001 */  addiu $s4, $s4, 1
/* 03DBF0 8003CFF0 2A820004 */  slti  $v0, $s4, 4
/* 03DBF4 8003CFF4 1440FFA2 */  bnez  $v0, .L8003CE80
/* 03DBF8 8003CFF8 00000000 */   nop   
/* 03DBFC 8003CFFC 0C018085 */  jal   func_80060214
/* 03DC00 8003D000 24040060 */   li    $a0, 96
/* 03DC04 8003D004 24040006 */  li    $a0, 6
/* 03DC08 8003D008 0C01C991 */  jal   func_80072644
/* 03DC0C 8003D00C 24050008 */   li    $a1, 8
/* 03DC10 8003D010 0C018D54 */  jal   SleepProcess
/* 03DC14 8003D014 24040007 */   li    $a0, 7
/* 03DC18 8003D018 00002021 */  addu  $a0, $zero, $zero
/* 03DC1C 8003D01C 24050014 */  li    $a1, 20
/* 03DC20 8003D020 0C011761 */  jal   func_80045D84
/* 03DC24 8003D024 00003021 */   addu  $a2, $zero, $zero
/* 03DC28 8003D028 0040A021 */  addu  $s4, $v0, $zero
/* 03DC2C 8003D02C 24040004 */  li    $a0, 4
/* 03DC30 8003D030 24050022 */  li    $a1, 34
/* 03DC34 8003D034 0C011761 */  jal   func_80045D84
/* 03DC38 8003D038 00003021 */   addu  $a2, $zero, $zero
/* 03DC3C 8003D03C 00409821 */  addu  $s3, $v0, $zero
/* 03DC40 8003D040 3C02800F */  lui   $v0, %hi(D_800EC6EA) # $v0, 0x800f
/* 03DC44 8003D044 2442C6EA */  addiu $v0, %lo(D_800EC6EA) # addiu $v0, $v0, -0x3916
/* 03DC48 8003D048 8FA80024 */  lw    $t0, 0x24($sp)
/* 03DC4C 8003D04C 00081840 */  sll   $v1, $t0, 1
/* 03DC50 8003D050 00628021 */  addu  $s0, $v1, $v0
/* 03DC54 8003D054 3C12800C */  lui   $s2, %hi(D_800C42EC) # $s2, 0x800c
/* 03DC58 8003D058 265242EC */  addiu $s2, %lo(D_800C42EC) # addiu $s2, $s2, 0x42ec
/* 03DC5C 8003D05C 3C02800F */  lui   $v0, %hi(D_800F5460) # $v0, 0x800f
/* 03DC60 8003D060 24425460 */  addiu $v0, %lo(D_800F5460) # addiu $v0, $v0, 0x5460
/* 03DC64 8003D064 00628821 */  addu  $s1, $v1, $v0
.L8003D068:
/* 03DC68 8003D068 0C018D6D */  jal   SleepVProcess
/* 03DC6C 8003D06C 00000000 */   nop   
/* 03DC70 8003D070 96030000 */  lhu   $v1, ($s0)
/* 03DC74 8003D074 30620800 */  andi  $v0, $v1, 0x800
/* 03DC78 8003D078 2C420001 */  sltiu $v0, $v0, 1
/* 03DC7C 8003D07C 30630400 */  andi  $v1, $v1, 0x400
/* 03DC80 8003D080 10600002 */  beqz  $v1, .L8003D08C
/* 03DC84 8003D084 00022023 */   negu  $a0, $v0
/* 03DC88 8003D088 24040001 */  li    $a0, 1
.L8003D08C:
/* 03DC8C 8003D08C 96020000 */  lhu   $v0, ($s0)
/* 03DC90 8003D090 30420200 */  andi  $v0, $v0, 0x200
/* 03DC94 8003D094 54400001 */  bnezl $v0, .L8003D09C
/* 03DC98 8003D098 24040002 */   li    $a0, 2
.L8003D09C:
/* 03DC9C 8003D09C 96020000 */  lhu   $v0, ($s0)
/* 03DCA0 8003D0A0 30420100 */  andi  $v0, $v0, 0x100
/* 03DCA4 8003D0A4 54400001 */  bnezl $v0, .L8003D0AC
/* 03DCA8 8003D0A8 24040003 */   li    $a0, 3
.L8003D0AC:
/* 03DCAC 8003D0AC 00041400 */  sll   $v0, $a0, 0x10
/* 03DCB0 8003D0B0 00021C03 */  sra   $v1, $v0, 0x10
/* 03DCB4 8003D0B4 2402FFFF */  li    $v0, -1
/* 03DCB8 8003D0B8 10620009 */  beq   $v1, $v0, .L8003D0E0
/* 03DCBC 8003D0BC 00031840 */   sll   $v1, $v1, 1
/* 03DCC0 8003D0C0 97A80036 */  lhu   $t0, 0x36($sp)
/* 03DCC4 8003D0C4 00081400 */  sll   $v0, $t0, 0x10
/* 03DCC8 8003D0C8 00021343 */  sra   $v0, $v0, 0xd
/* 03DCCC 8003D0CC 00521021 */  addu  $v0, $v0, $s2
/* 03DCD0 8003D0D0 00621821 */  addu  $v1, $v1, $v0
/* 03DCD4 8003D0D4 94620000 */  lhu   $v0, ($v1)
/* 03DCD8 8003D0D8 00484021 */  addu  $t0, $v0, $t0
/* 03DCDC 8003D0DC A7A80036 */  sh    $t0, 0x36($sp)
.L8003D0E0:
/* 03DCE0 8003D0E0 97A80036 */  lhu   $t0, 0x36($sp)
/* 03DCE4 8003D0E4 3C01800D */  lui   $at, %hi(D_800D61B8) # $at, 0x800d
/* 03DCE8 8003D0E8 A42861B8 */  sh    $t0, %lo(D_800D61B8)($at)
/* 03DCEC 8003D0EC 96220000 */  lhu   $v0, ($s1)
/* 03DCF0 8003D0F0 3042E010 */  andi  $v0, $v0, 0xe010
/* 03DCF4 8003D0F4 1040FFDC */  beqz  $v0, .L8003D068
/* 03DCF8 8003D0F8 24040006 */   li    $a0, 6
/* 03DCFC 8003D0FC 0C01C9AB */  jal   func_800726AC
/* 03DD00 8003D100 24050008 */   li    $a1, 8
/* 03DD04 8003D104 0C018D54 */  jal   SleepProcess
/* 03DD08 8003D108 24040008 */   li    $a0, 8
/* 03DD0C 8003D10C 3C01800F */  lui   $at, %hi(D_800F384E) # $at, 0x800f
/* 03DD10 8003D110 0C012850 */  jal   func_8004A140
/* 03DD14 8003D114 A020384E */   sb    $zero, %lo(D_800F384E)($at)
/* 03DD18 8003D118 0C0127D3 */  jal   func_80049F4C
/* 03DD1C 8003D11C 8FA4002C */   lw    $a0, 0x2c($sp)
/* 03DD20 8003D120 0C012D87 */  jal   func_8004B61C
/* 03DD24 8003D124 27A40010 */   addiu $a0, $sp, 0x10
/* 03DD28 8003D128 0C018D6D */  jal   SleepVProcess
/* 03DD2C 8003D12C 00000000 */   nop   
/* 03DD30 8003D130 0C012948 */  jal   func_8004A520
/* 03DD34 8003D134 00000000 */   nop   
/* 03DD38 8003D138 3C02800F */  lui   $v0, (0x800F0001 >> 16) # lui $v0, 0x800f
/* 03DD3C 8003D13C 94425278 */  lhu   $v0, %lo(D_800F5278)($v0)
/* 03DD40 8003D140 34420001 */  ori   $v0, (0x800F0001 & 0xFFFF) # ori $v0, $v0, 1
/* 03DD44 8003D144 3C01800F */  lui   $at, %hi(D_800F5278) # $at, 0x800f
/* 03DD48 8003D148 A4225278 */  sh    $v0, %lo(D_800F5278)($at)
/* 03DD4C 8003D14C 3C10800F */  lui   $s0, %hi(D_800ED5DC) # $s0, 0x800f
/* 03DD50 8003D150 2610D5DC */  addiu $s0, %lo(D_800ED5DC) # addiu $s0, $s0, -0x2a24
/* 03DD54 8003D154 0C00FFBF */  jal   func_8003FEFC
/* 03DD58 8003D158 86040000 */   lh    $a0, ($s0)
/* 03DD5C 8003D15C 0C0101C9 */  jal   func_80040724
/* 03DD60 8003D160 86040000 */   lh    $a0, ($s0)
/* 03DD64 8003D164 0C01179B */  jal   func_80045E6C
/* 03DD68 8003D168 02802021 */   addu  $a0, $s4, $zero
/* 03DD6C 8003D16C 0C01179B */  jal   func_80045E6C
/* 03DD70 8003D170 02602021 */   addu  $a0, $s3, $zero
/* 03DD74 8003D174 8FA4003C */  lw    $a0, 0x3c($sp)
/* 03DD78 8003D178 0C017764 */  jal   EndProcess
/* 03DD7C 8003D17C 00000000 */   nop   
/* 03DD80 8003D180 0C014D15 */  jal   func_80053454
/* 03DD84 8003D184 02C02021 */   addu  $a0, $s6, $zero
/* 03DD88 8003D188 0C014D15 */  jal   func_80053454
/* 03DD8C 8003D18C 03C02021 */   addu  $a0, $fp, $zero
/* 03DD90 8003D190 0C00F216 */  jal   func_8003C858
/* 03DD94 8003D194 00000000 */   nop   
/* 03DD98 8003D198 0C00F0D4 */  jal   func_8003C350
/* 03DD9C 8003D19C 00000000 */   nop   
/* 03DDA0 8003D1A0 0C0101C9 */  jal   func_80040724
/* 03DDA4 8003D1A4 8FA40024 */   lw    $a0, 0x24($sp)
/* 03DDA8 8003D1A8 0C01567E */  jal   func_800559F8
/* 03DDAC 8003D1AC 00000000 */   nop   
/* 03DDB0 8003D1B0 0C012E75 */  jal   func_8004B9D4
/* 03DDB4 8003D1B4 00002021 */   addu  $a0, $zero, $zero
/* 03DDB8 8003D1B8 0C018085 */  jal   func_80060214
/* 03DDBC 8003D1BC 2404007F */   li    $a0, 127
/* 03DDC0 8003D1C0 24040006 */  li    $a0, 6
/* 03DDC4 8003D1C4 0C01C991 */  jal   func_80072644
/* 03DDC8 8003D1C8 24050008 */   li    $a1, 8
/* 03DDCC 8003D1CC 0C018D54 */  jal   SleepProcess
/* 03DDD0 8003D1D0 24040008 */   li    $a0, 8
/* 03DDD4 8003D1D4 0C017764 */  jal   EndProcess
/* 03DDD8 8003D1D8 00002021 */   addu  $a0, $zero, $zero
/* 03DDDC 8003D1DC 8FBF0064 */  lw    $ra, 0x64($sp)
/* 03DDE0 8003D1E0 8FBE0060 */  lw    $fp, 0x60($sp)
/* 03DDE4 8003D1E4 8FB7005C */  lw    $s7, 0x5c($sp)
/* 03DDE8 8003D1E8 8FB60058 */  lw    $s6, 0x58($sp)
/* 03DDEC 8003D1EC 8FB50054 */  lw    $s5, 0x54($sp)
/* 03DDF0 8003D1F0 8FB40050 */  lw    $s4, 0x50($sp)
/* 03DDF4 8003D1F4 8FB3004C */  lw    $s3, 0x4c($sp)
/* 03DDF8 8003D1F8 8FB20048 */  lw    $s2, 0x48($sp)
/* 03DDFC 8003D1FC 8FB10044 */  lw    $s1, 0x44($sp)
/* 03DE00 8003D200 8FB00040 */  lw    $s0, 0x40($sp)
/* 03DE04 8003D204 03E00008 */  jr    $ra
/* 03DE08 8003D208 27BD0068 */   addiu $sp, $sp, 0x68

glabel func_8003D20C
/* 03DE0C 8003D20C 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 03DE10 8003D210 AFBF001C */  sw    $ra, 0x1c($sp)
/* 03DE14 8003D214 AFB20018 */  sw    $s2, 0x18($sp)
/* 03DE18 8003D218 AFB10014 */  sw    $s1, 0x14($sp)
/* 03DE1C 8003D21C AFB00010 */  sw    $s0, 0x10($sp)
/* 03DE20 8003D220 24020001 */  li    $v0, 1
/* 03DE24 8003D224 3C01800F */  lui   $at, %hi(D_800ECC22) # $at, 0x800f
/* 03DE28 8003D228 A022CC22 */  sb    $v0, %lo(D_800ECC22)($at)
/* 03DE2C 8003D22C 0C017F5F */  jal   func_8005FD7C
/* 03DE30 8003D230 00809021 */   addu  $s2, $a0, $zero
/* 03DE34 8003D234 0C018CEA */  jal   GetCurrentProcess
/* 03DE38 8003D238 00000000 */   nop   
/* 03DE3C 8003D23C 00408821 */  addu  $s1, $v0, $zero
/* 03DE40 8003D240 3C048004 */  lui   $a0, %hi(D_8003CAB4) # $a0, 0x8004
/* 03DE44 8003D244 2484CAB4 */  addiu $a0, %lo(D_8003CAB4) # addiu $a0, $a0, -0x354c
/* 03DE48 8003D248 24051005 */  li    $a1, 4101
/* 03DE4C 8003D24C 00003021 */  addu  $a2, $zero, $zero
/* 03DE50 8003D250 0C01770A */  jal   InitProcess
/* 03DE54 8003D254 00003821 */   addu  $a3, $zero, $zero
/* 03DE58 8003D258 00408021 */  addu  $s0, $v0, $zero
/* 03DE5C 8003D25C AE12008C */  sw    $s2, 0x8c($s0)
/* 03DE60 8003D260 02002021 */  addu  $a0, $s0, $zero
/* 03DE64 8003D264 0C017640 */  jal   func_8005D900
/* 03DE68 8003D268 24050080 */   li    $a1, 128
/* 03DE6C 8003D26C 02202021 */  addu  $a0, $s1, $zero
/* 03DE70 8003D270 0C018C9C */  jal   LinkChildProcess
/* 03DE74 8003D274 02002821 */   addu  $a1, $s0, $zero
/* 03DE78 8003D278 0C018CD6 */  jal   WaitForChildProcess
/* 03DE7C 8003D27C 00000000 */   nop   
/* 03DE80 8003D280 0C017FB3 */  jal   func_8005FECC
/* 03DE84 8003D284 00000000 */   nop   
/* 03DE88 8003D288 3C01800F */  lui   $at, %hi(D_800ECC22) # $at, 0x800f
/* 03DE8C 8003D28C A020CC22 */  sb    $zero, %lo(D_800ECC22)($at)
/* 03DE90 8003D290 8FBF001C */  lw    $ra, 0x1c($sp)
/* 03DE94 8003D294 8FB20018 */  lw    $s2, 0x18($sp)
/* 03DE98 8003D298 8FB10014 */  lw    $s1, 0x14($sp)
/* 03DE9C 8003D29C 8FB00010 */  lw    $s0, 0x10($sp)
/* 03DEA0 8003D2A0 03E00008 */  jr    $ra
/* 03DEA4 8003D2A4 27BD0020 */   addiu $sp, $sp, 0x20

/* 03DEA8 8003D2A8 00000000 */  nop   
/* 03DEAC 8003D2AC 00000000 */  nop   
