# Mario Party (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "globals.inc"
.include "macros.inc"

glabel func_8004CB70
/* 04D770 8004CB70 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 04D774 8004CB74 AFBF0018 */  sw    $ra, 0x18($sp)
/* 04D778 8004CB78 AFB10014 */  sw    $s1, 0x14($sp)
/* 04D77C 8004CB7C AFB00010 */  sw    $s0, 0x10($sp)
/* 04D780 8004CB80 00808021 */  addu  $s0, $a0, $zero
/* 04D784 8004CB84 00C08821 */  addu  $s1, $a2, $zero
/* 04D788 8004CB88 00052400 */  sll   $a0, $a1, 0x10
/* 04D78C 8004CB8C 0C01307B */  jal   GetSpaceData
/* 04D790 8004CB90 00042403 */   sra   $a0, $a0, 0x10
/* 04D794 8004CB94 C4400004 */  lwc1  $f0, 4($v0)
/* 04D798 8004CB98 E6200000 */  swc1  $f0, ($s1)
/* 04D79C 8004CB9C C4400008 */  lwc1  $f0, 8($v0)
/* 04D7A0 8004CBA0 E6200004 */  swc1  $f0, 4($s1)
/* 04D7A4 8004CBA4 C440000C */  lwc1  $f0, 0xc($v0)
/* 04D7A8 8004CBA8 00108400 */  sll   $s0, $s0, 0x10
/* 04D7AC 8004CBAC 00108403 */  sra   $s0, $s0, 0x10
/* 04D7B0 8004CBB0 2402FFFF */  li    $v0, -1
/* 04D7B4 8004CBB4 12020012 */  beq   $s0, $v0, .L8004CC00
/* 04D7B8 8004CBB8 E6200008 */   swc1  $f0, 8($s1)
/* 04D7BC 8004CBBC 0C014AB3 */  jal   PlayerIsCurrent
/* 04D7C0 8004CBC0 02002021 */   addu  $a0, $s0, $zero
/* 04D7C4 8004CBC4 00021400 */  sll   $v0, $v0, 0x10
/* 04D7C8 8004CBC8 1440000D */  bnez  $v0, .L8004CC00
/* 04D7CC 8004CBCC 001010C0 */   sll   $v0, $s0, 3
/* 04D7D0 8004CBD0 C6200000 */  lwc1  $f0, ($s1)
/* 04D7D4 8004CBD4 3C01800C */  lui   $at, 0x800c
/* 04D7D8 8004CBD8 00220821 */  addu  $at, $at, $v0
/* 04D7DC 8004CBDC C42251C0 */  lwc1  $f2, 0x51c0($at)
/* 04D7E0 8004CBE0 46020000 */  add.s $f0, $f0, $f2
/* 04D7E4 8004CBE4 E6200000 */  swc1  $f0, ($s1)
/* 04D7E8 8004CBE8 C6200008 */  lwc1  $f0, 8($s1)
/* 04D7EC 8004CBEC 3C01800C */  lui   $at, 0x800c
/* 04D7F0 8004CBF0 00220821 */  addu  $at, $at, $v0
/* 04D7F4 8004CBF4 C42251C4 */  lwc1  $f2, 0x51c4($at)
/* 04D7F8 8004CBF8 46020000 */  add.s $f0, $f0, $f2
/* 04D7FC 8004CBFC E6200008 */  swc1  $f0, 8($s1)
.L8004CC00:
/* 04D800 8004CC00 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04D804 8004CC04 8FB10014 */  lw    $s1, 0x14($sp)
/* 04D808 8004CC08 8FB00010 */  lw    $s0, 0x10($sp)
/* 04D80C 8004CC0C 03E00008 */  jr    $ra
/* 04D810 8004CC10 27BD0020 */   addiu $sp, $sp, 0x20

glabel func_8004CC14
/* 04D814 8004CC14 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 04D818 8004CC18 AFBF0018 */  sw    $ra, 0x18($sp)
/* 04D81C 8004CC1C AFB10014 */  sw    $s1, 0x14($sp)
/* 04D820 8004CC20 AFB00010 */  sw    $s0, 0x10($sp)
/* 04D824 8004CC24 00808021 */  addu  $s0, $a0, $zero
/* 04D828 8004CC28 00C08821 */  addu  $s1, $a2, $zero
/* 04D82C 8004CC2C 00052400 */  sll   $a0, $a1, 0x10
/* 04D830 8004CC30 0C01307B */  jal   GetSpaceData
/* 04D834 8004CC34 00042403 */   sra   $a0, $a0, 0x10
/* 04D838 8004CC38 00108400 */  sll   $s0, $s0, 0x10
/* 04D83C 8004CC3C 00108343 */  sra   $s0, $s0, 0xd
/* 04D840 8004CC40 C4400004 */  lwc1  $f0, 4($v0)
/* 04D844 8004CC44 3C01800C */  lui   $at, 0x800c
/* 04D848 8004CC48 00300821 */  addu  $at, $at, $s0
/* 04D84C 8004CC4C C42251E0 */  lwc1  $f2, 0x51e0($at)
/* 04D850 8004CC50 46020000 */  add.s $f0, $f0, $f2
/* 04D854 8004CC54 E6200000 */  swc1  $f0, ($s1)
/* 04D858 8004CC58 C4400008 */  lwc1  $f0, 8($v0)
/* 04D85C 8004CC5C E6200004 */  swc1  $f0, 4($s1)
/* 04D860 8004CC60 C440000C */  lwc1  $f0, 0xc($v0)
/* 04D864 8004CC64 3C01800C */  lui   $at, 0x800c
/* 04D868 8004CC68 00300821 */  addu  $at, $at, $s0
/* 04D86C 8004CC6C C42251E4 */  lwc1  $f2, 0x51e4($at)
/* 04D870 8004CC70 46020000 */  add.s $f0, $f0, $f2
/* 04D874 8004CC74 E6200008 */  swc1  $f0, 8($s1)
/* 04D878 8004CC78 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04D87C 8004CC7C 8FB10014 */  lw    $s1, 0x14($sp)
/* 04D880 8004CC80 8FB00010 */  lw    $s0, 0x10($sp)
/* 04D884 8004CC84 03E00008 */  jr    $ra
/* 04D888 8004CC88 27BD0020 */   addiu $sp, $sp, 0x20

glabel func_8004CC8C
/* 04D88C 8004CC8C 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04D890 8004CC90 AFBF0010 */  sw    $ra, 0x10($sp)
/* 04D894 8004CC94 00042400 */  sll   $a0, $a0, 0x10
/* 04D898 8004CC98 00042403 */  sra   $a0, $a0, 0x10
/* 04D89C 8004CC9C 00052C00 */  sll   $a1, $a1, 0x10
/* 04D8A0 8004CCA0 00041040 */  sll   $v0, $a0, 1
/* 04D8A4 8004CCA4 00441021 */  addu  $v0, $v0, $a0
/* 04D8A8 8004CCA8 00021100 */  sll   $v0, $v0, 4
/* 04D8AC 8004CCAC 3C06800F */  lui   $a2, 0x800f
/* 04D8B0 8004CCB0 00C23021 */  addu  $a2, $a2, $v0
/* 04D8B4 8004CCB4 8CC632D0 */  lw    $a2, 0x32d0($a2)
/* 04D8B8 8004CCB8 00052C03 */  sra   $a1, $a1, 0x10
/* 04D8BC 8004CCBC 0C0132DC */  jal   func_8004CB70
/* 04D8C0 8004CCC0 24C6000C */   addiu $a2, $a2, 0xc
/* 04D8C4 8004CCC4 8FBF0010 */  lw    $ra, 0x10($sp)
/* 04D8C8 8004CCC8 03E00008 */  jr    $ra
/* 04D8CC 8004CCCC 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8004CCD0
/* 04D8D0 8004CCD0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04D8D4 8004CCD4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 04D8D8 8004CCD8 AFB00010 */  sw    $s0, 0x10($sp)
/* 04D8DC 8004CCDC 00801021 */  addu  $v0, $a0, $zero
/* 04D8E0 8004CCE0 00C08021 */  addu  $s0, $a2, $zero
/* 04D8E4 8004CCE4 02002021 */  addu  $a0, $s0, $zero
/* 04D8E8 8004CCE8 0C0283A0 */  jal   func_800A0E80
/* 04D8EC 8004CCEC 00403021 */   addu  $a2, $v0, $zero
/* 04D8F0 8004CCF0 0C00F502 */  jal   func_8003D408
/* 04D8F4 8004CCF4 02002021 */   addu  $a0, $s0, $zero
/* 04D8F8 8004CCF8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 04D8FC 8004CCFC 8FB00010 */  lw    $s0, 0x10($sp)
/* 04D900 8004CD00 03E00008 */  jr    $ra
/* 04D904 8004CD04 27BD0018 */   addiu $sp, $sp, 0x18

/* 04D908 8004CD08 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04D90C 8004CD0C AFBF0014 */  sw    $ra, 0x14($sp)
/* 04D910 8004CD10 AFB00010 */  sw    $s0, 0x10($sp)
/* 04D914 8004CD14 00A08021 */  addu  $s0, $a1, $zero
/* 04D918 8004CD18 00042400 */  sll   $a0, $a0, 0x10
/* 04D91C 8004CD1C 0C014AA3 */  jal   GetPlayerStruct
/* 04D920 8004CD20 00042403 */   sra   $a0, $a0, 0x10
/* 04D924 8004CD24 8C460020 */  lw    $a2, 0x20($v0)
/* 04D928 8004CD28 24C4000C */  addiu $a0, $a2, 0xc
/* 04D92C 8004CD2C 02002821 */  addu  $a1, $s0, $zero
/* 04D930 8004CD30 0C013334 */  jal   func_8004CCD0
/* 04D934 8004CD34 24C60018 */   addiu $a2, $a2, 0x18
/* 04D938 8004CD38 8FBF0014 */  lw    $ra, 0x14($sp)
/* 04D93C 8004CD3C 8FB00010 */  lw    $s0, 0x10($sp)
/* 04D940 8004CD40 03E00008 */  jr    $ra
/* 04D944 8004CD44 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8004CD48
/* 04D948 8004CD48 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04D94C 8004CD4C AFBF0014 */  sw    $ra, 0x14($sp)
/* 04D950 8004CD50 AFB00010 */  sw    $s0, 0x10($sp)
/* 04D954 8004CD54 00808021 */  addu  $s0, $a0, $zero
/* 04D958 8004CD58 00052400 */  sll   $a0, $a1, 0x10
/* 04D95C 8004CD5C 0C01307B */  jal   GetSpaceData
/* 04D960 8004CD60 00042403 */   sra   $a0, $a0, 0x10
/* 04D964 8004CD64 2604000C */  addiu $a0, $s0, 0xc
/* 04D968 8004CD68 24450004 */  addiu $a1, $v0, 4
/* 04D96C 8004CD6C 0C013334 */  jal   func_8004CCD0
/* 04D970 8004CD70 26060018 */   addiu $a2, $s0, 0x18
/* 04D974 8004CD74 8FBF0014 */  lw    $ra, 0x14($sp)
/* 04D978 8004CD78 8FB00010 */  lw    $s0, 0x10($sp)
/* 04D97C 8004CD7C 03E00008 */  jr    $ra
/* 04D980 8004CD80 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8004CD84
/* 04D984 8004CD84 AC800000 */  sw    $zero, ($a0)
/* 04D988 8004CD88 AC800004 */  sw    $zero, 4($a0)
/* 04D98C 8004CD8C 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 04D990 8004CD90 44810000 */  mtc1  $at, $f0
/* 04D994 8004CD94 00000000 */  nop   
/* 04D998 8004CD98 03E00008 */  jr    $ra
/* 04D99C 8004CD9C E4800008 */   swc1  $f0, 8($a0)

glabel func_8004CDA0
/* 04D9A0 8004CDA0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04D9A4 8004CDA4 AFBF0010 */  sw    $ra, 0x10($sp)
/* 04D9A8 8004CDA8 00042400 */  sll   $a0, $a0, 0x10
/* 04D9AC 8004CDAC 0C014AA3 */  jal   GetPlayerStruct
/* 04D9B0 8004CDB0 00042403 */   sra   $a0, $a0, 0x10
/* 04D9B4 8004CDB4 8C440020 */  lw    $a0, 0x20($v0)
/* 04D9B8 8004CDB8 0C013361 */  jal   func_8004CD84
/* 04D9BC 8004CDBC 24840018 */   addiu $a0, $a0, 0x18
/* 04D9C0 8004CDC0 8FBF0010 */  lw    $ra, 0x10($sp)
/* 04D9C4 8004CDC4 03E00008 */  jr    $ra
/* 04D9C8 8004CDC8 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8004CDCC
/* 04D9CC 8004CDCC 27BDFFC0 */  addiu $sp, $sp, -0x40
/* 04D9D0 8004CDD0 AFBF003C */  sw    $ra, 0x3c($sp)
/* 04D9D4 8004CDD4 AFB20038 */  sw    $s2, 0x38($sp)
/* 04D9D8 8004CDD8 AFB10034 */  sw    $s1, 0x34($sp)
/* 04D9DC 8004CDDC AFB00030 */  sw    $s0, 0x30($sp)
/* 04D9E0 8004CDE0 00808821 */  addu  $s1, $a0, $zero
/* 04D9E4 8004CDE4 2632000C */  addiu $s2, $s1, 0xc
/* 04D9E8 8004CDE8 27A40010 */  addiu $a0, $sp, 0x10
/* 04D9EC 8004CDEC 3C05800C */  lui   $a1, %hi(D_800C3110) # $a1, 0x800c
/* 04D9F0 8004CDF0 8CA53110 */  lw    $a1, %lo(D_800C3110)($a1)
/* 04D9F4 8004CDF4 0C0283A0 */  jal   func_800A0E80
/* 04D9F8 8004CDF8 02403021 */   addu  $a2, $s2, $zero
/* 04D9FC 8004CDFC 27B00020 */  addiu $s0, $sp, 0x20
/* 04DA00 8004CE00 02002021 */  addu  $a0, $s0, $zero
/* 04DA04 8004CE04 8FA50010 */  lw    $a1, 0x10($sp)
/* 04DA08 8004CE08 8FA70018 */  lw    $a3, 0x18($sp)
/* 04DA0C 8004CE0C 0C028340 */  jal   func_800A0D00
/* 04DA10 8004CE10 00003021 */   addu  $a2, $zero, $zero
/* 04DA14 8004CE14 27A40010 */  addiu $a0, $sp, 0x10
/* 04DA18 8004CE18 0C00F633 */  jal   func_8003D8CC
/* 04DA1C 8004CE1C 02002821 */   addu  $a1, $s0, $zero
/* 04DA20 8004CE20 8E22003C */  lw    $v0, 0x3c($s1)
/* 04DA24 8004CE24 46000007 */  neg.s $f0, $f0
/* 04DA28 8004CE28 E4400024 */  swc1  $f0, 0x24($v0)
/* 04DA2C 8004CE2C 02402021 */  addu  $a0, $s2, $zero
/* 04DA30 8004CE30 3C05800C */  lui   $a1, %hi(D_800C3110) # $a1, 0x800c
/* 04DA34 8004CE34 8CA53110 */  lw    $a1, %lo(D_800C3110)($a1)
/* 04DA38 8004CE38 0C013334 */  jal   func_8004CCD0
/* 04DA3C 8004CE3C 27A60010 */   addiu $a2, $sp, 0x10
/* 04DA40 8004CE40 0C00F4AC */  jal   func_8003D2B0
/* 04DA44 8004CE44 27A40010 */   addiu $a0, $sp, 0x10
/* 04DA48 8004CE48 8E22003C */  lw    $v0, 0x3c($s1)
/* 04DA4C 8004CE4C E4400028 */  swc1  $f0, 0x28($v0)
/* 04DA50 8004CE50 8E22003C */  lw    $v0, 0x3c($s1)
/* 04DA54 8004CE54 AC40002C */  sw    $zero, 0x2c($v0)
/* 04DA58 8004CE58 8FBF003C */  lw    $ra, 0x3c($sp)
/* 04DA5C 8004CE5C 8FB20038 */  lw    $s2, 0x38($sp)
/* 04DA60 8004CE60 8FB10034 */  lw    $s1, 0x34($sp)
/* 04DA64 8004CE64 8FB00030 */  lw    $s0, 0x30($sp)
/* 04DA68 8004CE68 03E00008 */  jr    $ra
/* 04DA6C 8004CE6C 27BD0040 */   addiu $sp, $sp, 0x40

glabel func_8004CE70
/* 04DA70 8004CE70 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 04DA74 8004CE74 AFBF0018 */  sw    $ra, 0x18($sp)
/* 04DA78 8004CE78 AFB10014 */  sw    $s1, 0x14($sp)
/* 04DA7C 8004CE7C AFB00010 */  sw    $s0, 0x10($sp)
/* 04DA80 8004CE80 00A08821 */  addu  $s1, $a1, $zero
/* 04DA84 8004CE84 00042400 */  sll   $a0, $a0, 0x10
/* 04DA88 8004CE88 0C014AA3 */  jal   GetPlayerStruct
/* 04DA8C 8004CE8C 00042403 */   sra   $a0, $a0, 0x10
/* 04DA90 8004CE90 00408021 */  addu  $s0, $v0, $zero
/* 04DA94 8004CE94 00118C00 */  sll   $s1, $s1, 0x10
/* 04DA98 8004CE98 0C014AA3 */  jal   GetPlayerStruct
/* 04DA9C 8004CE9C 00112403 */   sra   $a0, $s1, 0x10
/* 04DAA0 8004CEA0 9604000E */  lhu   $a0, 0xe($s0)
/* 04DAA4 8004CEA4 9443000E */  lhu   $v1, 0xe($v0)
/* 04DAA8 8004CEA8 A603000E */  sh    $v1, 0xe($s0)
/* 04DAAC 8004CEAC A444000E */  sh    $a0, 0xe($v0)
/* 04DAB0 8004CEB0 96040010 */  lhu   $a0, 0x10($s0)
/* 04DAB4 8004CEB4 94430010 */  lhu   $v1, 0x10($v0)
/* 04DAB8 8004CEB8 A6030010 */  sh    $v1, 0x10($s0)
/* 04DABC 8004CEBC A4440010 */  sh    $a0, 0x10($v0)
/* 04DAC0 8004CEC0 96040012 */  lhu   $a0, 0x12($s0)
/* 04DAC4 8004CEC4 94430012 */  lhu   $v1, 0x12($v0)
/* 04DAC8 8004CEC8 A6030012 */  sh    $v1, 0x12($s0)
/* 04DACC 8004CECC A4440012 */  sh    $a0, 0x12($v0)
/* 04DAD0 8004CED0 96040014 */  lhu   $a0, 0x14($s0)
/* 04DAD4 8004CED4 94430014 */  lhu   $v1, 0x14($v0)
/* 04DAD8 8004CED8 A6030014 */  sh    $v1, 0x14($s0)
/* 04DADC 8004CEDC A4440014 */  sh    $a0, 0x14($v0)
/* 04DAE0 8004CEE0 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04DAE4 8004CEE4 8FB10014 */  lw    $s1, 0x14($sp)
/* 04DAE8 8004CEE8 8FB00010 */  lw    $s0, 0x10($sp)
/* 04DAEC 8004CEEC 03E00008 */  jr    $ra
/* 04DAF0 8004CEF0 27BD0020 */   addiu $sp, $sp, 0x20

glabel func_8004CEF4
/* 04DAF4 8004CEF4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04DAF8 8004CEF8 AFBF0014 */  sw    $ra, 0x14($sp)
/* 04DAFC 8004CEFC AFB00010 */  sw    $s0, 0x10($sp)
/* 04DB00 8004CF00 00A08021 */  addu  $s0, $a1, $zero
/* 04DB04 8004CF04 00042400 */  sll   $a0, $a0, 0x10
/* 04DB08 8004CF08 0C014AA3 */  jal   GetPlayerStruct
/* 04DB0C 8004CF0C 00042403 */   sra   $a0, $a0, 0x10
/* 04DB10 8004CF10 00401821 */  addu  $v1, $v0, $zero
/* 04DB14 8004CF14 2610FFFF */  addiu $s0, $s0, -1
/* 04DB18 8004CF18 00108400 */  sll   $s0, $s0, 0x10
/* 04DB1C 8004CF1C 00108403 */  sra   $s0, $s0, 0x10
/* 04DB20 8004CF20 2E020009 */  sltiu $v0, $s0, 9
/* 04DB24 8004CF24 1040000C */  beqz  $v0, .L8004CF58
/* 04DB28 8004CF28 00101080 */   sll   $v0, $s0, 2
/* 04DB2C 8004CF2C 3C01800D */  lui   $at, 0x800d
/* 04DB30 8004CF30 00220821 */  addu  $at, $at, $v0
/* 04DB34 8004CF34 8C22B060 */  lw    $v0, -0x4fa0($at)
/* 04DB38 8004CF38 00400008 */  jr    $v0
/* 04DB3C 8004CF3C 00000000 */   nop   
/* 04DB40 8004CF40 080133D7 */  j     func_8004CF5C
SetPlayerBlue:
/* 04DB44 8004CF44 24020001 */   li    $v0, 1

/* 04DB48 8004CF48 080133D7 */  j     func_8004CF5C
SetPlayerRed:
/* 04DB4C 8004CF4C 24020002 */   li    $v0, 2

/* 04DB50 8004CF50 080133D7 */  j     func_8004CF5C
SetPlayerGreen:
/* 04DB54 8004CF54 24020004 */   li    $v0, 4

.L8004CF58:
/* 04DB58 8004CF58 00001021 */  addu  $v0, $zero, $zero
glabel func_8004CF5C
/* 04DB5C 8004CF5C A0620017 */  sb    $v0, 0x17($v1)
/* 04DB60 8004CF60 8FBF0014 */  lw    $ra, 0x14($sp)
/* 04DB64 8004CF64 8FB00010 */  lw    $s0, 0x10($sp)
/* 04DB68 8004CF68 03E00008 */  jr    $ra
/* 04DB6C 8004CF6C 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8004CF70
/* 04DB70 8004CF70 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 04DB74 8004CF74 AFBF0018 */  sw    $ra, 0x18($sp)
/* 04DB78 8004CF78 AFB10014 */  sw    $s1, 0x14($sp)
/* 04DB7C 8004CF7C AFB00010 */  sw    $s0, 0x10($sp)
/* 04DB80 8004CF80 00008821 */  addu  $s1, $zero, $zero
/* 04DB84 8004CF84 00008021 */  addu  $s0, $zero, $zero
.L8004CF88:
/* 04DB88 8004CF88 0C014AA3 */  jal   GetPlayerStruct
/* 04DB8C 8004CF8C 02002021 */   addu  $a0, $s0, $zero
/* 04DB90 8004CF90 8442000C */  lh    $v0, 0xc($v0)
/* 04DB94 8004CF94 02228821 */  addu  $s1, $s1, $v0
/* 04DB98 8004CF98 26100001 */  addiu $s0, $s0, 1
/* 04DB9C 8004CF9C 2A020004 */  slti  $v0, $s0, 4
/* 04DBA0 8004CFA0 1440FFF9 */  bnez  $v0, .L8004CF88
/* 04DBA4 8004CFA4 00111400 */   sll   $v0, $s1, 0x10
/* 04DBA8 8004CFA8 00021403 */  sra   $v0, $v0, 0x10
/* 04DBAC 8004CFAC 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04DBB0 8004CFB0 8FB10014 */  lw    $s1, 0x14($sp)
/* 04DBB4 8004CFB4 8FB00010 */  lw    $s0, 0x10($sp)
/* 04DBB8 8004CFB8 03E00008 */  jr    $ra
/* 04DBBC 8004CFBC 27BD0020 */   addiu $sp, $sp, 0x20

glabel func_8004CFC0
/* 04DBC0 8004CFC0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04DBC4 8004CFC4 AFBF0014 */  sw    $ra, 0x14($sp)
/* 04DBC8 8004CFC8 AFB00010 */  sw    $s0, 0x10($sp)
/* 04DBCC 8004CFCC 0C005D63 */  jal   GetRandomByte
/* 04DBD0 8004CFD0 00808021 */   addu  $s0, $a0, $zero
/* 04DBD4 8004CFD4 00108600 */  sll   $s0, $s0, 0x18
/* 04DBD8 8004CFD8 00108603 */  sra   $s0, $s0, 0x18
/* 04DBDC 8004CFDC 304300FF */  andi  $v1, $v0, 0xff
/* 04DBE0 8004CFE0 00031040 */  sll   $v0, $v1, 1
/* 04DBE4 8004CFE4 00431021 */  addu  $v0, $v0, $v1
/* 04DBE8 8004CFE8 00021940 */  sll   $v1, $v0, 5
/* 04DBEC 8004CFEC 00431021 */  addu  $v0, $v0, $v1
/* 04DBF0 8004CFF0 00021203 */  sra   $v0, $v0, 8
/* 04DBF4 8004CFF4 0050102A */  slt   $v0, $v0, $s0
/* 04DBF8 8004CFF8 8FBF0014 */  lw    $ra, 0x14($sp)
/* 04DBFC 8004CFFC 8FB00010 */  lw    $s0, 0x10($sp)
/* 04DC00 8004D000 03E00008 */  jr    $ra
/* 04DC04 8004D004 27BD0018 */   addiu $sp, $sp, 0x18

GetTurnsElapsed:
/* 04DC08 8004D008 3C02800F */  lui   $v0, %hi(D_800ED5C6) # $v0, 0x800f
/* 04DC0C 8004D00C 9442D5C6 */  lhu   $v0, %lo(D_800ED5C6)($v0)
/* 04DC10 8004D010 3C03800F */  lui   $v1, %hi(D_800ED5C8) # $v1, 0x800f
/* 04DC14 8004D014 9463D5C8 */  lhu   $v1, %lo(D_800ED5C8)($v1)
/* 04DC18 8004D018 00431023 */  subu  $v0, $v0, $v1
/* 04DC1C 8004D01C 24420001 */  addiu $v0, $v0, 1
/* 04DC20 8004D020 00021400 */  sll   $v0, $v0, 0x10
/* 04DC24 8004D024 03E00008 */  jr    $ra
/* 04DC28 8004D028 00021403 */   sra   $v0, $v0, 0x10

glabel func_8004D02C
/* 04DC2C 8004D02C 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 04DC30 8004D030 AFBF0020 */  sw    $ra, 0x20($sp)
/* 04DC34 8004D034 F7B40028 */  sdc1  $f20, 0x28($sp)
/* 04DC38 8004D038 4485A000 */  mtc1  $a1, $f20
/* 04DC3C 8004D03C 00042400 */  sll   $a0, $a0, 0x10
/* 04DC40 8004D040 00042403 */  sra   $a0, $a0, 0x10
/* 04DC44 8004D044 3C02800F */  lui   $v0, 0x800f
/* 04DC48 8004D048 00441021 */  addu  $v0, $v0, $a0
/* 04DC4C 8004D04C 8042CE14 */  lb    $v0, -0x31ec($v0)
/* 04DC50 8004D050 44820000 */  mtc1  $v0, $f0
/* 04DC54 8004D054 00000000 */  nop   
/* 04DC58 8004D058 46800020 */  cvt.s.w $f0, $f0
/* 04DC5C 8004D05C E7A00010 */  swc1  $f0, 0x10($sp)
/* 04DC60 8004D060 AFA00014 */  sw    $zero, 0x14($sp)
/* 04DC64 8004D064 3C02800F */  lui   $v0, 0x800f
/* 04DC68 8004D068 00441021 */  addu  $v0, $v0, $a0
/* 04DC6C 8004D06C 80423843 */  lb    $v0, 0x3843($v0)
/* 04DC70 8004D070 44820000 */  mtc1  $v0, $f0
/* 04DC74 8004D074 00000000 */  nop   
/* 04DC78 8004D078 46800020 */  cvt.s.w $f0, $f0
/* 04DC7C 8004D07C E7A00018 */  swc1  $f0, 0x18($sp)
/* 04DC80 8004D080 0C028480 */  jal   func_800A1200
/* 04DC84 8004D084 27A40010 */   addiu $a0, $sp, 0x10
/* 04DC88 8004D088 4600A03E */  c.le.s $f20, $f0
/* 04DC8C 8004D08C 00000000 */  nop   
/* 04DC90 8004D090 00000000 */  nop   
/* 04DC94 8004D094 45010002 */  bc1t  .L8004D0A0
/* 04DC98 8004D098 24020001 */   li    $v0, 1
/* 04DC9C 8004D09C 00001021 */  addu  $v0, $zero, $zero
.L8004D0A0:
/* 04DCA0 8004D0A0 8FBF0020 */  lw    $ra, 0x20($sp)
/* 04DCA4 8004D0A4 D7B40028 */  ldc1  $f20, 0x28($sp)
/* 04DCA8 8004D0A8 03E00008 */  jr    $ra
/* 04DCAC 8004D0AC 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8004D0B0
/* 04DCB0 8004D0B0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 04DCB4 8004D0B4 AFBF0010 */  sw    $ra, 0x10($sp)
/* 04DCB8 8004D0B8 00042400 */  sll   $a0, $a0, 0x10
/* 04DCBC 8004D0BC 00042383 */  sra   $a0, $a0, 0xe
/* 04DCC0 8004D0C0 3C01800C */  lui   $at, 0x800c
/* 04DCC4 8004D0C4 00240821 */  addu  $at, $at, $a0
/* 04DCC8 8004D0C8 0C0136E7 */  jal   func_8004DB9C
/* 04DCCC 8004D0CC 8C245200 */   lw    $a0, 0x5200($at)
/* 04DCD0 8004D0D0 8FBF0010 */  lw    $ra, 0x10($sp)
/* 04DCD4 8004D0D4 03E00008 */  jr    $ra
/* 04DCD8 8004D0D8 27BD0018 */   addiu $sp, $sp, 0x18

D_8004D0DC:
/* 04DCDC 8004D0DC 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 04DCE0 8004D0E0 AFBF0018 */  sw    $ra, 0x18($sp)
/* 04DCE4 8004D0E4 AFB10014 */  sw    $s1, 0x14($sp)
/* 04DCE8 8004D0E8 AFB00010 */  sw    $s0, 0x10($sp)
/* 04DCEC 8004D0EC F7B60028 */  sdc1  $f22, 0x28($sp)
/* 04DCF0 8004D0F0 0C018CEA */  jal   GetCurrentProcess
/* 04DCF4 8004D0F4 F7B40020 */   sdc1  $f20, 0x20($sp)
/* 04DCF8 8004D0F8 8C50008C */  lw    $s0, 0x8c($v0)
/* 04DCFC 8004D0FC 8E11001C */  lw    $s1, 0x1c($s0)
/* 04DD00 8004D100 0C00F4AC */  jal   func_8003D2B0
/* 04DD04 8004D104 02002021 */   addu  $a0, $s0, $zero
/* 04DD08 8004D108 46000506 */  mov.s $f20, $f0
/* 04DD0C 8004D10C 0C00F4AC */  jal   func_8003D2B0
/* 04DD10 8004D110 2604000C */   addiu $a0, $s0, 0xc
/* 04DD14 8004D114 46140581 */  sub.s $f22, $f0, $f20
/* 04DD18 8004D118 44800000 */  mtc1  $zero, $f0
/* 04DD1C 8004D11C 00000000 */  nop   
/* 04DD20 8004D120 4600B03C */  c.lt.s $f22, $f0
/* 04DD24 8004D124 00000000 */  nop   
/* 04DD28 8004D128 00000000 */  nop   
/* 04DD2C 8004D12C 45000005 */  bc1f  .L8004D144
/* 04DD30 8004D130 02002021 */   addu  $a0, $s0, $zero
/* 04DD34 8004D134 3C0143B4 */  li    $at, 0x43B40000 # 360.000000
/* 04DD38 8004D138 44810000 */  mtc1  $at, $f0
/* 04DD3C 8004D13C 00000000 */  nop   
/* 04DD40 8004D140 4600B580 */  add.s $f22, $f22, $f0
.L8004D144:
/* 04DD44 8004D144 0C00F633 */  jal   func_8003D8CC
/* 04DD48 8004D148 2605000C */   addiu $a1, $s0, 0xc
/* 04DD4C 8004D14C 44911000 */  mtc1  $s1, $f2
/* 04DD50 8004D150 00000000 */  nop   
/* 04DD54 8004D154 468010A0 */  cvt.s.w $f2, $f2
/* 04DD58 8004D158 46020083 */  div.s $f2, $f0, $f2
/* 04DD5C 8004D15C 3C014334 */  li    $at, 0x43340000 # 180.000000
/* 04DD60 8004D160 44810000 */  mtc1  $at, $f0
/* 04DD64 8004D164 00000000 */  nop   
/* 04DD68 8004D168 4600B03C */  c.lt.s $f22, $f0
/* 04DD6C 8004D16C 00000000 */  nop   
/* 04DD70 8004D170 00000000 */  nop   
/* 04DD74 8004D174 45020001 */  bc1fl .L8004D17C
/* 04DD78 8004D178 46001087 */   neg.s $f2, $f2
.L8004D17C:
/* 04DD7C 8004D17C 4480A000 */  mtc1  $zero, $f20
/* 04DD80 8004D180 8E02001C */  lw    $v0, 0x1c($s0)
/* 04DD84 8004D184 10400010 */  beqz  $v0, .L8004D1C8
/* 04DD88 8004D188 46001586 */   mov.s $f22, $f2
.L8004D18C:
/* 04DD8C 8004D18C 8E040018 */  lw    $a0, 0x18($s0)
/* 04DD90 8004D190 0C028354 */  jal   func_800A0D50
/* 04DD94 8004D194 02002821 */   addu  $a1, $s0, $zero
/* 04DD98 8004D198 4616A500 */  add.s $f20, $f20, $f22
/* 04DD9C 8004D19C 8E040018 */  lw    $a0, 0x18($s0)
/* 04DDA0 8004D1A0 4405A000 */  mfc1  $a1, $f20
/* 04DDA4 8004D1A4 0C00F545 */  jal   func_8003D514
/* 04DDA8 8004D1A8 00000000 */   nop   
/* 04DDAC 8004D1AC 8E02001C */  lw    $v0, 0x1c($s0)
/* 04DDB0 8004D1B0 2442FFFF */  addiu $v0, $v0, -1
/* 04DDB4 8004D1B4 0C018D6D */  jal   SleepVProcess
/* 04DDB8 8004D1B8 AE02001C */   sw    $v0, 0x1c($s0)
/* 04DDBC 8004D1BC 8E02001C */  lw    $v0, 0x1c($s0)
/* 04DDC0 8004D1C0 1440FFF2 */  bnez  $v0, .L8004D18C
/* 04DDC4 8004D1C4 00000000 */   nop   
.L8004D1C8:
/* 04DDC8 8004D1C8 0C017764 */  jal   EndProcess
/* 04DDCC 8004D1CC 00002021 */   addu  $a0, $zero, $zero
/* 04DDD0 8004D1D0 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04DDD4 8004D1D4 8FB10014 */  lw    $s1, 0x14($sp)
/* 04DDD8 8004D1D8 8FB00010 */  lw    $s0, 0x10($sp)
/* 04DDDC 8004D1DC D7B60028 */  ldc1  $f22, 0x28($sp)
/* 04DDE0 8004D1E0 D7B40020 */  ldc1  $f20, 0x20($sp)
/* 04DDE4 8004D1E4 03E00008 */  jr    $ra
/* 04DDE8 8004D1E8 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8004D1EC
/* 04DDEC 8004D1EC 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 04DDF0 8004D1F0 AFBF0028 */  sw    $ra, 0x28($sp)
/* 04DDF4 8004D1F4 AFB50024 */  sw    $s5, 0x24($sp)
/* 04DDF8 8004D1F8 AFB40020 */  sw    $s4, 0x20($sp)
/* 04DDFC 8004D1FC AFB3001C */  sw    $s3, 0x1c($sp)
/* 04DE00 8004D200 AFB20018 */  sw    $s2, 0x18($sp)
/* 04DE04 8004D204 AFB10014 */  sw    $s1, 0x14($sp)
/* 04DE08 8004D208 AFB00010 */  sw    $s0, 0x10($sp)
/* 04DE0C 8004D20C 00809021 */  addu  $s2, $a0, $zero
/* 04DE10 8004D210 00A09821 */  addu  $s3, $a1, $zero
/* 04DE14 8004D214 00C0A021 */  addu  $s4, $a2, $zero
/* 04DE18 8004D218 00E0A821 */  addu  $s5, $a3, $zero
/* 04DE1C 8004D21C 3C048005 */  lui   $a0, %hi(D_8004D0DC) # $a0, 0x8005
/* 04DE20 8004D220 2484D0DC */  addiu $a0, %lo(D_8004D0DC) # addiu $a0, $a0, -0x2f24
/* 04DE24 8004D224 24054001 */  li    $a1, 16385
/* 04DE28 8004D228 00003021 */  addu  $a2, $zero, $zero
/* 04DE2C 8004D22C 0C01770A */  jal   InitProcess
/* 04DE30 8004D230 24070050 */   li    $a3, 80
/* 04DE34 8004D234 00408821 */  addu  $s1, $v0, $zero
/* 04DE38 8004D238 8E240018 */  lw    $a0, 0x18($s1)
/* 04DE3C 8004D23C 0C016628 */  jal   Malloc
/* 04DE40 8004D240 24050020 */   li    $a1, 32
/* 04DE44 8004D244 00408021 */  addu  $s0, $v0, $zero
/* 04DE48 8004D248 AE30008C */  sw    $s0, 0x8c($s1)
/* 04DE4C 8004D24C 02002021 */  addu  $a0, $s0, $zero
/* 04DE50 8004D250 8E450000 */  lw    $a1, ($s2)
/* 04DE54 8004D254 8E470008 */  lw    $a3, 8($s2)
/* 04DE58 8004D258 0C028340 */  jal   func_800A0D00
/* 04DE5C 8004D25C 00003021 */   addu  $a2, $zero, $zero
/* 04DE60 8004D260 2604000C */  addiu $a0, $s0, 0xc
/* 04DE64 8004D264 8E650000 */  lw    $a1, ($s3)
/* 04DE68 8004D268 8E670008 */  lw    $a3, 8($s3)
/* 04DE6C 8004D26C 0C028340 */  jal   func_800A0D00
/* 04DE70 8004D270 00003021 */   addu  $a2, $zero, $zero
/* 04DE74 8004D274 AE140018 */  sw    $s4, 0x18($s0)
/* 04DE78 8004D278 AE15001C */  sw    $s5, 0x1c($s0)
/* 04DE7C 8004D27C 02201021 */  addu  $v0, $s1, $zero
/* 04DE80 8004D280 8FBF0028 */  lw    $ra, 0x28($sp)
/* 04DE84 8004D284 8FB50024 */  lw    $s5, 0x24($sp)
/* 04DE88 8004D288 8FB40020 */  lw    $s4, 0x20($sp)
/* 04DE8C 8004D28C 8FB3001C */  lw    $s3, 0x1c($sp)
/* 04DE90 8004D290 8FB20018 */  lw    $s2, 0x18($sp)
/* 04DE94 8004D294 8FB10014 */  lw    $s1, 0x14($sp)
/* 04DE98 8004D298 8FB00010 */  lw    $s0, 0x10($sp)
/* 04DE9C 8004D29C 03E00008 */  jr    $ra
/* 04DEA0 8004D2A0 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8004D2A4
/* 04DEA4 8004D2A4 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 04DEA8 8004D2A8 AFBF002C */  sw    $ra, 0x2c($sp)
/* 04DEAC 8004D2AC AFB20028 */  sw    $s2, 0x28($sp)
/* 04DEB0 8004D2B0 AFB10024 */  sw    $s1, 0x24($sp)
/* 04DEB4 8004D2B4 AFB00020 */  sw    $s0, 0x20($sp)
/* 04DEB8 8004D2B8 00A09021 */  addu  $s2, $a1, $zero
/* 04DEBC 8004D2BC 00C08021 */  addu  $s0, $a2, $zero
/* 04DEC0 8004D2C0 00042400 */  sll   $a0, $a0, 0x10
/* 04DEC4 8004D2C4 0C014AA3 */  jal   GetPlayerStruct
/* 04DEC8 8004D2C8 00042403 */   sra   $a0, $a0, 0x10
/* 04DECC 8004D2CC 00408821 */  addu  $s1, $v0, $zero
/* 04DED0 8004D2D0 00108400 */  sll   $s0, $s0, 0x10
/* 04DED4 8004D2D4 0C01307B */  jal   GetSpaceData
/* 04DED8 8004D2D8 00102403 */   sra   $a0, $s0, 0x10
/* 04DEDC 8004D2DC 8E260020 */  lw    $a2, 0x20($s1)
/* 04DEE0 8004D2E0 27A40010 */  addiu $a0, $sp, 0x10
/* 04DEE4 8004D2E4 24450004 */  addiu $a1, $v0, 4
/* 04DEE8 8004D2E8 0C0283A0 */  jal   func_800A0E80
/* 04DEEC 8004D2EC 24C6000C */   addiu $a2, $a2, 0xc
/* 04DEF0 8004D2F0 0C00F502 */  jal   func_8003D408
/* 04DEF4 8004D2F4 27A40010 */   addiu $a0, $sp, 0x10
/* 04DEF8 8004D2F8 8E260020 */  lw    $a2, 0x20($s1)
/* 04DEFC 8004D2FC 24C60018 */  addiu $a2, $a2, 0x18
/* 04DF00 8004D300 00C02021 */  addu  $a0, $a2, $zero
/* 04DF04 8004D304 27A50010 */  addiu $a1, $sp, 0x10
/* 04DF08 8004D308 0C01347B */  jal   func_8004D1EC
/* 04DF0C 8004D30C 02403821 */   addu  $a3, $s2, $zero
/* 04DF10 8004D310 8FBF002C */  lw    $ra, 0x2c($sp)
/* 04DF14 8004D314 8FB20028 */  lw    $s2, 0x28($sp)
/* 04DF18 8004D318 8FB10024 */  lw    $s1, 0x24($sp)
/* 04DF1C 8004D31C 8FB00020 */  lw    $s0, 0x20($sp)
/* 04DF20 8004D320 03E00008 */  jr    $ra
/* 04DF24 8004D324 27BD0030 */   addiu $sp, $sp, 0x30

D_8004D328:
/* 04DF28 8004D328 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 04DF2C 8004D32C AFBF0018 */  sw    $ra, 0x18($sp)
/* 04DF30 8004D330 AFB10014 */  sw    $s1, 0x14($sp)
/* 04DF34 8004D334 AFB00010 */  sw    $s0, 0x10($sp)
/* 04DF38 8004D338 0C018CEA */  jal   GetCurrentProcess
/* 04DF3C 8004D33C F7B40020 */   sdc1  $f20, 0x20($sp)
/* 04DF40 8004D340 8C50008C */  lw    $s0, 0x8c($v0)
/* 04DF44 8004D344 8E11001C */  lw    $s1, 0x1c($s0)
/* 04DF48 8004D348 12200022 */  beqz  $s1, .L8004D3D4
/* 04DF4C 8004D34C 00000000 */   nop   
/* 04DF50 8004D350 3C013F80 */  li    $at, 0x3F800000 # 1.000000
/* 04DF54 8004D354 4481A000 */  mtc1  $at, $f20
.L8004D358:
/* 04DF58 8004D358 8E040018 */  lw    $a0, 0x18($s0)
/* 04DF5C 8004D35C 2605000C */  addiu $a1, $s0, 0xc
/* 04DF60 8004D360 0C0283A0 */  jal   func_800A0E80
/* 04DF64 8004D364 02003021 */   addu  $a2, $s0, $zero
/* 04DF68 8004D368 44911000 */  mtc1  $s1, $f2
/* 04DF6C 8004D36C 00000000 */  nop   
/* 04DF70 8004D370 468010A0 */  cvt.s.w $f2, $f2
/* 04DF74 8004D374 4602A083 */  div.s $f2, $f20, $f2
/* 04DF78 8004D378 8E02001C */  lw    $v0, 0x1c($s0)
/* 04DF7C 8004D37C 2442FFFF */  addiu $v0, $v0, -1
/* 04DF80 8004D380 44820000 */  mtc1  $v0, $f0
/* 04DF84 8004D384 00000000 */  nop   
/* 04DF88 8004D388 46800020 */  cvt.s.w $f0, $f0
/* 04DF8C 8004D38C 46001082 */  mul.s $f2, $f2, $f0
/* 04DF90 8004D390 8E040018 */  lw    $a0, 0x18($s0)
/* 04DF94 8004D394 4602A081 */  sub.s $f2, $f20, $f2
/* 04DF98 8004D398 44051000 */  mfc1  $a1, $f2
/* 04DF9C 8004D39C 00000000 */  nop   
/* 04DFA0 8004D3A0 0C0283C0 */  jal   func_800A0F00
/* 04DFA4 8004D3A4 00803021 */   addu  $a2, $a0, $zero
/* 04DFA8 8004D3A8 8E040018 */  lw    $a0, 0x18($s0)
/* 04DFAC 8004D3AC 00802821 */  addu  $a1, $a0, $zero
/* 04DFB0 8004D3B0 0C028380 */  jal   func_800A0E00
/* 04DFB4 8004D3B4 02003021 */   addu  $a2, $s0, $zero
/* 04DFB8 8004D3B8 8E02001C */  lw    $v0, 0x1c($s0)
/* 04DFBC 8004D3BC 2442FFFF */  addiu $v0, $v0, -1
/* 04DFC0 8004D3C0 0C018D6D */  jal   SleepVProcess
/* 04DFC4 8004D3C4 AE02001C */   sw    $v0, 0x1c($s0)
/* 04DFC8 8004D3C8 8E02001C */  lw    $v0, 0x1c($s0)
/* 04DFCC 8004D3CC 1440FFE2 */  bnez  $v0, .L8004D358
/* 04DFD0 8004D3D0 00000000 */   nop   
.L8004D3D4:
/* 04DFD4 8004D3D4 0C017764 */  jal   EndProcess
/* 04DFD8 8004D3D8 00002021 */   addu  $a0, $zero, $zero
/* 04DFDC 8004D3DC 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04DFE0 8004D3E0 8FB10014 */  lw    $s1, 0x14($sp)
/* 04DFE4 8004D3E4 8FB00010 */  lw    $s0, 0x10($sp)
/* 04DFE8 8004D3E8 D7B40020 */  ldc1  $f20, 0x20($sp)
/* 04DFEC 8004D3EC 03E00008 */  jr    $ra
/* 04DFF0 8004D3F0 27BD0028 */   addiu $sp, $sp, 0x28

glabel func_8004D3F4
/* 04DFF4 8004D3F4 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 04DFF8 8004D3F8 AFBF0024 */  sw    $ra, 0x24($sp)
/* 04DFFC 8004D3FC AFB40020 */  sw    $s4, 0x20($sp)
/* 04E000 8004D400 AFB3001C */  sw    $s3, 0x1c($sp)
/* 04E004 8004D404 AFB20018 */  sw    $s2, 0x18($sp)
/* 04E008 8004D408 AFB10014 */  sw    $s1, 0x14($sp)
/* 04E00C 8004D40C AFB00010 */  sw    $s0, 0x10($sp)
/* 04E010 8004D410 00808821 */  addu  $s1, $a0, $zero
/* 04E014 8004D414 00A09021 */  addu  $s2, $a1, $zero
/* 04E018 8004D418 00C09821 */  addu  $s3, $a2, $zero
/* 04E01C 8004D41C 00E0A021 */  addu  $s4, $a3, $zero
/* 04E020 8004D420 3C048005 */  lui   $a0, %hi(D_8004D328) # $a0, 0x8005
/* 04E024 8004D424 2484D328 */  addiu $a0, %lo(D_8004D328) # addiu $a0, $a0, -0x2cd8
/* 04E028 8004D428 24054001 */  li    $a1, 16385
/* 04E02C 8004D42C 00003021 */  addu  $a2, $zero, $zero
/* 04E030 8004D430 0C01770A */  jal   InitProcess
/* 04E034 8004D434 24070050 */   li    $a3, 80
/* 04E038 8004D438 00408021 */  addu  $s0, $v0, $zero
/* 04E03C 8004D43C 8E040018 */  lw    $a0, 0x18($s0)
/* 04E040 8004D440 0C016628 */  jal   Malloc
/* 04E044 8004D444 24050020 */   li    $a1, 32
/* 04E048 8004D448 AE02008C */  sw    $v0, 0x8c($s0)
/* 04E04C 8004D44C 8E230000 */  lw    $v1, ($s1)
/* 04E050 8004D450 8E240004 */  lw    $a0, 4($s1)
/* 04E054 8004D454 8E250008 */  lw    $a1, 8($s1)
/* 04E058 8004D458 AC430000 */  sw    $v1, ($v0)
/* 04E05C 8004D45C AC440004 */  sw    $a0, 4($v0)
/* 04E060 8004D460 AC450008 */  sw    $a1, 8($v0)
/* 04E064 8004D464 8E430000 */  lw    $v1, ($s2)
/* 04E068 8004D468 8E440004 */  lw    $a0, 4($s2)
/* 04E06C 8004D46C 8E450008 */  lw    $a1, 8($s2)
/* 04E070 8004D470 AC43000C */  sw    $v1, 0xc($v0)
/* 04E074 8004D474 AC440010 */  sw    $a0, 0x10($v0)
/* 04E078 8004D478 AC450014 */  sw    $a1, 0x14($v0)
/* 04E07C 8004D47C AC530018 */  sw    $s3, 0x18($v0)
/* 04E080 8004D480 AC54001C */  sw    $s4, 0x1c($v0)
/* 04E084 8004D484 02001021 */  addu  $v0, $s0, $zero
/* 04E088 8004D488 8FBF0024 */  lw    $ra, 0x24($sp)
/* 04E08C 8004D48C 8FB40020 */  lw    $s4, 0x20($sp)
/* 04E090 8004D490 8FB3001C */  lw    $s3, 0x1c($sp)
/* 04E094 8004D494 8FB20018 */  lw    $s2, 0x18($sp)
/* 04E098 8004D498 8FB10014 */  lw    $s1, 0x14($sp)
/* 04E09C 8004D49C 8FB00010 */  lw    $s0, 0x10($sp)
/* 04E0A0 8004D4A0 03E00008 */  jr    $ra
/* 04E0A4 8004D4A4 27BD0028 */   addiu $sp, $sp, 0x28

glabel func_8004D4A8
/* 04E0A8 8004D4A8 27BDFFB8 */  addiu $sp, $sp, -0x48
/* 04E0AC 8004D4AC AFBF0040 */  sw    $ra, 0x40($sp)
/* 04E0B0 8004D4B0 AFB3003C */  sw    $s3, 0x3c($sp)
/* 04E0B4 8004D4B4 AFB20038 */  sw    $s2, 0x38($sp)
/* 04E0B8 8004D4B8 AFB10034 */  sw    $s1, 0x34($sp)
/* 04E0BC 8004D4BC AFB00030 */  sw    $s0, 0x30($sp)
/* 04E0C0 8004D4C0 00A09821 */  addu  $s3, $a1, $zero
/* 04E0C4 8004D4C4 00048400 */  sll   $s0, $a0, 0x10
/* 04E0C8 8004D4C8 00108403 */  sra   $s0, $s0, 0x10
/* 04E0CC 8004D4CC 0C014AA3 */  jal   GetPlayerStruct
/* 04E0D0 8004D4D0 02002021 */   addu  $a0, $s0, $zero
/* 04E0D4 8004D4D4 00409021 */  addu  $s2, $v0, $zero
/* 04E0D8 8004D4D8 9644000E */  lhu   $a0, 0xe($s2)
/* 04E0DC 8004D4DC 0C013081 */  jal   GetAbsSpaceIndexFromChainSpaceIndex
/* 04E0E0 8004D4E0 96450010 */   lhu   $a1, 0x10($s2)
/* 04E0E4 8004D4E4 00021400 */  sll   $v0, $v0, 0x10
/* 04E0E8 8004D4E8 02002021 */  addu  $a0, $s0, $zero
/* 04E0EC 8004D4EC 00022C03 */  sra   $a1, $v0, 0x10
/* 04E0F0 8004D4F0 0C0132DC */  jal   func_8004CB70
/* 04E0F4 8004D4F4 27A60010 */   addiu $a2, $sp, 0x10
/* 04E0F8 8004D4F8 96440012 */  lhu   $a0, 0x12($s2)
/* 04E0FC 8004D4FC 0C013081 */  jal   GetAbsSpaceIndexFromChainSpaceIndex
/* 04E100 8004D500 96450014 */   lhu   $a1, 0x14($s2)
/* 04E104 8004D504 00021400 */  sll   $v0, $v0, 0x10
/* 04E108 8004D508 27B10020 */  addiu $s1, $sp, 0x20
/* 04E10C 8004D50C 02002021 */  addu  $a0, $s0, $zero
/* 04E110 8004D510 00022C03 */  sra   $a1, $v0, 0x10
/* 04E114 8004D514 0C0132DC */  jal   func_8004CB70
/* 04E118 8004D518 02203021 */   addu  $a2, $s1, $zero
/* 04E11C 8004D51C 8E460020 */  lw    $a2, 0x20($s2)
/* 04E120 8004D520 27A40010 */  addiu $a0, $sp, 0x10
/* 04E124 8004D524 02202821 */  addu  $a1, $s1, $zero
/* 04E128 8004D528 0C013334 */  jal   func_8004CCD0
/* 04E12C 8004D52C 24C60018 */   addiu $a2, $a2, 0x18
/* 04E130 8004D530 8E460020 */  lw    $a2, 0x20($s2)
/* 04E134 8004D534 27A40010 */  addiu $a0, $sp, 0x10
/* 04E138 8004D538 02202821 */  addu  $a1, $s1, $zero
/* 04E13C 8004D53C 24C6000C */  addiu $a2, $a2, 0xc
/* 04E140 8004D540 0C0134FD */  jal   func_8004D3F4
/* 04E144 8004D544 02603821 */   addu  $a3, $s3, $zero
/* 04E148 8004D548 0C018CEA */  jal   GetCurrentProcess
/* 04E14C 8004D54C 00408021 */   addu  $s0, $v0, $zero
/* 04E150 8004D550 00402021 */  addu  $a0, $v0, $zero
/* 04E154 8004D554 0C018C9C */  jal   LinkChildProcess
/* 04E158 8004D558 02002821 */   addu  $a1, $s0, $zero
/* 04E15C 8004D55C 0C018CD6 */  jal   WaitForChildProcess
/* 04E160 8004D560 00000000 */   nop   
/* 04E164 8004D564 8FBF0040 */  lw    $ra, 0x40($sp)
/* 04E168 8004D568 8FB3003C */  lw    $s3, 0x3c($sp)
/* 04E16C 8004D56C 8FB20038 */  lw    $s2, 0x38($sp)
/* 04E170 8004D570 8FB10034 */  lw    $s1, 0x34($sp)
/* 04E174 8004D574 8FB00030 */  lw    $s0, 0x30($sp)
/* 04E178 8004D578 03E00008 */  jr    $ra
/* 04E17C 8004D57C 27BD0048 */   addiu $sp, $sp, 0x48

D_8004D580:
/* 04E180 8004D580 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 04E184 8004D584 AFBF0018 */  sw    $ra, 0x18($sp)
/* 04E188 8004D588 AFB10014 */  sw    $s1, 0x14($sp)
/* 04E18C 8004D58C AFB00010 */  sw    $s0, 0x10($sp)
/* 04E190 8004D590 0C018CEA */  jal   GetCurrentProcess
/* 04E194 8004D594 F7B40020 */   sdc1  $f20, 0x20($sp)
/* 04E198 8004D598 8C50008C */  lw    $s0, 0x8c($v0)
/* 04E19C 8004D59C C614001C */  lwc1  $f20, 0x1c($s0)
/* 04E1A0 8004D5A0 2611000C */  addiu $s1, $s0, 0xc
/* 04E1A4 8004D5A4 02002021 */  addu  $a0, $s0, $zero
glabel func_8004D5A8
/* 04E1A8 8004D5A8 0C0284F0 */  jal   func_800A13C0
/* 04E1AC 8004D5AC 02202821 */   addu  $a1, $s1, $zero
/* 04E1B0 8004D5B0 4614003C */  c.lt.s $f0, $f20
/* 04E1B4 8004D5B4 00000000 */  nop   
/* 04E1B8 8004D5B8 00000000 */  nop   
/* 04E1BC 8004D5BC 45010017 */  bc1t  .L8004D61C
/* 04E1C0 8004D5C0 02202821 */   addu  $a1, $s1, $zero
/* 04E1C4 8004D5C4 8E040018 */  lw    $a0, 0x18($s0)
/* 04E1C8 8004D5C8 0C0283A0 */  jal   func_800A0E80
/* 04E1CC 8004D5CC 02003021 */   addu  $a2, $s0, $zero
/* 04E1D0 8004D5D0 8E040018 */  lw    $a0, 0x18($s0)
/* 04E1D4 8004D5D4 0C00F502 */  jal   func_8003D408
/* 04E1D8 8004D5D8 00000000 */   nop   
/* 04E1DC 8004D5DC 8E040018 */  lw    $a0, 0x18($s0)
/* 04E1E0 8004D5E0 4405A000 */  mfc1  $a1, $f20
/* 04E1E4 8004D5E4 00000000 */  nop   
/* 04E1E8 8004D5E8 0C0283C0 */  jal   func_800A0F00
/* 04E1EC 8004D5EC 00803021 */   addu  $a2, $a0, $zero
/* 04E1F0 8004D5F0 8E040018 */  lw    $a0, 0x18($s0)
/* 04E1F4 8004D5F4 00802821 */  addu  $a1, $a0, $zero
/* 04E1F8 8004D5F8 0C028380 */  jal   func_800A0E00
/* 04E1FC 8004D5FC 02003021 */   addu  $a2, $s0, $zero
/* 04E200 8004D600 8E050018 */  lw    $a1, 0x18($s0)
/* 04E204 8004D604 0C028354 */  jal   func_800A0D50
/* 04E208 8004D608 02002021 */   addu  $a0, $s0, $zero
/* 04E20C 8004D60C 0C018D6D */  jal   SleepVProcess
/* 04E210 8004D610 00000000 */   nop   
/* 04E214 8004D614 0801356A */  j     func_8004D5A8
/* 04E218 8004D618 02002021 */   addu  $a0, $s0, $zero

.L8004D61C:
/* 04E21C 8004D61C 8E040018 */  lw    $a0, 0x18($s0)
/* 04E220 8004D620 0C028354 */  jal   func_800A0D50
/* 04E224 8004D624 2605000C */   addiu $a1, $s0, 0xc
/* 04E228 8004D628 0C017764 */  jal   EndProcess
/* 04E22C 8004D62C 00002021 */   addu  $a0, $zero, $zero
/* 04E230 8004D630 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04E234 8004D634 8FB10014 */  lw    $s1, 0x14($sp)
/* 04E238 8004D638 8FB00010 */  lw    $s0, 0x10($sp)
/* 04E23C 8004D63C D7B40020 */  ldc1  $f20, 0x20($sp)
/* 04E240 8004D640 03E00008 */  jr    $ra
/* 04E244 8004D644 27BD0028 */   addiu $sp, $sp, 0x28

glabel func_8004D648
/* 04E248 8004D648 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 04E24C 8004D64C AFBF0020 */  sw    $ra, 0x20($sp)
/* 04E250 8004D650 AFB3001C */  sw    $s3, 0x1c($sp)
/* 04E254 8004D654 AFB20018 */  sw    $s2, 0x18($sp)
/* 04E258 8004D658 AFB10014 */  sw    $s1, 0x14($sp)
/* 04E25C 8004D65C AFB00010 */  sw    $s0, 0x10($sp)
/* 04E260 8004D660 F7B40028 */  sdc1  $f20, 0x28($sp)
/* 04E264 8004D664 00808821 */  addu  $s1, $a0, $zero
/* 04E268 8004D668 00A09021 */  addu  $s2, $a1, $zero
/* 04E26C 8004D66C 00C09821 */  addu  $s3, $a2, $zero
/* 04E270 8004D670 4487A000 */  mtc1  $a3, $f20
/* 04E274 8004D674 3C048005 */  lui   $a0, %hi(D_8004D580) # $a0, 0x8005
/* 04E278 8004D678 2484D580 */  addiu $a0, %lo(D_8004D580) # addiu $a0, $a0, -0x2a80
/* 04E27C 8004D67C 24054001 */  li    $a1, 16385
/* 04E280 8004D680 00003021 */  addu  $a2, $zero, $zero
/* 04E284 8004D684 0C01770A */  jal   InitProcess
/* 04E288 8004D688 24070050 */   li    $a3, 80
/* 04E28C 8004D68C 00408021 */  addu  $s0, $v0, $zero
/* 04E290 8004D690 8E040018 */  lw    $a0, 0x18($s0)
/* 04E294 8004D694 0C016628 */  jal   Malloc
/* 04E298 8004D698 24050020 */   li    $a1, 32
/* 04E29C 8004D69C AE02008C */  sw    $v0, 0x8c($s0)
/* 04E2A0 8004D6A0 8E230000 */  lw    $v1, ($s1)
/* 04E2A4 8004D6A4 8E240004 */  lw    $a0, 4($s1)
/* 04E2A8 8004D6A8 8E250008 */  lw    $a1, 8($s1)
/* 04E2AC 8004D6AC AC430000 */  sw    $v1, ($v0)
/* 04E2B0 8004D6B0 AC440004 */  sw    $a0, 4($v0)
/* 04E2B4 8004D6B4 AC450008 */  sw    $a1, 8($v0)
/* 04E2B8 8004D6B8 8E430000 */  lw    $v1, ($s2)
/* 04E2BC 8004D6BC 8E440004 */  lw    $a0, 4($s2)
/* 04E2C0 8004D6C0 8E450008 */  lw    $a1, 8($s2)
/* 04E2C4 8004D6C4 AC43000C */  sw    $v1, 0xc($v0)
/* 04E2C8 8004D6C8 AC440010 */  sw    $a0, 0x10($v0)
/* 04E2CC 8004D6CC AC450014 */  sw    $a1, 0x14($v0)
/* 04E2D0 8004D6D0 AC530018 */  sw    $s3, 0x18($v0)
/* 04E2D4 8004D6D4 E454001C */  swc1  $f20, 0x1c($v0)
/* 04E2D8 8004D6D8 02001021 */  addu  $v0, $s0, $zero
/* 04E2DC 8004D6DC 8FBF0020 */  lw    $ra, 0x20($sp)
/* 04E2E0 8004D6E0 8FB3001C */  lw    $s3, 0x1c($sp)
/* 04E2E4 8004D6E4 8FB20018 */  lw    $s2, 0x18($sp)
/* 04E2E8 8004D6E8 8FB10014 */  lw    $s1, 0x14($sp)
/* 04E2EC 8004D6EC 8FB00010 */  lw    $s0, 0x10($sp)
/* 04E2F0 8004D6F0 D7B40028 */  ldc1  $f20, 0x28($sp)
/* 04E2F4 8004D6F4 03E00008 */  jr    $ra
/* 04E2F8 8004D6F8 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8004D6FC
/* 04E2FC 8004D6FC 27BDFFB8 */  addiu $sp, $sp, -0x48
/* 04E300 8004D700 AFBF003C */  sw    $ra, 0x3c($sp)
/* 04E304 8004D704 AFB20038 */  sw    $s2, 0x38($sp)
/* 04E308 8004D708 AFB10034 */  sw    $s1, 0x34($sp)
/* 04E30C 8004D70C AFB00030 */  sw    $s0, 0x30($sp)
/* 04E310 8004D710 F7B40040 */  sdc1  $f20, 0x40($sp)
/* 04E314 8004D714 4485A000 */  mtc1  $a1, $f20
/* 04E318 8004D718 00048400 */  sll   $s0, $a0, 0x10
/* 04E31C 8004D71C 00108403 */  sra   $s0, $s0, 0x10
/* 04E320 8004D720 0C014AA3 */  jal   GetPlayerStruct
/* 04E324 8004D724 02002021 */   addu  $a0, $s0, $zero
/* 04E328 8004D728 00409021 */  addu  $s2, $v0, $zero
/* 04E32C 8004D72C 9644000E */  lhu   $a0, 0xe($s2)
/* 04E330 8004D730 0C013081 */  jal   GetAbsSpaceIndexFromChainSpaceIndex
/* 04E334 8004D734 96450010 */   lhu   $a1, 0x10($s2)
/* 04E338 8004D738 00021400 */  sll   $v0, $v0, 0x10
/* 04E33C 8004D73C 02002021 */  addu  $a0, $s0, $zero
/* 04E340 8004D740 00022C03 */  sra   $a1, $v0, 0x10
/* 04E344 8004D744 0C0132DC */  jal   func_8004CB70
/* 04E348 8004D748 27A60010 */   addiu $a2, $sp, 0x10
/* 04E34C 8004D74C 96440012 */  lhu   $a0, 0x12($s2)
/* 04E350 8004D750 0C013081 */  jal   GetAbsSpaceIndexFromChainSpaceIndex
/* 04E354 8004D754 96450014 */   lhu   $a1, 0x14($s2)
/* 04E358 8004D758 00021400 */  sll   $v0, $v0, 0x10
/* 04E35C 8004D75C 27B10020 */  addiu $s1, $sp, 0x20
/* 04E360 8004D760 02002021 */  addu  $a0, $s0, $zero
/* 04E364 8004D764 00022C03 */  sra   $a1, $v0, 0x10
/* 04E368 8004D768 0C0132DC */  jal   func_8004CB70
/* 04E36C 8004D76C 02203021 */   addu  $a2, $s1, $zero
/* 04E370 8004D770 8E460020 */  lw    $a2, 0x20($s2)
/* 04E374 8004D774 27A40010 */  addiu $a0, $sp, 0x10
/* 04E378 8004D778 02202821 */  addu  $a1, $s1, $zero
/* 04E37C 8004D77C 0C013334 */  jal   func_8004CCD0
/* 04E380 8004D780 24C60018 */   addiu $a2, $a2, 0x18
/* 04E384 8004D784 8E460020 */  lw    $a2, 0x20($s2)
/* 04E388 8004D788 27A40010 */  addiu $a0, $sp, 0x10
/* 04E38C 8004D78C 02202821 */  addu  $a1, $s1, $zero
/* 04E390 8004D790 4407A000 */  mfc1  $a3, $f20
/* 04E394 8004D794 00000000 */  nop   
/* 04E398 8004D798 0C013592 */  jal   func_8004D648
/* 04E39C 8004D79C 24C6000C */   addiu $a2, $a2, 0xc
/* 04E3A0 8004D7A0 0C018CEA */  jal   GetCurrentProcess
/* 04E3A4 8004D7A4 00408021 */   addu  $s0, $v0, $zero
/* 04E3A8 8004D7A8 00402021 */  addu  $a0, $v0, $zero
/* 04E3AC 8004D7AC 0C018C9C */  jal   LinkChildProcess
/* 04E3B0 8004D7B0 02002821 */   addu  $a1, $s0, $zero
/* 04E3B4 8004D7B4 0C018CD6 */  jal   WaitForChildProcess
/* 04E3B8 8004D7B8 00000000 */   nop   
/* 04E3BC 8004D7BC 8FBF003C */  lw    $ra, 0x3c($sp)
/* 04E3C0 8004D7C0 8FB20038 */  lw    $s2, 0x38($sp)
/* 04E3C4 8004D7C4 8FB10034 */  lw    $s1, 0x34($sp)
/* 04E3C8 8004D7C8 8FB00030 */  lw    $s0, 0x30($sp)
/* 04E3CC 8004D7CC D7B40040 */  ldc1  $f20, 0x40($sp)
/* 04E3D0 8004D7D0 03E00008 */  jr    $ra
/* 04E3D4 8004D7D4 27BD0048 */   addiu $sp, $sp, 0x48

SetPlayerOntoChain:
/* 04E3D8 8004D7D8 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 04E3DC 8004D7DC AFBF001C */  sw    $ra, 0x1c($sp)
/* 04E3E0 8004D7E0 AFB20018 */  sw    $s2, 0x18($sp)
/* 04E3E4 8004D7E4 AFB10014 */  sw    $s1, 0x14($sp)
/* 04E3E8 8004D7E8 AFB00010 */  sw    $s0, 0x10($sp)
/* 04E3EC 8004D7EC 00A08021 */  addu  $s0, $a1, $zero
/* 04E3F0 8004D7F0 02009021 */  addu  $s2, $s0, $zero
/* 04E3F4 8004D7F4 00C08821 */  addu  $s1, $a2, $zero
/* 04E3F8 8004D7F8 00042400 */  sll   $a0, $a0, 0x10
/* 04E3FC 8004D7FC 0C014AA3 */  jal   GetPlayerStruct
/* 04E400 8004D800 00042403 */   sra   $a0, $a0, 0x10
/* 04E404 8004D804 00108400 */  sll   $s0, $s0, 0x10
/* 04E408 8004D808 06000003 */  bltz  $s0, .L8004D818
/* 04E40C 8004D80C 00401821 */   addu  $v1, $v0, $zero
/* 04E410 8004D810 A472000E */  sh    $s2, 0xe($v1)
/* 04E414 8004D814 A4720012 */  sh    $s2, 0x12($v1)
.L8004D818:
/* 04E418 8004D818 00111400 */  sll   $v0, $s1, 0x10
/* 04E41C 8004D81C 04400003 */  bltz  $v0, .L8004D82C
/* 04E420 8004D820 26220001 */   addiu $v0, $s1, 1
/* 04E424 8004D824 A4710010 */  sh    $s1, 0x10($v1)
/* 04E428 8004D828 A4620014 */  sh    $v0, 0x14($v1)
.L8004D82C:
/* 04E42C 8004D82C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 04E430 8004D830 8FB20018 */  lw    $s2, 0x18($sp)
/* 04E434 8004D834 8FB10014 */  lw    $s1, 0x14($sp)
/* 04E438 8004D838 8FB00010 */  lw    $s0, 0x10($sp)
/* 04E43C 8004D83C 03E00008 */  jr    $ra
/* 04E440 8004D840 27BD0020 */   addiu $sp, $sp, 0x20

SetNextChainAndSpace:
/* 04E444 8004D844 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 04E448 8004D848 AFBF001C */  sw    $ra, 0x1c($sp)
/* 04E44C 8004D84C AFB20018 */  sw    $s2, 0x18($sp)
/* 04E450 8004D850 AFB10014 */  sw    $s1, 0x14($sp)
/* 04E454 8004D854 AFB00010 */  sw    $s0, 0x10($sp)
/* 04E458 8004D858 00A08021 */  addu  $s0, $a1, $zero
/* 04E45C 8004D85C 02009021 */  addu  $s2, $s0, $zero
/* 04E460 8004D860 00C08821 */  addu  $s1, $a2, $zero
/* 04E464 8004D864 00042400 */  sll   $a0, $a0, 0x10
/* 04E468 8004D868 0C014AA3 */  jal   GetPlayerStruct
/* 04E46C 8004D86C 00042403 */   sra   $a0, $a0, 0x10
/* 04E470 8004D870 00108400 */  sll   $s0, $s0, 0x10
/* 04E474 8004D874 06000002 */  bltz  $s0, .L8004D880
/* 04E478 8004D878 00401821 */   addu  $v1, $v0, $zero
/* 04E47C 8004D87C A4720012 */  sh    $s2, 0x12($v1)
.L8004D880:
/* 04E480 8004D880 00111400 */  sll   $v0, $s1, 0x10
/* 04E484 8004D884 04430001 */  bgezl $v0, .L8004D88C
/* 04E488 8004D888 A4710014 */   sh    $s1, 0x14($v1)
.L8004D88C:
/* 04E48C 8004D88C 8FBF001C */  lw    $ra, 0x1c($sp)
/* 04E490 8004D890 8FB20018 */  lw    $s2, 0x18($sp)
/* 04E494 8004D894 8FB10014 */  lw    $s1, 0x14($sp)
/* 04E498 8004D898 8FB00010 */  lw    $s0, 0x10($sp)
/* 04E49C 8004D89C 03E00008 */  jr    $ra
/* 04E4A0 8004D8A0 27BD0020 */   addiu $sp, $sp, 0x20

/* 04E4A4 8004D8A4 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 04E4A8 8004D8A8 AFBF0018 */  sw    $ra, 0x18($sp)
/* 04E4AC 8004D8AC AFB10014 */  sw    $s1, 0x14($sp)
/* 04E4B0 8004D8B0 AFB00010 */  sw    $s0, 0x10($sp)
/* 04E4B4 8004D8B4 3C11800F */  lui   $s1, %hi(D_800ED5C0) # $s1, 0x800f
/* 04E4B8 8004D8B8 2631D5C0 */  addiu $s1, %lo(D_800ED5C0) # addiu $s1, $s1, -0x2a40
/* 04E4BC 8004D8BC 8624001A */  lh    $a0, 0x1a($s1)
/* 04E4C0 8004D8C0 0C0165F7 */  jal   SetBoardFeatureEnabled
/* 04E4C4 8004D8C4 00008021 */   addu  $s0, $zero, $zero
/* 04E4C8 8004D8C8 0C0165F7 */  jal   SetBoardFeatureEnabled
/* 04E4CC 8004D8CC 2404004E */   li    $a0, 78
/* 04E4D0 8004D8D0 0C0165E6 */  jal   IsBoardFeatureDisabled
/* 04E4D4 8004D8D4 24040043 */   li    $a0, 67
/* 04E4D8 8004D8D8 1040000E */  beqz  $v0, .L8004D914
/* 04E4DC 8004D8DC 24020007 */   li    $v0, 7
/* 04E4E0 8004D8E0 3C03800F */  lui   $v1, %hi(D_800ED5C2) # $v1, 0x800f
/* 04E4E4 8004D8E4 8463D5C2 */  lh    $v1, %lo(D_800ED5C2)($v1)
/* 04E4E8 8004D8E8 54620006 */  bnel  $v1, $v0, .L8004D904
/* 04E4EC 8004D8EC 2404FFFE */   li    $a0, -2
/* 04E4F0 8004D8F0 8623000A */  lh    $v1, 0xa($s1)
/* 04E4F4 8004D8F4 24020006 */  li    $v0, 6
/* 04E4F8 8004D8F8 14620007 */  bne   $v1, $v0, .L8004D918
/* 04E4FC 8004D8FC 02001021 */   addu  $v0, $s0, $zero
/* 04E500 8004D900 2404FFFE */  li    $a0, -2
.L8004D904:
/* 04E504 8004D904 24050004 */  li    $a1, 4
/* 04E508 8004D908 0C0159CC */  jal   func_80056730
/* 04E50C 8004D90C 24060092 */   li    $a2, 146
/* 04E510 8004D910 24100001 */  li    $s0, 1
.L8004D914:
/* 04E514 8004D914 02001021 */  addu  $v0, $s0, $zero
.L8004D918:
/* 04E518 8004D918 8FBF0018 */  lw    $ra, 0x18($sp)
/* 04E51C 8004D91C 8FB10014 */  lw    $s1, 0x14($sp)
/* 04E520 8004D920 8FB00010 */  lw    $s0, 0x10($sp)
/* 04E524 8004D924 03E00008 */  jr    $ra
/* 04E528 8004D928 27BD0020 */   addiu $sp, $sp, 0x20

/* 04E52C 8004D92C 00000000 */  nop   
