# Mario Party (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "globals.inc"
.include "macros.inc"

MakePermHeap:
/* 03C280 8003B680 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C284 8003B684 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C288 8003B688 0C016620 */  jal   MakeHeap
/* 03C28C 8003B68C 00000000 */   nop   
/* 03C290 8003B690 3C01800D */  lui   $at, %hi(D_800D6030) # $at, 0x800d
/* 03C294 8003B694 AC226030 */  sw    $v0, %lo(D_800D6030)($at)
/* 03C298 8003B698 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C29C 8003B69C 03E00008 */  jr    $ra
/* 03C2A0 8003B6A0 27BD0018 */   addiu $sp, $sp, 0x18

MallocPerm:
/* 03C2A4 8003B6A4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C2A8 8003B6A8 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C2AC 8003B6AC 00802821 */  addu  $a1, $a0, $zero
/* 03C2B0 8003B6B0 3C04800D */  lui   $a0, %hi(D_800D6030) # $a0, 0x800d
/* 03C2B4 8003B6B4 0C016628 */  jal   Malloc
/* 03C2B8 8003B6B8 8C846030 */   lw    $a0, %lo(D_800D6030)($a0)
/* 03C2BC 8003B6BC 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C2C0 8003B6C0 03E00008 */  jr    $ra
/* 03C2C4 8003B6C4 27BD0018 */   addiu $sp, $sp, 0x18

FreePerm:
/* 03C2C8 8003B6C8 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C2CC 8003B6CC AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C2D0 8003B6D0 0C01664B */  jal   Free
/* 03C2D4 8003B6D4 00000000 */   nop   
/* 03C2D8 8003B6D8 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C2DC 8003B6DC 03E00008 */  jr    $ra
/* 03C2E0 8003B6E0 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8003B6E4
/* 03C2E4 8003B6E4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C2E8 8003B6E8 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C2EC 8003B6EC 00801021 */  addu  $v0, $a0, $zero
/* 03C2F0 8003B6F0 00A03021 */  addu  $a2, $a1, $zero
/* 03C2F4 8003B6F4 3C04800D */  lui   $a0, %hi(D_800D6030) # $a0, 0x800d
/* 03C2F8 8003B6F8 8C846030 */  lw    $a0, %lo(D_800D6030)($a0)
/* 03C2FC 8003B6FC 0C016677 */  jal   func_800599DC
/* 03C300 8003B700 00402821 */   addu  $a1, $v0, $zero
/* 03C304 8003B704 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C308 8003B708 03E00008 */  jr    $ra
/* 03C30C 8003B70C 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8003B710
/* 03C310 8003B710 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C314 8003B714 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C318 8003B718 3C04800D */  lui   $a0, %hi(D_800D6030) # $a0, 0x800d
/* 03C31C 8003B71C 0C0166A9 */  jal   func_80059AA4
/* 03C320 8003B720 8C846030 */   lw    $a0, %lo(D_800D6030)($a0)
/* 03C324 8003B724 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C328 8003B728 03E00008 */  jr    $ra
/* 03C32C 8003B72C 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8003B730
/* 03C330 8003B730 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C334 8003B734 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C338 8003B738 3C04800D */  lui   $a0, %hi(D_800D6030) # $a0, 0x800d
/* 03C33C 8003B73C 0C0166B6 */  jal   func_80059AD8
/* 03C340 8003B740 8C846030 */   lw    $a0, %lo(D_800D6030)($a0)
/* 03C344 8003B744 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C348 8003B748 03E00008 */  jr    $ra
/* 03C34C 8003B74C 27BD0018 */   addiu $sp, $sp, 0x18

MakeTempHeap:
/* 03C350 8003B750 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C354 8003B754 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C358 8003B758 0C016620 */  jal   MakeHeap
/* 03C35C 8003B75C 00000000 */   nop   
/* 03C360 8003B760 3C01800D */  lui   $at, %hi(D_800D6040) # $at, 0x800d
/* 03C364 8003B764 AC226040 */  sw    $v0, %lo(D_800D6040)($at)
/* 03C368 8003B768 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C36C 8003B76C 03E00008 */  jr    $ra
/* 03C370 8003B770 27BD0018 */   addiu $sp, $sp, 0x18

MallocTemp:
/* 03C374 8003B774 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C378 8003B778 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C37C 8003B77C 00802821 */  addu  $a1, $a0, $zero
/* 03C380 8003B780 3C04800D */  lui   $a0, %hi(D_800D6040) # $a0, 0x800d
/* 03C384 8003B784 0C016628 */  jal   Malloc
/* 03C388 8003B788 8C846040 */   lw    $a0, %lo(D_800D6040)($a0)
/* 03C38C 8003B78C 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C390 8003B790 03E00008 */  jr    $ra
/* 03C394 8003B794 27BD0018 */   addiu $sp, $sp, 0x18

FreeTemp:
/* 03C398 8003B798 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C39C 8003B79C AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C3A0 8003B7A0 0C01664B */  jal   Free
/* 03C3A4 8003B7A4 00000000 */   nop   
/* 03C3A8 8003B7A8 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C3AC 8003B7AC 03E00008 */  jr    $ra
/* 03C3B0 8003B7B0 27BD0018 */   addiu $sp, $sp, 0x18

/* 03C3B4 8003B7B4 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C3B8 8003B7B8 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C3BC 8003B7BC 00801021 */  addu  $v0, $a0, $zero
/* 03C3C0 8003B7C0 00A03021 */  addu  $a2, $a1, $zero
/* 03C3C4 8003B7C4 3C04800D */  lui   $a0, %hi(D_800D6040) # $a0, 0x800d
/* 03C3C8 8003B7C8 8C846040 */  lw    $a0, %lo(D_800D6040)($a0)
/* 03C3CC 8003B7CC 0C016677 */  jal   func_800599DC
/* 03C3D0 8003B7D0 00402821 */   addu  $a1, $v0, $zero
/* 03C3D4 8003B7D4 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C3D8 8003B7D8 03E00008 */  jr    $ra
/* 03C3DC 8003B7DC 27BD0018 */   addiu $sp, $sp, 0x18

/* 03C3E0 8003B7E0 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C3E4 8003B7E4 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C3E8 8003B7E8 3C04800D */  lui   $a0, %hi(D_800D6040) # $a0, 0x800d
/* 03C3EC 8003B7EC 0C0166A9 */  jal   func_80059AA4
/* 03C3F0 8003B7F0 8C846040 */   lw    $a0, %lo(D_800D6040)($a0)
/* 03C3F4 8003B7F4 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C3F8 8003B7F8 03E00008 */  jr    $ra
/* 03C3FC 8003B7FC 27BD0018 */   addiu $sp, $sp, 0x18

/* 03C400 8003B800 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 03C404 8003B804 AFBF0010 */  sw    $ra, 0x10($sp)
/* 03C408 8003B808 3C04800D */  lui   $a0, %hi(D_800D6040) # $a0, 0x800d
/* 03C40C 8003B80C 0C0166B6 */  jal   func_80059AD8
/* 03C410 8003B810 8C846040 */   lw    $a0, %lo(D_800D6040)($a0)
/* 03C414 8003B814 8FBF0010 */  lw    $ra, 0x10($sp)
/* 03C418 8003B818 03E00008 */  jr    $ra
/* 03C41C 8003B81C 27BD0018 */   addiu $sp, $sp, 0x18