# Mario Party (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "globals.inc"
.include "macros.inc"

glabel D_8001A0F0
/* 01ACF0 8001A0F0 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 01ACF4 8001A0F4 AFBF0020 */  sw    $ra, 0x20($sp)
/* 01ACF8 8001A0F8 AFB1001C */  sw    $s1, 0x1c($sp)
/* 01ACFC 8001A0FC 0C018D6D */  jal   SleepVProcess
/* 01AD00 8001A100 AFB00018 */   sw    $s0, 0x18($sp)
/* 01AD04 8001A104 3C03800F */  lui   $v1, %hi(D_800F33EC) # $v1, 0x800f
/* 01AD08 8001A108 246333EC */  addiu $v1, %lo(D_800F33EC) # addiu $v1, $v1, 0x33ec
/* 01AD0C 8001A10C 3C0143A2 */  li    $at, 0x43A20000 # 324.000000
/* 01AD10 8001A110 34218000 */  ori   $at, (0x43A28000 & 0xFFFF) # ori $at, $at, 0x8000
/* 01AD14 8001A114 44810000 */  mtc1  $at, $f0
/* 01AD18 8001A118 00000000 */  nop   
/* 01AD1C 8001A11C E4600000 */  swc1  $f0, ($v1)
/* 01AD20 8001A120 AC600004 */  sw    $zero, 4($v1)
/* 01AD24 8001A124 AC600008 */  sw    $zero, 8($v1)
/* 01AD28 8001A128 3C01450C */  li    $at, 0x450C0000 # 2240.000000
/* 01AD2C 8001A12C 3421A000 */  ori   $at, (0x450CA000 & 0xFFFF) # ori $at, $at, 0xa000
/* 01AD30 8001A130 44810000 */  mtc1  $at, $f0
/* 01AD34 8001A134 3C01800F */  lui   $at, %hi(D_800EE98C) # $at, 0x800f
/* 01AD38 8001A138 E420E98C */  swc1  $f0, %lo(D_800EE98C)($at)
/* 01AD3C 8001A13C 3C02800F */  lui   $v0, %hi(D_800F6524) # $v0, 0x800f
/* 01AD40 8001A140 24426524 */  addiu $v0, %lo(D_800F6524) # addiu $v0, $v0, 0x6524
/* 01AD44 8001A144 C4600004 */  lwc1  $f0, 4($v1)
/* 01AD48 8001A148 E4400008 */  swc1  $f0, 8($v0)
/* 01AD4C 8001A14C E4400004 */  swc1  $f0, 4($v0)
/* 01AD50 8001A150 E4400000 */  swc1  $f0, ($v0)
/* 01AD54 8001A154 00002021 */  addu  $a0, $zero, $zero
/* 01AD58 8001A158 3C0143A2 */  li    $at, 0x43A20000 # 324.000000
/* 01AD5C 8001A15C 34218000 */  ori   $at, (0x43A28000 & 0xFFFF) # ori $at, $at, 0x8000
/* 01AD60 8001A160 44812000 */  mtc1  $at, $f4
/* 01AD64 8001A164 3C07800F */  lui   $a3, %hi(D_800F6550) # $a3, 0x800f
/* 01AD68 8001A168 24E76550 */  addiu $a3, %lo(D_800F6550) # addiu $a3, $a3, 0x6550
/* 01AD6C 8001A16C 44800000 */  mtc1  $zero, $f0
/* 01AD70 8001A170 3C06800F */  lui   $a2, %hi(D_800ED6C0) # $a2, 0x800f
/* 01AD74 8001A174 24C6D6C0 */  addiu $a2, %lo(D_800ED6C0) # addiu $a2, $a2, -0x2940
/* 01AD78 8001A178 3C01450C */  li    $at, 0x450C0000 # 2240.000000
/* 01AD7C 8001A17C 3421A000 */  ori   $at, (0x450CA000 & 0xFFFF) # ori $at, $at, 0xa000
/* 01AD80 8001A180 44811000 */  mtc1  $at, $f2
/* 01AD84 8001A184 3C05800F */  lui   $a1, %hi(D_800F52F8) # $a1, 0x800f
/* 01AD88 8001A188 24A552F8 */  addiu $a1, %lo(D_800F52F8) # addiu $a1, $a1, 0x52f8
/* 01AD8C 8001A18C 00041840 */  sll   $v1, $a0, 1
.L8001A190:
/* 01AD90 8001A190 00641821 */  addu  $v1, $v1, $a0
/* 01AD94 8001A194 00031880 */  sll   $v1, $v1, 2
/* 01AD98 8001A198 3C01800F */  lui   $at, 0x800f
/* 01AD9C 8001A19C 00230821 */  addu  $at, $at, $v1
/* 01ADA0 8001A1A0 E4246550 */  swc1  $f4, 0x6550($at)
/* 01ADA4 8001A1A4 00671021 */  addu  $v0, $v1, $a3
/* 01ADA8 8001A1A8 E4400008 */  swc1  $f0, 8($v0)
/* 01ADAC 8001A1AC 3C01800F */  lui   $at, 0x800f
/* 01ADB0 8001A1B0 00230821 */  addu  $at, $at, $v1
/* 01ADB4 8001A1B4 E4206554 */  swc1  $f0, 0x6554($at)
/* 01ADB8 8001A1B8 00041080 */  sll   $v0, $a0, 2
/* 01ADBC 8001A1BC 00461021 */  addu  $v0, $v0, $a2
/* 01ADC0 8001A1C0 E4420000 */  swc1  $f2, ($v0)
/* 01ADC4 8001A1C4 00651021 */  addu  $v0, $v1, $a1
/* 01ADC8 8001A1C8 E4400008 */  swc1  $f0, 8($v0)
/* 01ADCC 8001A1CC E4400004 */  swc1  $f0, 4($v0)
/* 01ADD0 8001A1D0 3C01800F */  lui   $at, 0x800f
/* 01ADD4 8001A1D4 00230821 */  addu  $at, $at, $v1
/* 01ADD8 8001A1D8 E42052F8 */  swc1  $f0, 0x52f8($at)
/* 01ADDC 8001A1DC 24840001 */  addiu $a0, $a0, 1
/* 01ADE0 8001A1E0 28820004 */  slti  $v0, $a0, 4
/* 01ADE4 8001A1E4 1440FFEA */  bnez  $v0, .L8001A190
/* 01ADE8 8001A1E8 00041840 */   sll   $v1, $a0, 1
/* 01ADEC 8001A1EC 24020003 */  li    $v0, 3
/* 01ADF0 8001A1F0 3C01800F */  lui   $at, %hi(D_800F3705) # $at, 0x800f
/* 01ADF4 8001A1F4 A0223705 */  sb    $v0, %lo(D_800F3705)($at)
/* 01ADF8 8001A1F8 24021000 */  li    $v0, 4096
/* 01ADFC 8001A1FC 3C01800F */  lui   $at, %hi(D_800F3F30) # $at, 0x800f
/* 01AE00 8001A200 A4223F30 */  sh    $v0, %lo(D_800F3F30)($at)
/* 01AE04 8001A204 24022004 */  li    $v0, 8196
/* 01AE08 8001A208 3C01800F */  lui   $at, %hi(D_800ED726) # $at, 0x800f
/* 01AE0C 8001A20C A422D726 */  sh    $v0, %lo(D_800ED726)($at)
/* 01AE10 8001A210 24020180 */  li    $v0, 384
/* 01AE14 8001A214 3C01800F */  lui   $at, %hi(D_800F64EC) # $at, 0x800f
/* 01AE18 8001A218 0C01C864 */  jal   func_80072190
/* 01AE1C 8001A21C A42264EC */   sh    $v0, %lo(D_800F64EC)($at)
/* 01AE20 8001A220 3C06800F */  lui   $a2, %hi(D_800F3F30) # $a2, 0x800f
/* 01AE24 8001A224 94C63F30 */  lhu   $a2, %lo(D_800F3F30)($a2)
/* 01AE28 8001A228 3C07800F */  lui   $a3, %hi(D_800ED726) # $a3, 0x800f
/* 01AE2C 8001A22C 94E7D726 */  lhu   $a3, %lo(D_800ED726)($a3)
/* 01AE30 8001A230 3C02800F */  lui   $v0, %hi(D_800F64EC) # $v0, 0x800f
/* 01AE34 8001A234 944264EC */  lhu   $v0, %lo(D_800F64EC)($v0)
/* 01AE38 8001A238 AFA20010 */  sw    $v0, 0x10($sp)
/* 01AE3C 8001A23C 3C02800F */  lui   $v0, %hi(D_800F3705) # $v0, 0x800f
/* 01AE40 8001A240 90423705 */  lbu   $v0, %lo(D_800F3705)($v0)
/* 01AE44 8001A244 3C048004 */  lui   $a0, %hi(MallocPerm) # $a0, 0x8004
/* 01AE48 8001A248 2484B6A4 */  addiu $a0, %lo(MallocPerm) # addiu $a0, $a0, -0x495c
/* 01AE4C 8001A24C 3C058004 */  lui   $a1, %hi(FreePerm) # $a1, 0x8004
/* 01AE50 8001A250 24A5B6C8 */  addiu $a1, %lo(FreePerm) # addiu $a1, $a1, -0x4938
/* 01AE54 8001A254 0C008ED0 */  jal   func_80023B40
/* 01AE58 8001A258 AFA20014 */   sw    $v0, 0x14($sp)
/* 01AE5C 8001A25C 0C007490 */  jal   func_8001D240
/* 01AE60 8001A260 24040001 */   li    $a0, 1
/* 01AE64 8001A264 0C018850 */  jal   func_80062140
/* 01AE68 8001A268 00000000 */   nop   
/* 01AE6C 8001A26C 3C0400FD */  lui   $a0, %hi(D_00FCB860) # $a0, 0xfd
/* 01AE70 8001A270 0C016DB4 */  jal   func_8005B6D0
/* 01AE74 8001A274 2484B860 */   addiu $a0, %lo(D_00FCB860) # addiu $a0, $a0, -0x47a0
/* 01AE78 8001A278 0C00EDC4 */  jal   GetAllocatedPermHeapSize
/* 01AE7C 8001A27C 00000000 */   nop   
/* 01AE80 8001A280 3C048002 */  lui   $a0, %hi(D_8001A3DC) # $a0, 0x8002
/* 01AE84 8001A284 2484A3DC */  addiu $a0, %lo(D_8001A3DC) # addiu $a0, $a0, -0x5c24
/* 01AE88 8001A288 3405F000 */  li    $a1, 61440
/* 01AE8C 8001A28C 24063000 */  li    $a2, 12288
/* 01AE90 8001A290 0C018C51 */  jal   func_80063144
/* 01AE94 8001A294 00003821 */   addu  $a3, $zero, $zero
/* 01AE98 8001A298 3C01800F */  lui   $at, %hi(D_800F2BD0) # $at, 0x800f
/* 01AE9C 8001A29C AC222BD0 */  sw    $v0, %lo(D_800F2BD0)($at)
/* 01AEA0 8001A2A0 3C048002 */  lui   $a0, %hi(D_8001A428) # $a0, 0x8002
/* 01AEA4 8001A2A4 2484A428 */  addiu $a0, %lo(D_8001A428) # addiu $a0, $a0, -0x5bd8
/* 01AEA8 8001A2A8 24054000 */  li    $a1, 16384
/* 01AEAC 8001A2AC 24063000 */  li    $a2, 12288
/* 01AEB0 8001A2B0 0C018C51 */  jal   func_80063144
/* 01AEB4 8001A2B4 00003821 */   addu  $a3, $zero, $zero
/* 01AEB8 8001A2B8 3C048002 */  lui   $a0, %hi(D_8001A454) # $a0, 0x8002
/* 01AEBC 8001A2BC 2484A454 */  addiu $a0, %lo(D_8001A454) # addiu $a0, $a0, -0x5bac
/* 01AEC0 8001A2C0 24051000 */  li    $a1, 4096
/* 01AEC4 8001A2C4 24063000 */  li    $a2, 12288
/* 01AEC8 8001A2C8 0C018C51 */  jal   func_80063144
/* 01AECC 8001A2CC 00003821 */   addu  $a3, $zero, $zero
/* 01AED0 8001A2D0 3C01800F */  lui   $at, %hi(D_800F3700) # $at, 0x800f
/* 01AED4 8001A2D4 0C006926 */  jal   func_8001A498
/* 01AED8 8001A2D8 AC223700 */   sw    $v0, %lo(D_800F3700)($at)
/* 01AEDC 8001A2DC 0C016C31 */  jal   func_8005B0C4
/* 01AEE0 8001A2E0 00000000 */   nop   
/* 01AEE4 8001A2E4 0C002CAF */  jal   func_8000B2BC
/* 01AEE8 8001A2E8 00408021 */   addu  $s0, $v0, $zero
/* 01AEEC 8001A2EC 00408821 */  addu  $s1, $v0, $zero
/* 01AEF0 8001A2F0 24020001 */  li    $v0, 1
/* 01AEF4 8001A2F4 16020002 */  bne   $s0, $v0, .L8001A300
/* 01AEF8 8001A2F8 24040067 */   li    $a0, 103
/* 01AEFC 8001A2FC 24040068 */  li    $a0, 104
.L8001A300:
/* 01AF00 8001A300 00002821 */  addu  $a1, $zero, $zero
/* 01AF04 8001A304 0C0177D1 */  jal   func_8005DF44
/* 01AF08 8001A308 24060081 */   li    $a2, 129
/* 01AF0C 8001A30C 3C0401BC */  lui   $a0, %hi(D_01BB8460) # $a0, 0x1bc
/* 01AF10 8001A310 24848460 */  addiu $a0, %lo(D_01BB8460) # addiu $a0, $a0, -0x7ba0
/* 01AF14 8001A314 00002821 */  addu  $a1, $zero, $zero
/* 01AF18 8001A318 00003021 */  addu  $a2, $zero, $zero
/* 01AF1C 8001A31C 0C00430C */  jal   func_80010C30
/* 01AF20 8001A320 00003821 */   addu  $a3, $zero, $zero
/* 01AF24 8001A324 AFA00010 */  sw    $zero, 0x10($sp)
/* 01AF28 8001A328 3C040178 */  lui   $a0, %hi(D_01778BC0) # $a0, 0x178
/* 01AF2C 8001A32C 24848BC0 */  addiu $a0, %lo(D_01778BC0) # addiu $a0, $a0, -0x7440
/* 01AF30 8001A330 3C050183 */  lui   $a1, %hi(D_01832AE0) # $a1, 0x183
/* 01AF34 8001A334 24A52AE0 */  addiu $a1, %lo(D_01832AE0) # addiu $a1, $a1, 0x2ae0
/* 01AF38 8001A338 00003021 */  addu  $a2, $zero, $zero
/* 01AF3C 8001A33C 0C002FA6 */  jal   func_8000BE98
/* 01AF40 8001A340 00003821 */   addu  $a3, $zero, $zero
/* 01AF44 8001A344 24020001 */  li    $v0, 1
/* 01AF48 8001A348 3C01800C */  lui   $at, %hi(D_800C59A0) # $at, 0x800c
/* 01AF4C 8001A34C A42259A0 */  sh    $v0, %lo(D_800C59A0)($at)
/* 01AF50 8001A350 3C01800C */  lui   $at, %hi(D_800C599E) # $at, 0x800c
/* 01AF54 8001A354 A422599E */  sh    $v0, %lo(D_800C599E)($at)
/* 01AF58 8001A358 3C0201CF */  lui   $v0, %hi(D_01CECC60) # $v0, 0x1cf
/* 01AF5C 8001A35C 2442CC60 */  addiu $v0, %lo(D_01CECC60) # addiu $v0, $v0, -0x33a0
/* 01AF60 8001A360 AE220024 */  sw    $v0, 0x24($s1)
/* 01AF64 8001A364 3C0201CF */  lui   $v0, %hi(D_01CED490) # $v0, 0x1cf
/* 01AF68 8001A368 2442D490 */  addiu $v0, %lo(D_01CED490) # addiu $v0, $v0, -0x2b70
/* 01AF6C 8001A36C AE220028 */  sw    $v0, 0x28($s1)
/* 01AF70 8001A370 24020014 */  li    $v0, 20
/* 01AF74 8001A374 AE220040 */  sw    $v0, 0x40($s1)
/* 01AF78 8001A378 2404006E */  li    $a0, 110
/* 01AF7C 8001A37C 00002821 */  addu  $a1, $zero, $zero
/* 01AF80 8001A380 3C06802E */  lui   $a2, 0x802e
/* 01AF84 8001A384 0C002C03 */  jal   func_8000B00C
/* 01AF88 8001A388 3C070008 */   lui   $a3, 8
/* 01AF8C 8001A38C 0C0165E6 */  jal   IsBoardFeatureDisabled
/* 01AF90 8001A390 24040010 */   li    $a0, 16
/* 01AF94 8001A394 10400002 */  beqz  $v0, .L8001A3A0
/* 01AF98 8001A398 24040001 */   li    $a0, 1
/* 01AF9C 8001A39C 00002021 */  addu  $a0, $zero, $zero
.L8001A3A0:
/* 01AFA0 8001A3A0 0C002CD9 */  jal   func_8000B364
/* 01AFA4 8001A3A4 00000000 */   nop   
/* 01AFA8 8001A3A8 0C018CEA */  jal   func_800633A8
/* 01AFAC 8001A3AC 00000000 */   nop   
/* 01AFB0 8001A3B0 0C018D06 */  jal   func_80063418
/* 01AFB4 8001A3B4 00402021 */   addu  $a0, $v0, $zero
glabel func_8001A3B8
/* 01AFB8 8001A3B8 0C018D6D */  jal   SleepVProcess
/* 01AFBC 8001A3BC 00000000 */   nop   
/* 01AFC0 8001A3C0 080068EE */  j     func_8001A3B8
/* 01AFC4 8001A3C4 00000000 */   nop   

/* 01AFC8 8001A3C8 8FBF0020 */  lw    $ra, 0x20($sp)
/* 01AFCC 8001A3CC 8FB1001C */  lw    $s1, 0x1c($sp)
/* 01AFD0 8001A3D0 8FB00018 */  lw    $s0, 0x18($sp)
/* 01AFD4 8001A3D4 03E00008 */  jr    $ra
/* 01AFD8 8001A3D8 27BD0028 */   addiu $sp, $sp, 0x28

D_8001A3DC:
/* 01AFDC 8001A3DC 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01AFE0 8001A3E0 AFBF0010 */  sw    $ra, 0x10($sp)
glabel func_8001A3E4
/* 01AFE4 8001A3E4 0C018D6D */  jal   SleepVProcess
/* 01AFE8 8001A3E8 00000000 */   nop   
/* 01AFEC 8001A3EC 0C00ADB2 */  jal   func_8002B6C8
/* 01AFF0 8001A3F0 00000000 */   nop   
/* 01AFF4 8001A3F4 0C0077F0 */  jal   func_8001DFC0
/* 01AFF8 8001A3F8 00000000 */   nop   
/* 01AFFC 8001A3FC 3C040200 */  lui   $a0, 0x200
/* 01B000 8001A400 3C05003D */  lui   $a1, (0x003D0800 >> 16) # lui $a1, 0x3d
/* 01B004 8001A404 0C009596 */  jal   func_80025658
/* 01B008 8001A408 34A50800 */   ori   $a1, (0x003D0800 & 0xFFFF) # ori $a1, $a1, 0x800
/* 01B00C 8001A40C 0C018876 */  jal   func_800621D8
/* 01B010 8001A410 00000000 */   nop   
/* 01B014 8001A414 080068F9 */  j     func_8001A3E4
/* 01B018 8001A418 00000000 */   nop   

/* 01B01C 8001A41C 8FBF0010 */  lw    $ra, 0x10($sp)
/* 01B020 8001A420 03E00008 */  jr    $ra
/* 01B024 8001A424 27BD0018 */   addiu $sp, $sp, 0x18

D_8001A428:
/* 01B028 8001A428 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01B02C 8001A42C AFBF0010 */  sw    $ra, 0x10($sp)
glabel func_8001A430
/* 01B030 8001A430 0C018D6D */  jal   SleepVProcess
/* 01B034 8001A434 00000000 */   nop   
/* 01B038 8001A438 0C0178FF */  jal   func_8005E3FC
/* 01B03C 8001A43C 00000000 */   nop   
/* 01B040 8001A440 0800690C */  j     func_8001A430
/* 01B044 8001A444 00000000 */   nop   

/* 01B048 8001A448 8FBF0010 */  lw    $ra, 0x10($sp)
/* 01B04C 8001A44C 03E00008 */  jr    $ra
/* 01B050 8001A450 27BD0018 */   addiu $sp, $sp, 0x18

D_8001A454:
/* 01B054 8001A454 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 01B058 8001A458 AFBF0010 */  sw    $ra, 0x10($sp)
glabel func_8001A45C
/* 01B05C 8001A45C 0C018D6D */  jal   SleepVProcess
/* 01B060 8001A460 00000000 */   nop   
/* 01B064 8001A464 0C0062CB */  jal   func_80018B2C
/* 01B068 8001A468 00000000 */   nop   
/* 01B06C 8001A46C 0C007968 */  jal   func_8001E5A0
/* 01B070 8001A470 24040002 */   li    $a0, 2
/* 01B074 8001A474 3C04800F */  lui   $a0, %hi(D_800ED538) # $a0, 0x800f
/* 01B078 8001A478 2484D538 */  addiu $a0, %lo(D_800ED538) # addiu $a0, $a0, -0x2ac8
/* 01B07C 8001A47C 0C0091FF */  jal   func_800247FC
/* 01B080 8001A480 24050002 */   li    $a1, 2
/* 01B084 8001A484 08006917 */  j     func_8001A45C
/* 01B088 8001A488 00000000 */   nop   

/* 01B08C 8001A48C 8FBF0010 */  lw    $ra, 0x10($sp)
/* 01B090 8001A490 03E00008 */  jr    $ra
/* 01B094 8001A494 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8001A498
/* 01B098 8001A498 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 01B09C 8001A49C AFBF0020 */  sw    $ra, 0x20($sp)
/* 01B0A0 8001A4A0 AFB3001C */  sw    $s3, 0x1c($sp)
/* 01B0A4 8001A4A4 AFB20018 */  sw    $s2, 0x18($sp)
/* 01B0A8 8001A4A8 AFB10014 */  sw    $s1, 0x14($sp)
/* 01B0AC 8001A4AC AFB00010 */  sw    $s0, 0x10($sp)
/* 01B0B0 8001A4B0 00008821 */  addu  $s1, $zero, $zero
/* 01B0B4 8001A4B4 24130001 */  li    $s3, 1
/* 01B0B8 8001A4B8 2412000A */  li    $s2, 10
.L8001A4BC:
/* 01B0BC 8001A4BC 3C02800F */  lui   $v0, %hi(D_800F3778) # $v0, 0x800f
/* 01B0C0 8001A4C0 84423778 */  lh    $v0, %lo(D_800F3778)($v0)
/* 01B0C4 8001A4C4 0222102A */  slt   $v0, $s1, $v0
/* 01B0C8 8001A4C8 1040000B */  beqz  $v0, .L8001A4F8
/* 01B0CC 8001A4CC 00111840 */   sll   $v1, $s1, 1
/* 01B0D0 8001A4D0 3C01800F */  lui   $at, 0x800f
/* 01B0D4 8001A4D4 00310821 */  addu  $at, $at, $s1
/* 01B0D8 8001A4D8 A020D558 */  sb    $zero, -0x2aa8($at)
/* 01B0DC 8001A4DC 00711821 */  addu  $v1, $v1, $s1
/* 01B0E0 8001A4E0 00031900 */  sll   $v1, $v1, 4
/* 01B0E4 8001A4E4 3C02800F */  lui   $v0, 0x800f
/* 01B0E8 8001A4E8 00431021 */  addu  $v0, $v0, $v1
/* 01B0EC 8001A4EC 944232B6 */  lhu   $v0, 0x32b6($v0)
/* 01B0F0 8001A4F0 08006947 */  j     func_8001A51C
/* 01B0F4 8001A4F4 3042FFFE */   andi  $v0, $v0, 0xfffe

.L8001A4F8:
/* 01B0F8 8001A4F8 3C01800F */  lui   $at, 0x800f
/* 01B0FC 8001A4FC 00310821 */  addu  $at, $at, $s1
/* 01B100 8001A500 A033D558 */  sb    $s3, -0x2aa8($at)
/* 01B104 8001A504 00711821 */  addu  $v1, $v1, $s1
/* 01B108 8001A508 00031900 */  sll   $v1, $v1, 4
/* 01B10C 8001A50C 3C02800F */  lui   $v0, 0x800f
/* 01B110 8001A510 00431021 */  addu  $v0, $v0, $v1
/* 01B114 8001A514 944232B6 */  lhu   $v0, 0x32b6($v0)
/* 01B118 8001A518 34420001 */  ori   $v0, $v0, 1
glabel func_8001A51C
/* 01B11C 8001A51C 3C01800F */  lui   $at, 0x800f
/* 01B120 8001A520 00230821 */  addu  $at, $at, $v1
/* 01B124 8001A524 A42232B6 */  sh    $v0, 0x32b6($at)
/* 01B128 8001A528 00118040 */  sll   $s0, $s1, 1
/* 01B12C 8001A52C 02118021 */  addu  $s0, $s0, $s1
/* 01B130 8001A530 00108100 */  sll   $s0, $s0, 4
/* 01B134 8001A534 3C01800F */  lui   $at, 0x800f
/* 01B138 8001A538 00300821 */  addu  $at, $at, $s0
/* 01B13C 8001A53C A03132B3 */  sb    $s1, 0x32b3($at)
/* 01B140 8001A540 3C01800F */  lui   $at, 0x800f
/* 01B144 8001A544 00300821 */  addu  $at, $at, $s0
/* 01B148 8001A548 A43232B8 */  sh    $s2, 0x32b8($at)
/* 01B14C 8001A54C 3C01800F */  lui   $at, 0x800f
/* 01B150 8001A550 00300821 */  addu  $at, $at, $s0
/* 01B154 8001A554 A42032BA */  sh    $zero, 0x32ba($at)
/* 01B158 8001A558 3C01800F */  lui   $at, 0x800f
/* 01B15C 8001A55C 00300821 */  addu  $at, $at, $s0
/* 01B160 8001A560 A03132B0 */  sb    $s1, 0x32b0($at)
/* 01B164 8001A564 02202021 */  addu  $a0, $s1, $zero
/* 01B168 8001A568 0C014B33 */  jal   func_80052CCC
/* 01B16C 8001A56C 24050001 */   li    $a1, 1
/* 01B170 8001A570 3C01800F */  lui   $at, 0x800f
/* 01B174 8001A574 00300821 */  addu  $at, $at, $s0
/* 01B178 8001A578 A42032BC */  sh    $zero, 0x32bc($at)
/* 01B17C 8001A57C 26310001 */  addiu $s1, $s1, 1
/* 01B180 8001A580 2A220004 */  slti  $v0, $s1, 4
/* 01B184 8001A584 1440FFCD */  bnez  $v0, .L8001A4BC
/* 01B188 8001A588 00002021 */   addu  $a0, $zero, $zero
/* 01B18C 8001A58C 0C016539 */  jal   func_800594E4
/* 01B190 8001A590 24054650 */   li    $a1, 18000
/* 01B194 8001A594 24040001 */  li    $a0, 1
/* 01B198 8001A598 0C016539 */  jal   func_800594E4
/* 01B19C 8001A59C 24050E10 */   li    $a1, 3600
/* 01B1A0 8001A5A0 24040002 */  li    $a0, 2
/* 01B1A4 8001A5A4 0C016539 */  jal   func_800594E4
/* 01B1A8 8001A5A8 24050E10 */   li    $a1, 3600
/* 01B1AC 8001A5AC 24040003 */  li    $a0, 3
/* 01B1B0 8001A5B0 0C016539 */  jal   func_800594E4
/* 01B1B4 8001A5B4 24054650 */   li    $a1, 18000
/* 01B1B8 8001A5B8 24040005 */  li    $a0, 5
/* 01B1BC 8001A5BC 0C016539 */  jal   func_800594E4
/* 01B1C0 8001A5C0 24050E10 */   li    $a1, 3600
/* 01B1C4 8001A5C4 24040006 */  li    $a0, 6
/* 01B1C8 8001A5C8 0C016539 */  jal   func_800594E4
/* 01B1CC 8001A5CC 24050E10 */   li    $a1, 3600
/* 01B1D0 8001A5D0 24040007 */  li    $a0, 7
/* 01B1D4 8001A5D4 0C016539 */  jal   func_800594E4
/* 01B1D8 8001A5D8 24050E10 */   li    $a1, 3600
/* 01B1DC 8001A5DC 8FBF0020 */  lw    $ra, 0x20($sp)
/* 01B1E0 8001A5E0 8FB3001C */  lw    $s3, 0x1c($sp)
/* 01B1E4 8001A5E4 8FB20018 */  lw    $s2, 0x18($sp)
/* 01B1E8 8001A5E8 8FB10014 */  lw    $s1, 0x14($sp)
/* 01B1EC 8001A5EC 8FB00010 */  lw    $s0, 0x10($sp)
/* 01B1F0 8001A5F0 03E00008 */  jr    $ra
/* 01B1F4 8001A5F4 27BD0028 */   addiu $sp, $sp, 0x28

/* 01B1F8 8001A5F8 00000000 */  nop   
/* 01B1FC 8001A5FC 00000000 */  nop   
