# Mario Party (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "globals.inc"
.include "macros.inc"

glabel func_8005B860
/* 05C460 8005B860 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 05C464 8005B864 AFBF0014 */  sw    $ra, 0x14($sp)
/* 05C468 8005B868 AFB00010 */  sw    $s0, 0x10($sp)
/* 05C46C 8005B86C 00801021 */  addu  $v0, $a0, $zero
/* 05C470 8005B870 3C01800E */  lui   $at, %hi(D_800D8920) # $at, 0x800e
/* 05C474 8005B874 A4228920 */  sh    $v0, %lo(D_800D8920)($at)
/* 05C478 8005B878 00042400 */  sll   $a0, $a0, 0x10
/* 05C47C 8005B87C 00042403 */  sra   $a0, $a0, 0x10
/* 05C480 8005B880 04800013 */  bltz  $a0, .L8005B8D0
/* 05C484 8005B884 00048040 */   sll   $s0, $a0, 1
/* 05C488 8005B888 02048021 */  addu  $s0, $s0, $a0
/* 05C48C 8005B88C 3C04800C */  lui   $a0, 0x800c
/* 05C490 8005B890 00902021 */  addu  $a0, $a0, $s0
/* 05C494 8005B894 0C0164D2 */  jal   func_80059348
/* 05C498 8005B898 80845820 */   lb    $a0, 0x5820($a0)
/* 05C49C 8005B89C 3C02800C */  lui   $v0, 0x800c
/* 05C4A0 8005B8A0 00501021 */  addu  $v0, $v0, $s0
/* 05C4A4 8005B8A4 90425821 */  lbu   $v0, 0x5821($v0)
/* 05C4A8 8005B8A8 00021600 */  sll   $v0, $v0, 0x18
/* 05C4AC 8005B8AC 00021603 */  sra   $v0, $v0, 0x18
/* 05C4B0 8005B8B0 3C01800F */  lui   $at, %hi(D_800F329A) # $at, 0x800f
/* 05C4B4 8005B8B4 A422329A */  sh    $v0, %lo(D_800F329A)($at)
/* 05C4B8 8005B8B8 3C02800C */  lui   $v0, 0x800c
/* 05C4BC 8005B8BC 00501021 */  addu  $v0, $v0, $s0
/* 05C4C0 8005B8C0 90425822 */  lbu   $v0, 0x5822($v0)
/* 05C4C4 8005B8C4 00021600 */  sll   $v0, $v0, 0x18
/* 05C4C8 8005B8C8 08016E3A */  j     func_8005B8E8
/* 05C4CC 8005B8CC 00021603 */   sra   $v0, $v0, 0x18

.L8005B8D0:
/* 05C4D0 8005B8D0 00022400 */  sll   $a0, $v0, 0x10
/* 05C4D4 8005B8D4 0C0164D2 */  jal   func_80059348
/* 05C4D8 8005B8D8 00042403 */   sra   $a0, $a0, 0x10
/* 05C4DC 8005B8DC 2402FFFF */  li    $v0, -1
/* 05C4E0 8005B8E0 3C01800F */  lui   $at, %hi(D_800F329A) # $at, 0x800f
/* 05C4E4 8005B8E4 A422329A */  sh    $v0, %lo(D_800F329A)($at)
glabel func_8005B8E8
/* 05C4E8 8005B8E8 3C01800F */  lui   $at, %hi(D_800F3750) # $at, 0x800f
/* 05C4EC 8005B8EC A4223750 */  sh    $v0, %lo(D_800F3750)($at)
/* 05C4F0 8005B8F0 8FBF0014 */  lw    $ra, 0x14($sp)
/* 05C4F4 8005B8F4 8FB00010 */  lw    $s0, 0x10($sp)
/* 05C4F8 8005B8F8 03E00008 */  jr    $ra
/* 05C4FC 8005B8FC 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8005B900
/* 05C500 8005B900 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 05C504 8005B904 AFBF0014 */  sw    $ra, 0x14($sp)
/* 05C508 8005B908 AFB00010 */  sw    $s0, 0x10($sp)
/* 05C50C 8005B90C 3C10800E */  lui   $s0, %hi(D_800D8920) # $s0, 0x800e
/* 05C510 8005B910 96108920 */  lhu   $s0, %lo(D_800D8920)($s0)
/* 05C514 8005B914 0C0165E6 */  jal   IsBoardFeatureDisabled
/* 05C518 8005B918 2404002F */   li    $a0, 47
/* 05C51C 8005B91C 10400008 */  beqz  $v0, .L8005B940
/* 05C520 8005B920 00101400 */   sll   $v0, $s0, 0x10
/* 05C524 8005B924 00028403 */  sra   $s0, $v0, 0x10
/* 05C528 8005B928 06000005 */  bltz  $s0, .L8005B940
/* 05C52C 8005B92C 00000000 */   nop   
/* 05C530 8005B930 0C01660B */  jal   SetBoardFeatureDisabled
/* 05C534 8005B934 2404002F */   li    $a0, 47
/* 05C538 8005B938 0C0173A3 */  jal   func_8005CE8C
/* 05C53C 8005B93C 26040007 */   addiu $a0, $s0, 7
.L8005B940:
/* 05C540 8005B940 8FBF0014 */  lw    $ra, 0x14($sp)
/* 05C544 8005B944 8FB00010 */  lw    $s0, 0x10($sp)
/* 05C548 8005B948 03E00008 */  jr    $ra
/* 05C54C 8005B94C 27BD0018 */   addiu $sp, $sp, 0x18

/* 05C550 8005B950 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 05C554 8005B954 AFBF0010 */  sw    $ra, 0x10($sp)
/* 05C558 8005B958 3C02800E */  lui   $v0, %hi(D_800D8920) # $v0, 0x800e
/* 05C55C 8005B95C 84428920 */  lh    $v0, %lo(D_800D8920)($v0)
/* 05C560 8005B960 04400005 */  bltz  $v0, .L8005B978
/* 05C564 8005B964 24020001 */   li    $v0, 1
/* 05C568 8005B968 3C04800E */  lui   $a0, %hi(D_800E0007) # $a0, 0x800e
/* 05C56C 8005B96C 84848920 */  lh    $a0, %lo(D_800D8920)($a0)
/* 05C570 8005B970 0C017392 */  jal   func_8005CE48
/* 05C574 8005B974 24840007 */   addiu $a0, %lo(D_800E0007) # addiu $a0, $a0, 7
.L8005B978:
/* 05C578 8005B978 8FBF0010 */  lw    $ra, 0x10($sp)
/* 05C57C 8005B97C 03E00008 */  jr    $ra
/* 05C580 8005B980 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8005B984
/* 05C584 8005B984 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 05C588 8005B988 AFBF0028 */  sw    $ra, 0x28($sp)
/* 05C58C 8005B98C AFB30024 */  sw    $s3, 0x24($sp)
/* 05C590 8005B990 AFB20020 */  sw    $s2, 0x20($sp)
/* 05C594 8005B994 AFB1001C */  sw    $s1, 0x1c($sp)
/* 05C598 8005B998 AFB00018 */  sw    $s0, 0x18($sp)
/* 05C59C 8005B99C 00809021 */  addu  $s2, $a0, $zero
/* 05C5A0 8005B9A0 3C13800F */  lui   $s3, %hi(D_800F32B3) # $s3, 0x800f
/* 05C5A4 8005B9A4 927332B3 */  lbu   $s3, %lo(D_800F32B3)($s3)
/* 05C5A8 8005B9A8 0C0180AB */  jal   PlaySound
/* 05C5AC 8005B9AC 24040036 */   li    $a0, 54
/* 05C5B0 8005B9B0 AFA00010 */  sw    $zero, 0x10($sp)
/* 05C5B4 8005B9B4 AFA00014 */  sw    $zero, 0x14($sp)
/* 05C5B8 8005B9B8 2404005F */  li    $a0, 95
/* 05C5BC 8005B9BC 24050032 */  li    $a1, 50
/* 05C5C0 8005B9C0 24060081 */  li    $a2, 129
/* 05C5C4 8005B9C4 0C01B404 */  jal   func_8006D010
/* 05C5C8 8005B9C8 24070022 */   li    $a3, 34
/* 05C5CC 8005B9CC 00408021 */  addu  $s0, $v0, $zero
/* 05C5D0 8005B9D0 00101400 */  sll   $v0, $s0, 0x10
/* 05C5D4 8005B9D4 00028C03 */  sra   $s1, $v0, 0x10
/* 05C5D8 8005B9D8 02202021 */  addu  $a0, $s1, $zero
/* 05C5DC 8005B9DC 0C01B829 */  jal   func_8006E0A4
/* 05C5E0 8005B9E0 24050005 */   li    $a1, 5
/* 05C5E4 8005B9E4 02202021 */  addu  $a0, $s1, $zero
/* 05C5E8 8005B9E8 0C01B855 */  jal   func_8006E154
/* 05C5EC 8005B9EC 240500DC */   li    $a1, 220
/* 05C5F0 8005B9F0 56400004 */  bnezl $s2, .L8005BA04
/* 05C5F4 8005B9F4 00102400 */   sll   $a0, $s0, 0x10
/* 05C5F8 8005B9F8 02202021 */  addu  $a0, $s1, $zero
/* 05C5FC 8005B9FC 08016E83 */  j     func_8005BA0C
/* 05C600 8005BA00 240504A8 */   li    $a1, 1192

.L8005BA04:
/* 05C604 8005BA04 00042403 */  sra   $a0, $a0, 0x10
/* 05C608 8005BA08 02402821 */  addu  $a1, $s2, $zero
glabel func_8005BA0C
/* 05C60C 8005BA0C 2406FFFF */  li    $a2, -1
/* 05C610 8005BA10 0C01B5F6 */  jal   LoadStringIntoWindow
/* 05C614 8005BA14 2407FFFF */   li    $a3, -1
/* 05C618 8005BA18 00102400 */  sll   $a0, $s0, 0x10
/* 05C61C 8005BA1C 00042403 */  sra   $a0, $a0, 0x10
/* 05C620 8005BA20 0C01B81C */  jal   SetTextCharsPerFrame
/* 05C624 8005BA24 00002821 */   addu  $a1, $zero, $zero
/* 05C628 8005BA28 00108C00 */  sll   $s1, $s0, 0x10
glabel func_8005BA2C
/* 05C62C 8005BA2C 0C01BF30 */  jal   func_8006FCC0
/* 05C630 8005BA30 00112403 */   sra   $a0, $s1, 0x10
/* 05C634 8005BA34 00021400 */  sll   $v0, $v0, 0x10
/* 05C638 8005BA38 50400005 */  beql  $v0, $zero, .L8005BA50
/* 05C63C 8005BA3C 00108400 */   sll   $s0, $s0, 0x10
/* 05C640 8005BA40 0C018D6D */  jal   SleepVProcess
/* 05C644 8005BA44 00000000 */   nop   
/* 05C648 8005BA48 08016E8B */  j     func_8005BA2C
/* 05C64C 8005BA4C 00000000 */   nop   

.L8005BA50:
/* 05C650 8005BA50 00108403 */  sra   $s0, $s0, 0x10
/* 05C654 8005BA54 3C050001 */  lui   $a1, 1
/* 05C658 8005BA58 02652804 */  sllv  $a1, $a1, $s3
/* 05C65C 8005BA5C 02002021 */  addu  $a0, $s0, $zero
/* 05C660 8005BA60 0C01C557 */  jal   func_8007155C
/* 05C664 8005BA64 00052C03 */   sra   $a1, $a1, 0x10
/* 05C668 8005BA68 02002021 */  addu  $a0, $s0, $zero
/* 05C66C 8005BA6C 00002821 */  addu  $a1, $zero, $zero
/* 05C670 8005BA70 0C01BF3C */  jal   func_8006FCF0
/* 05C674 8005BA74 00003021 */   addu  $a2, $zero, $zero
/* 05C678 8005BA78 00408821 */  addu  $s1, $v0, $zero
/* 05C67C 8005BA7C 0C01C364 */  jal   func_80070D90
/* 05C680 8005BA80 02002021 */   addu  $a0, $s0, $zero
/* 05C684 8005BA84 0C0180AB */  jal   PlaySound
/* 05C688 8005BA88 24040037 */   li    $a0, 55
/* 05C68C 8005BA8C 00118C00 */  sll   $s1, $s1, 0x10
/* 05C690 8005BA90 00111403 */  sra   $v0, $s1, 0x10
/* 05C694 8005BA94 8FBF0028 */  lw    $ra, 0x28($sp)
/* 05C698 8005BA98 8FB30024 */  lw    $s3, 0x24($sp)
/* 05C69C 8005BA9C 8FB20020 */  lw    $s2, 0x20($sp)
/* 05C6A0 8005BAA0 8FB1001C */  lw    $s1, 0x1c($sp)
/* 05C6A4 8005BAA4 8FB00018 */  lw    $s0, 0x18($sp)
/* 05C6A8 8005BAA8 03E00008 */  jr    $ra
/* 05C6AC 8005BAAC 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8005BAB0
/* 05C6B0 8005BAB0 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 05C6B4 8005BAB4 AFBF0028 */  sw    $ra, 0x28($sp)
/* 05C6B8 8005BAB8 AFB30024 */  sw    $s3, 0x24($sp)
/* 05C6BC 8005BABC AFB20020 */  sw    $s2, 0x20($sp)
/* 05C6C0 8005BAC0 AFB1001C */  sw    $s1, 0x1c($sp)
/* 05C6C4 8005BAC4 AFB00018 */  sw    $s0, 0x18($sp)
/* 05C6C8 8005BAC8 00809821 */  addu  $s3, $a0, $zero
/* 05C6CC 8005BACC 3C12800E */  lui   $s2, %hi(D_800D8920) # $s2, 0x800e
/* 05C6D0 8005BAD0 96528920 */  lhu   $s2, %lo(D_800D8920)($s2)
/* 05C6D4 8005BAD4 0C0180AB */  jal   PlaySound
/* 05C6D8 8005BAD8 24040036 */   li    $a0, 54
/* 05C6DC 8005BADC AFA00010 */  sw    $zero, 0x10($sp)
/* 05C6E0 8005BAE0 AFA00014 */  sw    $zero, 0x14($sp)
/* 05C6E4 8005BAE4 24040048 */  li    $a0, 72
/* 05C6E8 8005BAE8 24050096 */  li    $a1, 150
/* 05C6EC 8005BAEC 240600AD */  li    $a2, 173
/* 05C6F0 8005BAF0 0C01B404 */  jal   func_8006D010
/* 05C6F4 8005BAF4 24070030 */   li    $a3, 48
/* 05C6F8 8005BAF8 00408821 */  addu  $s1, $v0, $zero
/* 05C6FC 8005BAFC 00111400 */  sll   $v0, $s1, 0x10
/* 05C700 8005BB00 00028403 */  sra   $s0, $v0, 0x10
/* 05C704 8005BB04 02002021 */  addu  $a0, $s0, $zero
/* 05C708 8005BB08 0C01B829 */  jal   func_8006E0A4
/* 05C70C 8005BB0C 24050005 */   li    $a1, 5
/* 05C710 8005BB10 02002021 */  addu  $a0, $s0, $zero
/* 05C714 8005BB14 0C01B855 */  jal   func_8006E154
/* 05C718 8005BB18 240500DC */   li    $a1, 220
/* 05C71C 8005BB1C 0C01C5F0 */  jal   func_800717C0
/* 05C720 8005BB20 02002021 */   addu  $a0, $s0, $zero
/* 05C724 8005BB24 5660002C */  bnezl $s3, .L8005BBD8
/* 05C728 8005BB28 00112400 */   sll   $a0, $s1, 0x10
/* 05C72C 8005BB2C 00121400 */  sll   $v0, $s2, 0x10
/* 05C730 8005BB30 00021403 */  sra   $v0, $v0, 0x10
/* 05C734 8005BB34 2403FFFE */  li    $v1, -2
/* 05C738 8005BB38 5443000B */  bnel  $v0, $v1, .L8005BB68
/* 05C73C 8005BB3C 00122400 */   sll   $a0, $s2, 0x10
/* 05C740 8005BB40 3C02800F */  lui   $v0, %hi(D_800ED154) # $v0, 0x800f
/* 05C744 8005BB44 8442D154 */  lh    $v0, %lo(D_800ED154)($v0)
/* 05C748 8005BB48 50400004 */  beql  $v0, $zero, .L8005BB5C
/* 05C74C 8005BB4C 00112400 */   sll   $a0, $s1, 0x10
/* 05C750 8005BB50 02002021 */  addu  $a0, $s0, $zero
/* 05C754 8005BB54 08016EF8 */  j     func_8005BBE0
/* 05C758 8005BB58 240504AD */   li    $a1, 1197

.L8005BB5C:
/* 05C75C 8005BB5C 00042403 */  sra   $a0, $a0, 0x10
/* 05C760 8005BB60 08016EF8 */  j     func_8005BBE0
/* 05C764 8005BB64 240504AC */   li    $a1, 1196

.L8005BB68:
/* 05C768 8005BB68 00042403 */  sra   $a0, $a0, 0x10
/* 05C76C 8005BB6C 0C017392 */  jal   func_8005CE48
/* 05C770 8005BB70 24840007 */   addiu $a0, $a0, 7
/* 05C774 8005BB74 10400004 */  beqz  $v0, .L8005BB88
/* 05C778 8005BB78 240504AA */   li    $a1, 1194
/* 05C77C 8005BB7C 00112400 */  sll   $a0, $s1, 0x10
/* 05C780 8005BB80 08016EE5 */  j     func_8005BB94
/* 05C784 8005BB84 00042403 */   sra   $a0, $a0, 0x10

.L8005BB88:
/* 05C788 8005BB88 00112400 */  sll   $a0, $s1, 0x10
/* 05C78C 8005BB8C 00042403 */  sra   $a0, $a0, 0x10
/* 05C790 8005BB90 240504AB */  li    $a1, 1195
glabel func_8005BB94
/* 05C794 8005BB94 2406FFFF */  li    $a2, -1
/* 05C798 8005BB98 0C01B5F6 */  jal   LoadStringIntoWindow
/* 05C79C 8005BB9C 2407FFFF */   li    $a3, -1
/* 05C7A0 8005BBA0 00112400 */  sll   $a0, $s1, 0x10
/* 05C7A4 8005BBA4 00121C00 */  sll   $v1, $s2, 0x10
/* 05C7A8 8005BBA8 00031C03 */  sra   $v1, $v1, 0x10
/* 05C7AC 8005BBAC 00031040 */  sll   $v0, $v1, 1
/* 05C7B0 8005BBB0 00431021 */  addu  $v0, $v0, $v1
/* 05C7B4 8005BBB4 3C05800C */  lui   $a1, 0x800c
/* 05C7B8 8005BBB8 00A22821 */  addu  $a1, $a1, $v0
/* 05C7BC 8005BBBC 80A55820 */  lb    $a1, 0x5820($a1)
/* 05C7C0 8005BBC0 00042403 */  sra   $a0, $a0, 0x10
/* 05C7C4 8005BBC4 24A50325 */  addiu $a1, $a1, 0x325
/* 05C7C8 8005BBC8 0C01C637 */  jal   func_800718DC
/* 05C7CC 8005BBCC 00003021 */   addu  $a2, $zero, $zero
/* 05C7D0 8005BBD0 08016EFC */  j     func_8005BBF0
/* 05C7D4 8005BBD4 00118400 */   sll   $s0, $s1, 0x10

.L8005BBD8:
/* 05C7D8 8005BBD8 00042403 */  sra   $a0, $a0, 0x10
/* 05C7DC 8005BBDC 02602821 */  addu  $a1, $s3, $zero
glabel func_8005BBE0
/* 05C7E0 8005BBE0 2406FFFF */  li    $a2, -1
/* 05C7E4 8005BBE4 0C01B5F6 */  jal   LoadStringIntoWindow
/* 05C7E8 8005BBE8 2407FFFF */   li    $a3, -1
/* 05C7EC 8005BBEC 00118400 */  sll   $s0, $s1, 0x10
glabel func_8005BBF0
/* 05C7F0 8005BBF0 00108403 */  sra   $s0, $s0, 0x10
/* 05C7F4 8005BBF4 02002021 */  addu  $a0, $s0, $zero
/* 05C7F8 8005BBF8 0C01B81C */  jal   SetTextCharsPerFrame
/* 05C7FC 8005BBFC 00002821 */   addu  $a1, $zero, $zero
/* 05C800 8005BC00 0C0180AB */  jal   PlaySound
/* 05C804 8005BC04 24040037 */   li    $a0, 55
/* 05C808 8005BC08 02001021 */  addu  $v0, $s0, $zero
/* 05C80C 8005BC0C 8FBF0028 */  lw    $ra, 0x28($sp)
/* 05C810 8005BC10 8FB30024 */  lw    $s3, 0x24($sp)
/* 05C814 8005BC14 8FB20020 */  lw    $s2, 0x20($sp)
/* 05C818 8005BC18 8FB1001C */  lw    $s1, 0x1c($sp)
/* 05C81C 8005BC1C 8FB00018 */  lw    $s0, 0x18($sp)
/* 05C820 8005BC20 03E00008 */  jr    $ra
/* 05C824 8005BC24 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8005BC28
/* 05C828 8005BC28 27BDFFD8 */  addiu $sp, $sp, -0x28
/* 05C82C 8005BC2C AFBF0024 */  sw    $ra, 0x24($sp)
/* 05C830 8005BC30 AFB00020 */  sw    $s0, 0x20($sp)
/* 05C834 8005BC34 0C014AA3 */  jal   GetPlayerStruct
/* 05C838 8005BC38 2404FFFF */   li    $a0, -1
/* 05C83C 8005BC3C 00408021 */  addu  $s0, $v0, $zero
/* 05C840 8005BC40 2404FFFF */  li    $a0, -1
/* 05C844 8005BC44 2405FFFF */  li    $a1, -1
/* 05C848 8005BC48 0C014AFA */  jal   SetPlayerAnimation
/* 05C84C 8005BC4C 24060002 */   li    $a2, 2
/* 05C850 8005BC50 0C013361 */  jal   func_8004CD84
/* 05C854 8005BC54 27A40010 */   addiu $a0, $sp, 0x10
/* 05C858 8005BC58 8E060020 */  lw    $a2, 0x20($s0)
/* 05C85C 8005BC5C 24C60018 */  addiu $a2, $a2, 0x18
/* 05C860 8005BC60 00C02021 */  addu  $a0, $a2, $zero
/* 05C864 8005BC64 27A50010 */  addiu $a1, $sp, 0x10
/* 05C868 8005BC68 0C01347B */  jal   func_8004D1EC
/* 05C86C 8005BC6C 24070008 */   li    $a3, 8
/* 05C870 8005BC70 8FBF0024 */  lw    $ra, 0x24($sp)
/* 05C874 8005BC74 8FB00020 */  lw    $s0, 0x20($sp)
/* 05C878 8005BC78 03E00008 */  jr    $ra
/* 05C87C 8005BC7C 27BD0028 */   addiu $sp, $sp, 0x28

glabel func_8005BC80
/* 05C880 8005BC80 3C01800F */  lui   $at, %hi(D_800F524A) # $at, 0x800f
/* 05C884 8005BC84 A020524A */  sb    $zero, %lo(D_800F524A)($at)
/* 05C888 8005BC88 00001821 */  addu  $v1, $zero, $zero
/* 05C88C 8005BC8C 2404FFFF */  li    $a0, -1
/* 05C890 8005BC90 00031080 */  sll   $v0, $v1, 2
.L8005BC94:
/* 05C894 8005BC94 3C01800F */  lui   $at, 0x800f
/* 05C898 8005BC98 00220821 */  addu  $at, $at, $v0
/* 05C89C 8005BC9C A42433D8 */  sh    $a0, 0x33d8($at)
/* 05C8A0 8005BCA0 24630001 */  addiu $v1, $v1, 1
/* 05C8A4 8005BCA4 28620004 */  slti  $v0, $v1, 4
/* 05C8A8 8005BCA8 1440FFFA */  bnez  $v0, .L8005BC94
/* 05C8AC 8005BCAC 00031080 */   sll   $v0, $v1, 2
/* 05C8B0 8005BCB0 24020001 */  li    $v0, 1
/* 05C8B4 8005BCB4 3C01800F */  lui   $at, %hi(D_800F3752) # $at, 0x800f
/* 05C8B8 8005BCB8 A0223752 */  sb    $v0, %lo(D_800F3752)($at)
/* 05C8BC 8005BCBC 3C01800F */  lui   $at, 0x800f
/* 05C8C0 8005BCC0 03E00008 */  jr    $ra
/* 05C8C4 8005BCC4 A0220A22 */   sb    $v0, 0xa22($at)

glabel func_8005BCC8
/* 05C8C8 8005BCC8 27BDFFF8 */  addiu $sp, $sp, -8
/* 05C8CC 8005BCCC 3C03800F */  lui   $v1, %hi(D_800F524A) # $v1, 0x800f
/* 05C8D0 8005BCD0 8063524A */  lb    $v1, %lo(D_800F524A)($v1)
/* 05C8D4 8005BCD4 28620004 */  slti  $v0, $v1, 4
/* 05C8D8 8005BCD8 1040000B */  beqz  $v0, .L8005BD08
/* 05C8DC 8005BCDC 00603021 */   addu  $a2, $v1, $zero
/* 05C8E0 8005BCE0 00031080 */  sll   $v0, $v1, 2
/* 05C8E4 8005BCE4 3C01800F */  lui   $at, 0x800f
/* 05C8E8 8005BCE8 00220821 */  addu  $at, $at, $v0
/* 05C8EC 8005BCEC A42433D8 */  sh    $a0, 0x33d8($at)
/* 05C8F0 8005BCF0 3C01800F */  lui   $at, 0x800f
/* 05C8F4 8005BCF4 00220821 */  addu  $at, $at, $v0
/* 05C8F8 8005BCF8 A42533DA */  sh    $a1, 0x33da($at)
/* 05C8FC 8005BCFC 24C20001 */  addiu $v0, $a2, 1
/* 05C900 8005BD00 3C01800F */  lui   $at, %hi(D_800F524A) # $at, 0x800f
/* 05C904 8005BD04 A022524A */  sb    $v0, %lo(D_800F524A)($at)
.L8005BD08:
/* 05C908 8005BD08 03E00008 */  jr    $ra
/* 05C90C 8005BD0C 27BD0008 */   addiu $sp, $sp, 8

/* 05C910 8005BD10 3C01800F */  lui   $at, 0x800f
/* 05C914 8005BD14 03E00008 */  jr    $ra
/* 05C918 8005BD18 A0243752 */   sb    $a0, 0x3752($at)

/* 05C91C 8005BD1C 3C01800F */  lui   $at, 0x800f
/* 05C920 8005BD20 03E00008 */  jr    $ra
/* 05C924 8005BD24 A0240A22 */   sb    $a0, 0xa22($at)

glabel func_8005BD28
/* 05C928 8005BD28 27BDFFE8 */  addiu $sp, $sp, -0x18
/* 05C92C 8005BD2C AFBF0014 */  sw    $ra, 0x14($sp)
/* 05C930 8005BD30 AFB00010 */  sw    $s0, 0x10($sp)
/* 05C934 8005BD34 0C014AA3 */  jal   GetPlayerStruct
/* 05C938 8005BD38 00002021 */   addu  $a0, $zero, $zero
/* 05C93C 8005BD3C 00408021 */  addu  $s0, $v0, $zero
/* 05C940 8005BD40 3C02800F */  lui   $v0, %hi(D_800F3752) # $v0, 0x800f
/* 05C944 8005BD44 80423752 */  lb    $v0, %lo(D_800F3752)($v0)
/* 05C948 8005BD48 10400007 */  beqz  $v0, .L8005BD68
/* 05C94C 8005BD4C 00000000 */   nop   
/* 05C950 8005BD50 96050010 */  lhu   $a1, 0x10($s0)
/* 05C954 8005BD54 24A50001 */  addiu $a1, $a1, 1
/* 05C958 8005BD58 00052C00 */  sll   $a1, $a1, 0x10
/* 05C95C 8005BD5C 8604000E */  lh    $a0, 0xe($s0)
/* 05C960 8005BD60 0C016F32 */  jal   func_8005BCC8
/* 05C964 8005BD64 00052C03 */   sra   $a1, $a1, 0x10
.L8005BD68:
/* 05C968 8005BD68 3C02800F */  lui   $v0, %hi(D_800F0A22) # $v0, 0x800f
/* 05C96C 8005BD6C 80420A22 */  lb    $v0, %lo(D_800F0A22)($v0)
/* 05C970 8005BD70 10400007 */  beqz  $v0, .L8005BD90
/* 05C974 8005BD74 00000000 */   nop   
/* 05C978 8005BD78 96050010 */  lhu   $a1, 0x10($s0)
/* 05C97C 8005BD7C 24A5FFFF */  addiu $a1, $a1, -1
/* 05C980 8005BD80 00052C00 */  sll   $a1, $a1, 0x10
/* 05C984 8005BD84 8604000E */  lh    $a0, 0xe($s0)
/* 05C988 8005BD88 0C016F32 */  jal   func_8005BCC8
/* 05C98C 8005BD8C 00052C03 */   sra   $a1, $a1, 0x10
.L8005BD90:
/* 05C990 8005BD90 8FBF0014 */  lw    $ra, 0x14($sp)
/* 05C994 8005BD94 8FB00010 */  lw    $s0, 0x10($sp)
/* 05C998 8005BD98 03E00008 */  jr    $ra
/* 05C99C 8005BD9C 27BD0018 */   addiu $sp, $sp, 0x18

glabel func_8005BDA0
/* 05C9A0 8005BDA0 27BDFFA0 */  addiu $sp, $sp, -0x60
/* 05C9A4 8005BDA4 AFBF0050 */  sw    $ra, 0x50($sp)
/* 05C9A8 8005BDA8 AFB5004C */  sw    $s5, 0x4c($sp)
/* 05C9AC 8005BDAC AFB40048 */  sw    $s4, 0x48($sp)
/* 05C9B0 8005BDB0 AFB30044 */  sw    $s3, 0x44($sp)
/* 05C9B4 8005BDB4 AFB20040 */  sw    $s2, 0x40($sp)
/* 05C9B8 8005BDB8 AFB1003C */  sw    $s1, 0x3c($sp)
/* 05C9BC 8005BDBC AFB00038 */  sw    $s0, 0x38($sp)
/* 05C9C0 8005BDC0 F7B40058 */  sdc1  $f20, 0x58($sp)
/* 05C9C4 8005BDC4 0080A021 */  addu  $s4, $a0, $zero
/* 05C9C8 8005BDC8 00A0A821 */  addu  $s5, $a1, $zero
/* 05C9CC 8005BDCC 0C014AA3 */  jal   GetPlayerStruct
/* 05C9D0 8005BDD0 00002021 */   addu  $a0, $zero, $zero
/* 05C9D4 8005BDD4 00409821 */  addu  $s3, $v0, $zero
/* 05C9D8 8005BDD8 92620003 */  lbu   $v0, 3($s3)
/* 05C9DC 8005BDDC 3C01800F */  lui   $at, 0x800f
/* 05C9E0 8005BDE0 00220821 */  addu  $at, $at, $v0
/* 05C9E4 8005BDE4 8022CE14 */  lb    $v0, -0x31ec($at)
/* 05C9E8 8005BDE8 44820000 */  mtc1  $v0, $f0
/* 05C9EC 8005BDEC 00000000 */  nop   
/* 05C9F0 8005BDF0 46800020 */  cvt.s.w $f0, $f0
/* 05C9F4 8005BDF4 E7A00010 */  swc1  $f0, 0x10($sp)
/* 05C9F8 8005BDF8 92620003 */  lbu   $v0, 3($s3)
/* 05C9FC 8005BDFC 3C01800F */  lui   $at, 0x800f
/* 05CA00 8005BE00 00220821 */  addu  $at, $at, $v0
/* 05CA04 8005BE04 80223843 */  lb    $v0, 0x3843($at)
/* 05CA08 8005BE08 44820000 */  mtc1  $v0, $f0
/* 05CA0C 8005BE0C 00000000 */  nop   
/* 05CA10 8005BE10 46800020 */  cvt.s.w $f0, $f0
/* 05CA14 8005BE14 46000007 */  neg.s $f0, $f0
/* 05CA18 8005BE18 E7A00018 */  swc1  $f0, 0x18($sp)
/* 05CA1C 8005BE1C AFA00014 */  sw    $zero, 0x14($sp)
/* 05CA20 8005BE20 3C02800F */  lui   $v0, %hi(D_800F524A) # $v0, 0x800f
/* 05CA24 8005BE24 8042524A */  lb    $v0, %lo(D_800F524A)($v0)
/* 05CA28 8005BE28 1840002C */  blez  $v0, .L8005BEDC
/* 05CA2C 8005BE2C 00008821 */   addu  $s1, $zero, $zero
/* 05CA30 8005BE30 27B20020 */  addiu $s2, $sp, 0x20
/* 05CA34 8005BE34 3C0141F0 */  li    $at, 0x41F00000 # 30.000000
/* 05CA38 8005BE38 4481A000 */  mtc1  $at, $f20
/* 05CA3C 8005BE3C 00118080 */  sll   $s0, $s1, 2
.L8005BE40:
/* 05CA40 8005BE40 3C04800F */  lui   $a0, 0x800f
/* 05CA44 8005BE44 00902021 */  addu  $a0, $a0, $s0
/* 05CA48 8005BE48 948433D8 */  lhu   $a0, 0x33d8($a0)
/* 05CA4C 8005BE4C 3C05800F */  lui   $a1, 0x800f
/* 05CA50 8005BE50 00B02821 */  addu  $a1, $a1, $s0
/* 05CA54 8005BE54 0C013081 */  jal   GetAbsSpaceIndexFromChainSpaceIndex
/* 05CA58 8005BE58 94A533DA */   lhu   $a1, 0x33da($a1)
/* 05CA5C 8005BE5C 00021400 */  sll   $v0, $v0, 0x10
/* 05CA60 8005BE60 0C01307B */  jal   GetSpaceData
/* 05CA64 8005BE64 00022403 */   sra   $a0, $v0, 0x10
/* 05CA68 8005BE68 8E660020 */  lw    $a2, 0x20($s3)
/* 05CA6C 8005BE6C 02402021 */  addu  $a0, $s2, $zero
/* 05CA70 8005BE70 24450004 */  addiu $a1, $v0, 4
/* 05CA74 8005BE74 0C0283A0 */  jal   func_800A0E80
/* 05CA78 8005BE78 24C6000C */   addiu $a2, $a2, 0xc
/* 05CA7C 8005BE7C AFA00024 */  sw    $zero, 0x24($sp)
/* 05CA80 8005BE80 27A40010 */  addiu $a0, $sp, 0x10
/* 05CA84 8005BE84 0C00F633 */  jal   func_8003D8CC
/* 05CA88 8005BE88 02402821 */   addu  $a1, $s2, $zero
/* 05CA8C 8005BE8C 4614003E */  c.le.s $f0, $f20
/* 05CA90 8005BE90 00000000 */  nop   
/* 05CA94 8005BE94 00000000 */  nop   
/* 05CA98 8005BE98 4500000B */  bc1f  .L8005BEC8
/* 05CA9C 8005BE9C 26310001 */   addiu $s1, $s1, 1
/* 05CAA0 8005BEA0 3C02800F */  lui   $v0, 0x800f
/* 05CAA4 8005BEA4 00501021 */  addu  $v0, $v0, $s0
/* 05CAA8 8005BEA8 944233D8 */  lhu   $v0, 0x33d8($v0)
/* 05CAAC 8005BEAC A6820000 */  sh    $v0, ($s4)
/* 05CAB0 8005BEB0 3C02800F */  lui   $v0, 0x800f
/* 05CAB4 8005BEB4 00501021 */  addu  $v0, $v0, $s0
/* 05CAB8 8005BEB8 944233DA */  lhu   $v0, 0x33da($v0)
/* 05CABC 8005BEBC A6A20000 */  sh    $v0, ($s5)
/* 05CAC0 8005BEC0 08016FB8 */  j     func_8005BEE0
/* 05CAC4 8005BEC4 24020001 */   li    $v0, 1

.L8005BEC8:
/* 05CAC8 8005BEC8 3C02800F */  lui   $v0, %hi(D_800F524A) # $v0, 0x800f
/* 05CACC 8005BECC 8042524A */  lb    $v0, %lo(D_800F524A)($v0)
/* 05CAD0 8005BED0 0222102A */  slt   $v0, $s1, $v0
/* 05CAD4 8005BED4 1440FFDA */  bnez  $v0, .L8005BE40
/* 05CAD8 8005BED8 00118080 */   sll   $s0, $s1, 2
.L8005BEDC:
/* 05CADC 8005BEDC 00001021 */  addu  $v0, $zero, $zero
glabel func_8005BEE0
/* 05CAE0 8005BEE0 8FBF0050 */  lw    $ra, 0x50($sp)
/* 05CAE4 8005BEE4 8FB5004C */  lw    $s5, 0x4c($sp)
/* 05CAE8 8005BEE8 8FB40048 */  lw    $s4, 0x48($sp)
/* 05CAEC 8005BEEC 8FB30044 */  lw    $s3, 0x44($sp)
/* 05CAF0 8005BEF0 8FB20040 */  lw    $s2, 0x40($sp)
/* 05CAF4 8005BEF4 8FB1003C */  lw    $s1, 0x3c($sp)
/* 05CAF8 8005BEF8 8FB00038 */  lw    $s0, 0x38($sp)
/* 05CAFC 8005BEFC D7B40058 */  ldc1  $f20, 0x58($sp)
/* 05CB00 8005BF00 03E00008 */  jr    $ra
/* 05CB04 8005BF04 27BD0060 */   addiu $sp, $sp, 0x60

D_8005BF08:
/* 05CB08 8005BF08 27BDFFB0 */  addiu $sp, $sp, -0x50
/* 05CB0C 8005BF0C AFBF0018 */  sw    $ra, 0x18($sp)
/* 05CB10 8005BF10 AFB10014 */  sw    $s1, 0x14($sp)
/* 05CB14 8005BF14 AFB00010 */  sw    $s0, 0x10($sp)
/* 05CB18 8005BF18 F7BE0048 */  sdc1  $f30, 0x48($sp)
/* 05CB1C 8005BF1C F7BC0040 */  sdc1  $f28, 0x40($sp)
/* 05CB20 8005BF20 F7BA0038 */  sdc1  $f26, 0x38($sp)
/* 05CB24 8005BF24 F7B80030 */  sdc1  $f24, 0x30($sp)
/* 05CB28 8005BF28 F7B60028 */  sdc1  $f22, 0x28($sp)
/* 05CB2C 8005BF2C F7B40020 */  sdc1  $f20, 0x20($sp)
/* 05CB30 8005BF30 4480B000 */  mtc1  $zero, $f22
/* 05CB34 8005BF34 3C014170 */  li    $at, 0x41700000 # 15.000000
/* 05CB38 8005BF38 4481F000 */  mtc1  $at, $f30
/* 05CB3C 8005BF3C 3C0143B4 */  li    $at, 0x43B40000 # 360.000000
/* 05CB40 8005BF40 4481C000 */  mtc1  $at, $f24
/* 05CB44 8005BF44 3C013E19 */  li    $at, 0x3E190000 # 0.149414
/* 05CB48 8005BF48 3421999A */  ori   $at, (0x3E19999A & 0xFFFF) # ori $at, $at, 0x999a
/* 05CB4C 8005BF4C 4481E000 */  mtc1  $at, $f28
/* 05CB50 8005BF50 3C013F8C */  li    $at, 0x3F8C0000 # 1.093750
/* 05CB54 8005BF54 3421CCCD */  ori   $at, (0x3F8CCCCD & 0xFFFF) # ori $at, $at, 0xcccd
/* 05CB58 8005BF58 4481D000 */  mtc1  $at, $f26
/* 05CB5C 8005BF5C 3C11800E */  lui   $s1, %hi(D_800D8930) # $s1, 0x800e
/* 05CB60 8005BF60 26318930 */  addiu $s1, %lo(D_800D8930) # addiu $s1, $s1, -0x76d0
glabel func_8005BF64
/* 05CB64 8005BF64 0C018D6D */  jal   SleepVProcess
/* 05CB68 8005BF68 00000000 */   nop   
/* 05CB6C 8005BF6C 461EB580 */  add.s $f22, $f22, $f30
/* 05CB70 8005BF70 4616C03C */  c.lt.s $f24, $f22
/* 05CB74 8005BF74 00000000 */  nop   
/* 05CB78 8005BF78 00000000 */  nop   
/* 05CB7C 8005BF7C 45030001 */  bc1tl .L8005BF84
/* 05CB80 8005BF80 4618B581 */   sub.s $f22, $f22, $f24
.L8005BF84:
/* 05CB84 8005BF84 0C02BBF4 */  jal   func_800AEFD0
/* 05CB88 8005BF88 4600B306 */   mov.s $f12, $f22
/* 05CB8C 8005BF8C 461C0002 */  mul.s $f0, $f0, $f28
/* 05CB90 8005BF90 461A0500 */  add.s $f20, $f0, $f26
/* 05CB94 8005BF94 00008021 */  addu  $s0, $zero, $zero
/* 05CB98 8005BF98 00101080 */  sll   $v0, $s0, 2
.L8005BF9C:
/* 05CB9C 8005BF9C 00511021 */  addu  $v0, $v0, $s1
/* 05CBA0 8005BFA0 8C420000 */  lw    $v0, ($v0)
/* 05CBA4 8005BFA4 50400009 */  beql  $v0, $zero, .L8005BFCC
/* 05CBA8 8005BFA8 26100001 */   addiu $s0, $s0, 1
/* 05CBAC 8005BFAC 8C440004 */  lw    $a0, 4($v0)
/* 05CBB0 8005BFB0 4405A000 */  mfc1  $a1, $f20
/* 05CBB4 8005BFB4 3C063F80 */  lui   $a2, 0x3f80
/* 05CBB8 8005BFB8 4407A000 */  mfc1  $a3, $f20
/* 05CBBC 8005BFBC 00000000 */  nop   
/* 05CBC0 8005BFC0 0C028340 */  jal   func_800A0D00
/* 05CBC4 8005BFC4 24840024 */   addiu $a0, $a0, 0x24
/* 05CBC8 8005BFC8 26100001 */  addiu $s0, $s0, 1
.L8005BFCC:
/* 05CBCC 8005BFCC 2A020004 */  slti  $v0, $s0, 4
/* 05CBD0 8005BFD0 1440FFF2 */  bnez  $v0, .L8005BF9C
/* 05CBD4 8005BFD4 00101080 */   sll   $v0, $s0, 2
/* 05CBD8 8005BFD8 08016FD9 */  j     func_8005BF64
/* 05CBDC 8005BFDC 00000000 */   nop   

/* 05CBE0 8005BFE0 8FBF0018 */  lw    $ra, 0x18($sp)
/* 05CBE4 8005BFE4 8FB10014 */  lw    $s1, 0x14($sp)
/* 05CBE8 8005BFE8 8FB00010 */  lw    $s0, 0x10($sp)
/* 05CBEC 8005BFEC D7BE0048 */  ldc1  $f30, 0x48($sp)
/* 05CBF0 8005BFF0 D7BC0040 */  ldc1  $f28, 0x40($sp)
/* 05CBF4 8005BFF4 D7BA0038 */  ldc1  $f26, 0x38($sp)
/* 05CBF8 8005BFF8 D7B80030 */  ldc1  $f24, 0x30($sp)
/* 05CBFC 8005BFFC D7B60028 */  ldc1  $f22, 0x28($sp)
/* 05CC00 8005C000 D7B40020 */  ldc1  $f20, 0x20($sp)
/* 05CC04 8005C004 03E00008 */  jr    $ra
/* 05CC08 8005C008 27BD0050 */   addiu $sp, $sp, 0x50

glabel func_8005C00C
/* 05CC0C 8005C00C 27BDFFD0 */  addiu $sp, $sp, -0x30
/* 05CC10 8005C010 AFBF002C */  sw    $ra, 0x2c($sp)
/* 05CC14 8005C014 AFB60028 */  sw    $s6, 0x28($sp)
/* 05CC18 8005C018 AFB50024 */  sw    $s5, 0x24($sp)
/* 05CC1C 8005C01C AFB40020 */  sw    $s4, 0x20($sp)
/* 05CC20 8005C020 AFB3001C */  sw    $s3, 0x1c($sp)
/* 05CC24 8005C024 AFB20018 */  sw    $s2, 0x18($sp)
/* 05CC28 8005C028 AFB10014 */  sw    $s1, 0x14($sp)
/* 05CC2C 8005C02C AFB00010 */  sw    $s0, 0x10($sp)
/* 05CC30 8005C030 00808021 */  addu  $s0, $a0, $zero
/* 05CC34 8005C034 0C014AA3 */  jal   GetPlayerStruct
/* 05CC38 8005C038 2404FFFF */   li    $a0, -1
/* 05CC3C 8005C03C 0040A021 */  addu  $s4, $v0, $zero
/* 05CC40 8005C040 00008821 */  addu  $s1, $zero, $zero
/* 05CC44 8005C044 3C16800E */  lui   $s6, %hi(D_800D8930) # $s6, 0x800e
/* 05CC48 8005C048 26D68930 */  addiu $s6, %lo(D_800D8930) # addiu $s6, $s6, -0x76d0
/* 05CC4C 8005C04C 2415FFFF */  li    $s5, -1
/* 05CC50 8005C050 00108400 */  sll   $s0, $s0, 0x10
/* 05CC54 8005C054 00109C03 */  sra   $s3, $s0, 0x10
/* 05CC58 8005C058 00111880 */  sll   $v1, $s1, 2
.L8005C05C:
/* 05CC5C 8005C05C 00769021 */  addu  $s2, $v1, $s6
/* 05CC60 8005C060 AE400000 */  sw    $zero, ($s2)
/* 05CC64 8005C064 3C02800F */  lui   $v0, 0x800f
/* 05CC68 8005C068 00431021 */  addu  $v0, $v0, $v1
/* 05CC6C 8005C06C 844233D8 */  lh    $v0, 0x33d8($v0)
/* 05CC70 8005C070 50550017 */  beql  $v0, $s5, .L8005C0D0
/* 05CC74 8005C074 26310001 */   addiu $s1, $s1, 1
/* 05CC78 8005C078 3C04800F */  lui   $a0, 0x800f
/* 05CC7C 8005C07C 00832021 */  addu  $a0, $a0, $v1
/* 05CC80 8005C080 948433D8 */  lhu   $a0, 0x33d8($a0)
/* 05CC84 8005C084 3C05800F */  lui   $a1, 0x800f
/* 05CC88 8005C088 00A32821 */  addu  $a1, $a1, $v1
/* 05CC8C 8005C08C 0C013081 */  jal   GetAbsSpaceIndexFromChainSpaceIndex
/* 05CC90 8005C090 94A533DA */   lhu   $a1, 0x33da($a1)
/* 05CC94 8005C094 00021400 */  sll   $v0, $v0, 0x10
/* 05CC98 8005C098 00022403 */  sra   $a0, $v0, 0x10
/* 05CC9C 8005C09C 1093000C */  beq   $a0, $s3, .L8005C0D0
/* 05CCA0 8005C0A0 26310001 */   addiu $s1, $s1, 1
/* 05CCA4 8005C0A4 0C01307B */  jal   GetSpaceData
/* 05CCA8 8005C0A8 00000000 */   nop   
/* 05CCAC 8005C0AC 0C00EE08 */  jal   func_8003B820
/* 05CCB0 8005C0B0 00408021 */   addu  $s0, $v0, $zero
/* 05CCB4 8005C0B4 AE420000 */  sw    $v0, ($s2)
/* 05CCB8 8005C0B8 8E850020 */  lw    $a1, 0x20($s4)
/* 05CCBC 8005C0BC 00402021 */  addu  $a0, $v0, $zero
/* 05CCC0 8005C0C0 24A5000C */  addiu $a1, $a1, 0xc
/* 05CCC4 8005C0C4 3C07432A */  lui   $a3, 0x432a
/* 05CCC8 8005C0C8 0C00F066 */  jal   func_8003C198
/* 05CCCC 8005C0CC 26060004 */   addiu $a2, $s0, 4
.L8005C0D0:
/* 05CCD0 8005C0D0 2A220004 */  slti  $v0, $s1, 4
/* 05CCD4 8005C0D4 1440FFE1 */  bnez  $v0, .L8005C05C
/* 05CCD8 8005C0D8 00111880 */   sll   $v1, $s1, 2
/* 05CCDC 8005C0DC 3C048006 */  lui   $a0, %hi(D_8005BF08) # $a0, 0x8006
/* 05CCE0 8005C0E0 2484BF08 */  addiu $a0, %lo(D_8005BF08) # addiu $a0, $a0, -0x40f8
/* 05CCE4 8005C0E4 24054800 */  li    $a1, 18432
/* 05CCE8 8005C0E8 00003021 */  addu  $a2, $zero, $zero
/* 05CCEC 8005C0EC 0C01770A */  jal   InitProcess
/* 05CCF0 8005C0F0 00003821 */   addu  $a3, $zero, $zero
/* 05CCF4 8005C0F4 3C01800E */  lui   $at, %hi(D_800D8940) # $at, 0x800e
/* 05CCF8 8005C0F8 AC228940 */  sw    $v0, %lo(D_800D8940)($at)
/* 05CCFC 8005C0FC 8FBF002C */  lw    $ra, 0x2c($sp)
/* 05CD00 8005C100 8FB60028 */  lw    $s6, 0x28($sp)
/* 05CD04 8005C104 8FB50024 */  lw    $s5, 0x24($sp)
/* 05CD08 8005C108 8FB40020 */  lw    $s4, 0x20($sp)
/* 05CD0C 8005C10C 8FB3001C */  lw    $s3, 0x1c($sp)
/* 05CD10 8005C110 8FB20018 */  lw    $s2, 0x18($sp)
/* 05CD14 8005C114 8FB10014 */  lw    $s1, 0x14($sp)
/* 05CD18 8005C118 8FB00010 */  lw    $s0, 0x10($sp)
/* 05CD1C 8005C11C 03E00008 */  jr    $ra
/* 05CD20 8005C120 27BD0030 */   addiu $sp, $sp, 0x30

glabel func_8005C124
/* 05CD24 8005C124 27BDFFE0 */  addiu $sp, $sp, -0x20
/* 05CD28 8005C128 AFBF001C */  sw    $ra, 0x1c($sp)
/* 05CD2C 8005C12C AFB20018 */  sw    $s2, 0x18($sp)
/* 05CD30 8005C130 AFB10014 */  sw    $s1, 0x14($sp)
/* 05CD34 8005C134 AFB00010 */  sw    $s0, 0x10($sp)
/* 05CD38 8005C138 00008821 */  addu  $s1, $zero, $zero
/* 05CD3C 8005C13C 3C12800E */  lui   $s2, %hi(D_800D8930) # $s2, 0x800e
/* 05CD40 8005C140 26528930 */  addiu $s2, %lo(D_800D8930) # addiu $s2, $s2, -0x76d0
/* 05CD44 8005C144 00111080 */  sll   $v0, $s1, 2
.L8005C148:
/* 05CD48 8005C148 00528021 */  addu  $s0, $v0, $s2
/* 05CD4C 8005C14C 8E040000 */  lw    $a0, ($s0)
/* 05CD50 8005C150 10800004 */  beqz  $a0, .L8005C164
/* 05CD54 8005C154 00000000 */   nop   
/* 05CD58 8005C158 0C00EE29 */  jal   func_8003B8A4
/* 05CD5C 8005C15C 00000000 */   nop   
/* 05CD60 8005C160 AE000000 */  sw    $zero, ($s0)
.L8005C164:
/* 05CD64 8005C164 3C04800E */  lui   $a0, %hi(D_800D8940) # $a0, 0x800e
/* 05CD68 8005C168 8C848940 */  lw    $a0, %lo(D_800D8940)($a0)
/* 05CD6C 8005C16C 10800005 */  beqz  $a0, .L8005C184
/* 05CD70 8005C170 26310001 */   addiu $s1, $s1, 1
/* 05CD74 8005C174 0C017764 */  jal   EndProcess
/* 05CD78 8005C178 00000000 */   nop   
/* 05CD7C 8005C17C 3C01800E */  lui   $at, %hi(D_800D8940) # $at, 0x800e
/* 05CD80 8005C180 AC208940 */  sw    $zero, %lo(D_800D8940)($at)
.L8005C184:
/* 05CD84 8005C184 2A220004 */  slti  $v0, $s1, 4
/* 05CD88 8005C188 1440FFEF */  bnez  $v0, .L8005C148
/* 05CD8C 8005C18C 00111080 */   sll   $v0, $s1, 2
/* 05CD90 8005C190 8FBF001C */  lw    $ra, 0x1c($sp)
/* 05CD94 8005C194 8FB20018 */  lw    $s2, 0x18($sp)
/* 05CD98 8005C198 8FB10014 */  lw    $s1, 0x14($sp)
/* 05CD9C 8005C19C 8FB00010 */  lw    $s0, 0x10($sp)
/* 05CDA0 8005C1A0 03E00008 */  jr    $ra
/* 05CDA4 8005C1A4 27BD0020 */   addiu $sp, $sp, 0x20

/* 05CDA8 8005C1A8 00000000 */  nop   
/* 05CDAC 8005C1AC 00000000 */  nop   
